### ISSUE TITLE
Unable to connect Elassandra 2.4.5 with Java driver sql4es

### ISSUE THREAD

**Issue by writeaditya** [strapdata/elassandra#106]
Hi Vincent,

I'am unable to connect elassandra with java code using version 2.4.5 , however i was able to connect when version was 2.4.2. Elassandra is installed on Ubuntu 16.04, running successfully from URL. I'am using following code for connection 

package es.dbConnection;

import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;

public class Connection {

	public static void DbConn() {

		try {
			Class.forName("nl.anchormen.sql4es.jdbc.ESDriver");
			java.sql.Connection con = DriverManager.getConnection("jdbc:sql4es://192.168.4.55:9300/twitter?cluster.name=TestCluster");
			Statement st = con.createStatement();
			ResultSet rs = st.executeQuery("SELECT * FROM tweet");
			ResultSetMetaData resultSetMetaData = rs.getMetaData();
			int resCol = resultSetMetaData.getColumnCount();
			System.out.println(rs.toString());
			System.out.println(rs.getString(1));
			while (rs.next()) {
				for (int i = 1; i <=resCol; i++) {
					System.out.println(rs.getObject(i));
				}
			}
			rs.close();
			con.close();
		} catch (ClassNotFoundException | SQLException e) {
			e.printStackTrace();
		}
	}
}

Using sql4es-0.9.2.4.jar for connection. 
when running code , gives following error -

java.sql.SQLException: Unable to connect to database
	at nl.anchormen.sql4es.jdbc.ESConnection.buildClient(ESConnection.java:129)
	at nl.anchormen.sql4es.jdbc.ESConnection.<init>(ESConnection.java:78)
	at nl.anchormen.sql4es.jdbc.ESDriver.connect(ESDriver.java:46)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at es.dbConnection.Connection.DbConn(Connection.java:15)
	at es.main.main.main(main.java:9)
Caused by: NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{192.168.4.55}{192.168.4.55:9300}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:326)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:223)
	at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:295)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:348)
	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1221)
	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.exists(AbstractClient.java:1241)
	at nl.anchormen.sql4es.jdbc.ESConnection.buildClient(ESConnection.java:122)
	... 6 more

Please suggest.

**Comment by vroyer** [comment]
Hi,

This is likely because your cluster.name parameter does not match your Elassandra cluster name.
If you have a space in your Elassandra cluster name "Test Cluster", use the following URL jdbc:sql4es://192.168.4.55:9300/twitter?cluster.name=Test%20Cluster

Thanks,
Vincent.

**Comment by writeaditya** [comment]
Hi Vincent,

As you suggested I have fixed my cluster name but still I'am getting this error. Now http://192.168.4.55:9200 shows follows information -

{
  "name" : "192.168.4.55",
  "cluster_name" : "Test Cluster",
  "cluster_uuid" : "e0c76265-ad14-4966-af4b-9ec052858c9e",
  "version" : {
    "number" : "2.4.5",
    "build_hash" : "${buildNumber}",
    "build_timestamp" : "2017-06-22T14:41:58Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.4"
  },
  "tagline" : "You Know, for Search"
}

Java code is as follows - 

public static void DbConn() {

		try {
			Class.forName("nl.anchormen.sql4es.jdbc.ESDriver");
			java.sql.Connection con = DriverManager.getConnection("jdbc:sql4es://192.168.4.55:9300/twitter?cluster.name=Test%20Cluster");
			Statement st = con.createStatement();
			ResultSet rs = st.executeQuery("SELECT * FROM tweet");
			ResultSetMetaData resultSetMetaData = rs.getMetaData();
			int resCol = resultSetMetaData.getColumnCount();
			System.out.println(rs.toString());
			System.out.println(rs.getString(1));
			while (rs.next()) {
				for (int i = 1; i <=resCol; i++) {
					System.out.println(rs.getObject(i));
				}
			}
			rs.close();
			con.close();
		} catch (ClassNotFoundException | SQLException e) {
			e.printStackTrace();
		}
}

Getting following Error -

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.sql.SQLException: Unable to connect to database
	at nl.anchormen.sql4es.jdbc.ESConnection.buildClient(ESConnection.java:129)
	at nl.anchormen.sql4es.jdbc.ESConnection.<init>(ESConnection.java:78)
	at nl.anchormen.sql4es.jdbc.ESDriver.connect(ESDriver.java:46)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at es.dbConnection.Connection.DbConn(Connection.java:15)
	at es.main.main.main(main.java:9)
Caused by: NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{192.168.4.55}{192.168.4.55:9300}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:326)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:223)
	at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:295)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:348)
	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1221)
	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.exists(AbstractClient.java:1241)
	at nl.anchormen.sql4es.jdbc.ESConnection.buildClient(ESConnection.java:122)
	... 6 more

**Comment by writeaditya** [comment]
Also , I checked if my port was working so i used this command - 

netstat -tulpn | grep -i listen | grep 25510

It shows port is listening for 192.168.4.55:9300

**Comment by vroyer** [comment]
Does your twitter index exists on your cluster ? 
What is your cluster state when this test fails ?

**Comment by writeaditya** [comment]
Hi ,

Yes twitter index was on cluster. I was able to access content of twitter from URL but not from java api . May be there is some issue with the Elassandra . When I downgraded it to 2.4.2 , it worked fine. 

Thanks,
