### ISSUE TITLE
Partitioner choice

### ISSUE THREAD

**Issue by adisharoon** [strapdata/elassandra#107]
It looks like Elassandra expects Murmur3Partitioner.  We are trying to implement Elassandra in older clusters that are using RandomPartitioner.  Are there any options for configuring the type mapping for different partitioners?

```
2017-08-08 16:25:56,369 WARN  [elasticsearch[172.31.28.41][clusterService#updateTask][T#1]] InternalClusterService.java:805 runTasksForExecutor [172.31.28.41] failed to apply updated cluster state in 958ms:
version [6], uuid [DfT1tkJ5Q12E7Fxew4uvNg], source [create-index [my_keyspace], cause [api]]
nodes:
   {35.158.75.80}{b095621b-503c-4c1f-9ff8-1cd335241958}{35.158.75.80}{35.158.75.80:9300}{rack=a, data=true, data_center=my_datacenter, master=true}, local, master
routing_table (version 0):
routing_nodes:
-----node_id[b095621b-503c-4c1f-9ff8-1cd335241958][V]
---- unassigned

java.lang.ClassCastException: org.apache.cassandra.dht.RandomPartitioner$BigIntegerToken cannot be cast to org.apache.cassandra.dht.Murmur3Partitioner$LongToken
        at org.apache.cassandra.dht.Murmur3Partitioner$LongToken.compareTo(Murmur3Partitioner.java:171)
        at org.apache.cassandra.dht.Murmur3Partitioner$LongToken.compareTo(Murmur3Partitioner.java:138)
        at java.util.ComparableTimSort.countRunAndMakeAscending(ComparableTimSort.java:320)
        at java.util.ComparableTimSort.sort(ComparableTimSort.java:188)
        at java.util.Arrays.sort(Arrays.java:1312)
        at java.util.Arrays.sort(Arrays.java:1506)
        at java.util.ArrayList.sort(ArrayList.java:1454)
        at java.util.Collections.sort(Collections.java:141)
        at org.elassandra.cluster.routing.AbstractSearchStrategy$Router.<init>(AbstractSearchStrategy.java:119)
        at org.elassandra.cluster.routing.PrimaryFirstSearchStrategy$PrimaryFirstRouter.<init>(PrimaryFirstSearchStrategy.java:52)
        at org.elassandra.cluster.routing.PrimaryFirstSearchStrategy.newRouter(PrimaryFirstSearchStrategy.java:45)
        at org.elassandra.cluster.InternalCassandraClusterService.updateRouter(InternalCassandraClusterService.java:448)
        at org.elasticsearch.cluster.routing.IndexRoutingTable$Builder.<init>(IndexRoutingTable.java:418)
        at org.elasticsearch.cluster.routing.RoutingTable.build(RoutingTable.java:408)
        at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:759)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:918)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by vroyer** [comment]
Hi,
The RandomPartitioner is not supported by Elassandra, because RandomPartitioner use BigInteger tokens, and BigInteger are not natively indexable in lucene 5.
