### ISSUE TITLE
jar hell exception when installing x-pack

### ISSUE THREAD

**Issue by ghost** [strapdata/elassandra#143]
**Elasticsearch version**:
elassandra 5.5.0.8

**Plugins installed**: []

none

**JVM version**:

java version "1.8.0_144"

**OS version**:
fedora 26

**Description of the problem including expected versus actual behavior**:
unability to install x-pack. Please advice how to correctly overcome the issue.

**Steps to reproduce**:
elasticsearch-plugin install x-pack

**Provide logs (if relevant)**:

16:46:37.133 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: /opt/elassandra/elassandra/lib/httpcore-4.4.5.jar
16:46:37.134 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: /opt/elassandra/elassandra/lib/jopt-simple-5.0.2.jar
16:46:37.134 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: /opt/elassandra/elassandra/lib/jamm-0.3.0.jar
16:46:37.135 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: /opt/elassandra/elassandra/lib/netty-all-4.1.12.Final.jar
Exception in thread "main" java.lang.IllegalStateException: jar hell!
class: io.netty.buffer.AbstractByteBufAllocator$1
jar1: /opt/elassandra/elassandra/plugins/.installing-7339951944987515494/netty-buffer-4.1.11.Final.jar
jar2: /opt/elassandra/elassandra/lib/netty-all-4.1.12.Final.jar
	at org.elasticsearch.bootstrap.JarHell.checkClass(JarHell.java:299)
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:192)
	at org.elasticsearch.plugins.InstallPluginCommand.jarHellCheck(InstallPluginCommand.java:531)
	at org.elasticsearch.plugins.InstallPluginCommand.verify(InstallPluginCommand.java:500)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:543)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:217)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:201)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.Command.main(Command.java:88)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)

**Comment by vroyer** [comment]
Sorry, but the pack from elasticsearch is not supported because it’s private code (and it elasticsearch won’t support too as specified in their support-policy).
If you need monitoring or security features, strapdata provides an Enterprise edition including theses feature and technical support.
