### ISSUE TITLE
Docs no longer indexing in some ES tables

### ISSUE THREAD

**Issue by rickysahu** [strapdata/elassandra#148]
**Elassandra version**: elassandra-2.4.2.15
**Plugins installed**: none
**JVM version**: OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
**OS version**: Ubuntu 16.04.3 LTS

**Description of the problem including expected versus actual behavior**: Recently new documents stopped being indexed in ES for some tables in a given keyspace. They new docs are still available in cassandra, but the elasticsearch responds with the following error: 
```
 { Error: [write_failure_exception] Operation failed - received 0 responses and 2 failures
    at respond (/Users/rickysahu/Desktop/git/1uphealth/common/js/node_modules/elasticsearch/src/lib/transport.js:289:15)
    at checkRespForFailure (/Users/rickysahu/Desktop/git/1uphealth/common/js/node_modules/elasticsearch/src/lib/transport.js:248:7)
    at HttpConnector.<anonymous> (/Users/rickysahu/Desktop/git/1uphealth/common/js/node_modules/elasticsearch/src/lib/connectors/http.js:164:7)
    at IncomingMessage.wrapper (/Users/rickysahu/Desktop/git/1uphealth/common/js/node_modules/lodash/lodash.js:4968:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  status: 500,
  displayName: 'InternalServerError',
  message: '[write_failure_exception] Operation failed - received 0 responses and 2 failures',
  path: '/keyspace1_table1/table1/%5B%22a098caf83bbc%22%2C%22%22%2C%229000000000000%22%5D',
  query: {},
  body: '{....}',
  statusCode: 500,
  response: '{"error":{"root_cause":[{"type":"write_failure_exception","reason":"Operation failed - received 0 responses and 2 failures"}],"type":"write_failure_exception","reason":"Operation failed - received 0 responses and 2 failures"},"status":500}',
  toString: [Function],
  toJSON: [Function] }
```
Previously indexed docs are still available in ES. Also this index query used to work. The new doc does appear in and is queryable from cassandra. But its not available in elastic even after some time. Using cassandra to write the doc also produce the same error. Some tables are still working fine with new docs indexed in ES.

**Steps to reproduce**:
 1. create an ES index on a table using the discover * function
 2.  `es_client.index({index:'keyspace1_table1', type:'table1', body:this_doc, id: '["a098caf83bbc","","9000000000000"]'}, function(body){console.log(body)})`

**Provide logs (if relevant)**:
These logs are similar to the ones reported in  (similar to the error in #135), but i believe the fix is not related.
## system.log
```
2017-12-08 14:34:33,022 ERROR [SharedPool-Worker-1] StorageProxy.java:1350 runMayThrow Failed to apply mutation locally : {}
java.lang.RuntimeException: null for ks: keyspace1, table: table1
	at org.apache.cassandra.db.ColumnFamilyStore.apply(ColumnFamilyStore.java:1210)
	at org.apache.cassandra.db.Keyspace.applyInternal(Keyspace.java:578)
	at org.apache.cassandra.db.Keyspace.apply(Keyspace.java:426)
	at org.apache.cassandra.db.Mutation.apply(Mutation.java:210)
	at org.apache.cassandra.db.Mutation.apply(Mutation.java:215)
	at org.apache.cassandra.db.Mutation.apply(Mutation.java:224)
	at org.apache.cassandra.service.StorageProxy$8.runMayThrow(StorageProxy.java:1344)
	at org.apache.cassandra.service.StorageProxy$LocalMutationRunnable.run(StorageProxy.java:2516)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:164)
	at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$LocalSessionFutureTask.run(AbstractLocalAwareExecutorService.java:136)
	at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:105)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
2017-12-08 14:34:33,077 WARN  [SharedPool-Worker-3] AbstractLocalAwareExecutorService.java:169 run Uncaught exception on thread Thread[SharedPool-Worker-3,5,main]: {}
java.lang.RuntimeException: null for ks: keyspace1, table: table2

```
This continues to happen for other tables in the keyspace, but not all of them. Some can still accept new writes which get indexed in ES.

**Comment by vroyer** [comment]
Would you have the document body of the failed write request ?
Could you provide your cluster state, and the output of "nodetool gossiping » ?
Thanks.

**Comment by rickysahu** [comment]
Is there some limit on the size of a indexed nested datatype within elasticsearch through the mappings made by elassandra?

I believe this behavior is being caused by an issue with an ES Secondary index and any doc that uses that index (based on a specific cassandra datatype) fails to be available in ES. This is some more logs i got in system.log, however they appear periodically, not immediately after indexing a new doc. This specific data type is used in nearly all documents and is significantly large.
```
2017-12-08 18:52:01,039 ERROR [SharedPool-Worker-1] ElasticSecondaryIndex.java:502 addField Unexpected subfield=system for field=code column type=frozen<dt_codeconcept>, ignoring value=null
2017-12-08 18:52:01,039 ERROR [SharedPool-Worker-1] ElasticSecondaryIndex.java:502 addField Unexpected subfield=code for field=code column type=frozen<dt_codeconcept>, ignoring value=null
2017-12-08 18:52:01,039 ERROR [SharedPool-Worker-1] ElasticSecondaryIndex.java:502 addField Unexpected subfield=display for field=code column type=frozen<dt_codeconcept>, ignoring value=null
2017-12-08 18:52:01,047 ERROR [SharedPool-Worker-2] ElasticSecondaryIndex.java:502 addField Unexpected subfield=system for field=activity column type=frozen<dt_codeconcept>, ignoring value=null
2017-12-08 18:52:01,047 ERROR [SharedPool-Worker-2] ElasticSecondaryIndex.java:502 addField Unexpected subfield=code for field=activity column type=frozen<dt_codeconcept>, ignoring value=null
2017-12-08 18:52:01,047 ERROR [SharedPool-Worker-2] ElasticSecondaryIndex.java:502 addField Unexpected subfield=display for field=activity column type=frozen<dt_codeconcept>, ignoring value=null
2017-12-08 18:52:01,102 ERROR [SharedPool-Worker-5] ElasticSecondaryIndex.java:502 addField Unexpected subfield=system for field=code column type=frozen<dt_codeconcept>, ignoring value=null
...
2017-12-08 18:58:59,798 INFO  [SharedPool-Worker-3] Message.java:615 apply Unexpected exception during request; channel = [id: 0xbf67a490, L:/xxxx.xxx.xxx.1:9042 ! R:/xxx.xxx.xxx.2:58100]
io.netty.channel.unix.Errors$NativeIoException: syscall:read(...)() failed: Connection reset by peer
	at io.netty.channel.unix.FileDescriptor.readAddress(...)(Unknown Source)
2017-12-08 19:01:04,751 INFO  [SharedPool-Worker-2] NoSpamLogger.java:91 log Maximum memory usage reached (536870912 bytes), cannot allocate chunk of 1048576 bytes
2017-12-08 19:02:02,865 ERROR [SharedPool-Worker-4] ElasticSecondaryIndex.java:502 addField Unexpected subfield=system for field=code column type=frozen<dt_codeconcept>, ignoring value=null
2017-12-08 19:02:02,866 ERROR [SharedPool-Worker-4] ElasticSecondaryIndex.java:502 addField Unexpected subfield=code for field=code column type=frozen<dt_codeconcept>, ignoring value=null
2017-12-08 19:02:02,866 ERROR [SharedPool-Worker-4] ElasticSecondaryIndex.java:502 addField Unexpected subfield=display for field=code column type=frozen<dt_codeconcept>, ignoring value=null
2017-12-08 19:02:02,872 ERROR [SharedPool-Worker-1] ElasticSecondaryIndex.java:502 addField Unexpected subfield=system for field=activity column type=frozen<dt_codeconcept>, ignoring value=null
...
```

So for example this body successfully can be written and read from ES and Cass:
```
{
  "private_shardid": "a098caf83bbx",
  "private_id": "",
  "private_version": "9000000000000",
  "identifier": [
    {
      "value": "c"
    },
    {
      "_m": "m"
    }
  ]
}
```

And this one cannot (it only shows up in Cass) because it includes a field which is of the datatype dt_codeconcept (nested within identifier[0].type = {dt_codeconcept}
```
{
  "private_shardid": "a098caf83bbw",
  "private_id": "",
  "private_version": "9000000000000",
  "identifier": [
    {
      "type": {
        "coding": [
          {
            "system": "a",
            "code": "b"
          },
          {
            "_m": "m"
          }
        ]
      },
      "value": "c"
    },
    {
      "_m": "m"
    }
  ]
}

this one also fails
{
  "private_shardid": "a098caf83bby",
  "private_id": "",
  "private_version": "9000000000000",
  "identifier": [
    {
      "value": "c",
      "type": [
        {
          "_m": "m"
        }
      ]
    },
    {
      "_m": "m"
    }
  ]
}
```
## Nested datatype structure
```
-- Coding
CREATE TYPE fhirdstu2.dt_coding (
  "code" text,
  "system" text,
  "_m" text
);

-- CodeConcept
CREATE TYPE fhirdstu2.dt_codeconcept (
  "id" text,
  "coding" list<FROZEN<dt_coding>>,
  "_m" text
);

-- Identifier
CREATE TYPE fhirdstu2.dt_identifier (
  "value" text,
  "type" FROZEN<dt_codeconcept>,
  "_m" text
);
```


## Status
```
Datacenter: us-west-2_1_cassandra
=================================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address        Load       Tokens       Owns    Host ID                               Rack
UN  xxx.xxx.xxx.1   9.3 GB     256          ?       f83f1b22-bd00-4bdf-822a-19c68cdbec45  2a
UN  xxx.xxx.xxx.2  11.17 GB   256          ?       671926eb-4135-47cd-887b-a8bc748afdca  2c
```

## Gossipinfo
```
/xxx.xxx.xxx.1
  generation:1511890043
  heartbeat:2641494
  STATUS:23:NORMAL,-1105952359864929273
  LOAD:2641350:9.990486173E9
  SCHEMA:2633957:32633804-4368-3a5f-a3f4-e4ef1ee36deb
  DC:6:us-west-2_1_cassandra
  RACK:8:2a
  RELEASE_VERSION:4:3.0.11
  RPC_ADDRESS:3:xxx.xxx.xxx.1
  SEVERITY:2641496:0.2525252401828766
  NET_VERSION:1:10
  HOST_ID:2:f83f1b22-bd00-4bdf-822a-19c68cdbec45
  RPC_READY:74:true
  X1:1961250:{"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"logging2_applog":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3}
  X2:2633762:f83f1b22-bd00-4bdf-822a-19c68cdbec45/95
  TOKENS:22:<hidden>
/xxx.xxx.xxx.2
  generation:1511888319
  heartbeat:2646858
  STATUS:24:NORMAL,-100026142743920206
  LOAD:2646752:1.1993446369E10
  SCHEMA:2639324:32633804-4368-3a5f-a3f4-e4ef1ee36deb
  DC:6:us-west-2_1_cassandra
  RACK:8:2c
  RELEASE_VERSION:4:3.0.11
  RPC_ADDRESS:3:xxx.xxx.xxx.2
  SEVERITY:2646857:0.0
  NET_VERSION:1:10
  HOST_ID:2:671926eb-4135-47cd-887b-a8bc748afdca
  RPC_READY:61:true
  X1:1966627:{"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"logging2_applog":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3,"keyspace1_table":3}
  X2:2639129:f83f1b22-bd00-4bdf-822a-19c68cdbec45/95
  TOKENS:23:<hidden>
```
because this data type is used in nearly each table (and for each doc type), at this point it seems like one workaround may be to use a namespaced method for creating datatypes (like dt_table1_codeconcept, and duplicate that for table2 as dt_table2_codeconcept, etc.). but thats only useful if there is some sort of ES limit being imposed on the nested datatype based fields

thanks for taking a look.

**Comment by vroyer** [comment]
That’s strange, you’ve got about 60 entries in Gossip.X1, meaning that you’ve about 60 shards opened on each node with the same name keyspace1_table.
How did you create your index ?

If can stop your application, i would recommend to upgrade to elassandra 5.5 and rebuild your index as follow :
1-make a C* snapshot and save your ES mapping in a text file.
2-delete all your ES indices
3-stop all nodes
4-upgrade to elassandra 5.5 (keep your data dir unchanged)
5-start all nodes
6-recreate your indices from the saved ES mapping + some changes coming from ES 5.5. It will rebuild ES indices from C* tables. 

Thanks.

**Comment by rickysahu** [comment]
sorry that keyspace_table is a unique table each time i just changed the name so that i didnt publicly divulge the domain of this work. i have 60 unique tables ok thanks im working on the upgrade. will report back

**Comment by vroyer** [comment]
Hi, do you have solved your issue ?
Thanks.

**Comment by rickysahu** [comment]
Yes, thanks. Upgrading did resolve the issue, but we also made some mapping changes to create datatypes under each table.
