### ISSUE TITLE
don't work UDF in elassandra 5.5.0.8

### ISSUE THREAD

**Issue by iamdenchik** [strapdata/elassandra#149]
**Elasticsearch version**: elassandra-5.5.0.8

**Plugins installed**: none

**JVM version**: OpenJDK 1.8.0_131

**OS version**: Debian 3.16.39-1+deb8u2 (docker)

* In /opt/elassandra-5.5.0.8/conf/cassandra.yaml enabled UDF:

```
enable_user_defined_functions: true
enable_scripted_user_defined_functions: true
```
* create keyspace:

```
CREATE KEYSPACE testkeyspace WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };
```

* in testkeyspace create function:

```
CREATE OR REPLACE FUNCTION first_int(input set<int>) RETURNS NULL ON NULL INPUT RETURNS int LANGUAGE javascript AS '(function(){var result = 2;return result;})();';
```

* create and insert:

```
create table A (id int primary key, val set<int>);
insert into A  (id, val) values (1, {3,5,7,1});
```

* select:

```
select first_int(val) from A where id = 1;

Traceback (most recent call last):
  File "/opt/elassandra-5.5.0.8/bin/cqlsh.py", line 1039, in perform_simple_statement
    result = future.result()
  File "/opt/elassandra-5.5.0.8/bin/../lib/cassandra-driver-internal-only-3.10.zip/cassandra-driver-3.10/cassandra/cluster.py", line 3826, in result
    raise self._final_exception
FunctionFailure: Error from server: code=1400 [User Defined Function failure] message="execution of 'testkeyspace.first_int[set<int>]' failed: java.security.AccessControlException: access denied: ("java.lang.RuntimePermission" "accessClassInPackage.java.io")"
```

* raw log
```
root@8a344b2fac43:/opt# cqlsh
Connected to Test Cluster at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.11.1.2 | CQL spec 3.4.4 | Native protocol v4]
Use HELP for help.
cqlsh> CREATE KEYSPACE testkeyspace WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };
cqlsh> USE testkeyspace;
cqlsh:testkeyspace> CREATE OR REPLACE FUNCTION first_int(input set<int>) RETURNS NULL ON NULL INPUT RETURNS int LANGUAGE javascript AS '(function(){var result = 2;return result;})();';

cqlsh:testkeyspace>
cqlsh:testkeyspace> create table A (id int primary key, val set<int>);
cqlsh:testkeyspace> insert into A  (id, val) values (1, {3,5,7,1});
cqlsh:testkeyspace> select first_int(val) from A where id = 1;
Traceback (most recent call last):
  File "/opt/elassandra-5.5.0.8/bin/cqlsh.py", line 1039, in perform_simple_statement
    result = future.result()
  File "/opt/elassandra-5.5.0.8/bin/../lib/cassandra-driver-internal-only-3.10.zip/cassandra-driver-3.10/cassandra/cluster.py", line 3826, in result
    raise self._final_exception
FunctionFailure: Error from server: code=1400 [User Defined Function failure] message="execution of 'testkeyspace.first_int[set<int>]' failed: java.security.AccessControlException: access denied: ("java.lang.RuntimePermission" "accessClassInPackage.java.io")"
```

**Comment by vroyer** [comment]
It seems to be a cassandra or a syntax issue in your function, because is does not works on the standard cassandra version 3.11.1 as show below.

```
git/apache/cassandra-cassandra-3.11.1$ bin/cqlsh
Connected to Test Cluster at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.11.1-SNAPSHOT | CQL spec 3.4.4 | Native protocol v4]
Use HELP for help.
cassandra@cqlsh> CREATE KEYSPACE testkeyspace WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };
cassandra@cqlsh> use testkeyspace ;
cassandra@cqlsh:testkeyspace> CREATE OR REPLACE FUNCTION first_int(input set<int>) RETURNS NULL ON NULL INPUT RETURNS int LANGUAGE javascript AS '(function(){var result = 2;return result;})();';
cassandra@cqlsh:testkeyspace> create table A (id int primary key, val set<int>);
cassandra@cqlsh:testkeyspace> insert into A  (id, val) values (1, {3,5,7,1});
cassandra@cqlsh:testkeyspace> select first_int(val) from A where id = 1;
Traceback (most recent call last):
  File "/Users/vroyer/Dev/git/apache/cassandra-cassandra-3.11.1/bin/cqlsh.py", line 1044, in perform_simple_statement
    result = future.result()
  File "/Users/vroyer/Dev/git/apache/cassandra-cassandra-3.11.1/bin/../lib/cassandra-driver-internal-only-3.10.zip/cassandra-driver-3.10/cassandra/cluster.py", line 3826, in result
    raise self._final_exception
FunctionFailure: Error from server: code=1400 [User Defined Function failure] message="execution of 'testkeyspace.first_int[set<int>]' failed: java.security.AccessControlException: access denied: ("java.lang.RuntimePermission" "accessClassInPackage.java.util.function")"
```

**Comment by iamdenchik** [comment]
thx!
