### ISSUE TITLE
datacenter.group

### ISSUE THREAD

**Issue by twoofy** [strapdata/elassandra#153]
Hello,

I was trying to test out the datacenter.group feature as documented here  http://doc.elassandra.io/en/latest/configuration.html#multi-datacenter-configuration

In elasticsearch.yml, I've added this line:

`datacenter.group: rack_c
`
But when the server boots it complains about not knowing how to handle it:

```
2018-01-14 06:38:18,589 ERROR [main] ElassandraDaemon.java:529 main Exception
java.lang.IllegalArgumentException: unknown setting [datacenter.group] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:293)
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:256)
	at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:139)
	at org.elasticsearch.node.Node.<init>(Node.java:348)
	at org.elasticsearch.node.Node.<init>(Node.java:245)
	at org.apache.cassandra.service.ElassandraDaemon.activate(ElassandraDaemon.java:183)
	at org.apache.cassandra.service.ElassandraDaemon.main(ElassandraDaemon.java:492)

```
Am I doing this wrong or is there more to it then this?

- Greg

**Comment by vroyer** [comment]
Hi, 
This is a settings check introduced by ES 5.5+ not reported in elassandra. 
A fix is available on this repo https://github.com/strapdata/elassandra5-rc.
It will be included in the next release.
Thanks for reporting the issue.
Vincent.
