### ISSUE TITLE
Partitioned index - Date formatting error

### ISSUE THREAD

**Issue by jMonsinjon** [strapdata/elassandra#178]
Hello, 
I'm trying to use the "partitioned index" (http://elassandra.readthedocs.io/en/v5.5.0.9/mapping.html#partitioned-index) but it seems it doesn't work.

Elassandra 5.5.0.9 (Elasticsearch 5.5.0, Cassandra 3.11.1.2, JVM 1.8.0_152)

To use the "partitioned index", I create an elasticsearch template :

```
curl -XPOST 'http://localhost:9200/_template/partitioned-index-test-template' -d '{
 "template": "partitioned-index-test-*",
 "settings": {
  "keyspace": "partitioned_index_keyspace",
  "index.partition_function": "toDayIndex partitioned-index-test-{0,date,yyyy.MM.dd} timefield",
  "index.partition_function_class": "org.elassandra.index.MessageFormatPartitionFunction"
 },
 "mappings": {
  "test": {
   "properties": {
    "timefield": {
     "type": "date"
    },
    "textfield": {
     "type": "text"
    }}}}}'
```

When I POST the first document in an index named "partitioned-index-test-2018.03.21"

```
curl -XPOST 'http://localhost:9200/partitioned-index-test-2018.03.21/test' -d '{
 "timefield": "2018-03-21T12:17:12.00Z",
 "textfield": "My text field"
}'
```

the new elasticsearch index is well created, and there is a new row in my cassandra table.
**But there is no document in the elasticsearch index**, and I can read this error in logs 

```
java.lang.RuntimeException: Cannot format given Object as a Date for ks: partitioned_index_keyspace, table: test
	at org.apache.cassandra.db.ColumnFamilyStore.apply(ColumnFamilyStore.java:1357)
	at org.apache.cassandra.db.Keyspace.applyInternal(Keyspace.java:623)
	at org.apache.cassandra.db.Keyspace.apply(Keyspace.java:467)
	at org.apache.cassandra.db.Mutation.apply(Mutation.java:227)
	at org.apache.cassandra.db.Mutation.apply(Mutation.java:232)
	at org.apache.cassandra.db.Mutation.apply(Mutation.java:241)
	at org.apache.cassandra.service.StorageProxy$8.runMayThrow(StorageProxy.java:1408)
	at org.apache.cassandra.service.StorageProxy$LocalMutationRunnable.run(StorageProxy.java:2647)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:162)
	at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:109)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Cannot format given Object as a Date
	at java.text.DateFormat.format(DateFormat.java:310)
	at java.text.Format.format(Format.java:157)
	at java.text.MessageFormat.subformat(MessageFormat.java:1322)
	at java.text.MessageFormat.format(MessageFormat.java:865)
	at java.text.Format.format(Format.java:157)
	at org.elassandra.index.MessageFormatPartitionFunction.format(MessageFormatPartitionFunction.java:34)
	at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$ImmutablePartitionFunction.indexName(ElasticSecondaryIndex.java:1010)
	at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo.targetIndices(ElasticSecondaryIndex.java:1241)
	at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$RowcumentIndexer$Rowcument.index(ElasticSecondaryIndex.java:1871)
	at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$SkinnyRowcumentIndexer$SkinnyRowcument.index(ElasticSecondaryIndex.java:1447)
	at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$SkinnyRowcumentIndexer.flush(ElasticSecondaryIndex.java:1483)
	at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$RowcumentIndexer.finish(ElasticSecondaryIndex.java:1598)
	at org.apache.cassandra.index.SecondaryIndexManager$WriteTimeTransaction.commit(SecondaryIndexManager.java:983)
	at org.apache.cassandra.db.partitions.AtomicBTreePartition.addAllWithSizeDelta(AtomicBTreePartition.java:181)
	at org.apache.cassandra.db.Memtable.put(Memtable.java:284)
	at org.apache.cassandra.db.ColumnFamilyStore.apply(ColumnFamilyStore.java:1339)
	... 11 common frames omitted
```

Before looking for a potentially bug, I develop my own very simple partition function.
Modify my template and re create all from scratch (and restart elassandra of course).

**Now, when I push new documents, there is no errors, but still no documents in the Elasticsearch index.**

So I add a log message (with slf4j) at the entrance of my partition function.

```
@Override
public String format(String pattern, Object... args) {

    logger.info("CUSTOM MESSAGE TO TRACE EXECUTION");

    return pattern + "2018.03.21";
}
```

With this new version, the first time I push a document, **I can see my log message**. But the message **appears randomly** on each new documents.
Anyway, **still no document in my Elasticsearch index**, but every document exists in the cassandra table.

Did am I the only guy using this feature ?
Could you please help me ?
Is it a bug, or did I use it in the wrong way ?

**Comment by vroyer** [comment]
Hi,
If you look at your CQL schema, "timefield" is a list<timestamp> because by default, elasticsearch multivalued fields are mapped to list, so it does not match the expected java.util.Date expected in your partition function. Change your template to explicitly type "timefield" to a CQL timestamp like this : 

curl -XPOST 'http://localhost:9200/_template/partitioned-index-test-template' -d '{
 "template": "partitioned-index-test-*",
 "settings": {
  "keyspace": "partitioned_index_keyspace",
  "index.partition_function": "toDayIndex partitioned-index-test-{0,date,yyyy.MM.dd} timefield",
  "index.partition_function_class": "org.elassandra.index.MessageFormatPartitionFunction"
 },
 "mappings": {
  "test": {
   "properties": {
    "timefield": {
     "type": "date",
     "cql_collection":"singleton"
    },
    "textfield": {
     "type": "text"
    }}}}}'

Remove your index and drop your keyspace, then retry with this new template mapping, and it works : 
curl -XPOST "https://$NODE:9200/partitioned-index-test-2018.03.21/test" -d '{
>  "timefield": "2018-03-21T12:17:12.00Z",
>  "textfield": "My text field"
> }'
{"_index":"partitioned-index-test-2018.03.21","_type":"test","_id":"AWJkfp0_i0Nn60Tks-eH","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"created":true}

admin@cqlsh> select * FROM partitioned_index_keyspace.test ;
 _id                                | textfield                  | timefield
----------------------+-------------------+---------------------------------
 AWJkeWNVi0Nn60Tks-eF | ['My text field'] | 2018-03-21 12:17:12.000000+0000

**Comment by Scale93** [comment]
Hello, I'm using Elassandra version: 6.2.3

**At first I have created the keyspace and a table inside my cassandra cluster:**

CREATE KEYSPACE test WITH replication = {'class': 'NetworkTopologyStrategy', 'DC1': '1'}  AND durable_writes = true;

CREATE TABLE test.my_test_table (
    i_d text,
    date_field timestamp,
    my_id text,
    value text,
    PRIMARY KEY (i_d, date_field, my_id)
) WITH CLUSTERING ORDER BY (date_field DESC, my_id ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';

**After that I have created an index with the discover method:**

curl -XPUT 'http://<MyHost>:9200/test_2018' -H 'Content-Type: application/json' -d '{
    "settings": { 
        "keyspace":"test",
        "index.partition_function":"toYearIndex test_{0,date,yyyy} date_field",
        "index.partition_function_class":"MessageFormatPartitionFunction"
    },
    "mappings": {
        "my_test_table": {"discover" : ".*"}
    }
}'

**I have checked that the index was created correctly**

curl "<MyHost>:9200/_cat/indices"

RESPONSE:
green open test_2018 oE6uE4jLQEOM39Yew1i8yQ 3 0 0 0  624b  624b

**INSERT some data inside cassandra table**

INSERT INTO test.my_test_table (i_d, date_field, my_id, value) VALUES ( 'Id001',dateof(now()),'MyID001','VALUE001');


**Finally i can't see anything inside my elastic index, i have tried also whit explicit mapping but it sill doesn't work!**
