### ISSUE TITLE
Elasticsearch indices are red

### ISSUE THREAD

**Issue by ignatev** [strapdata/elassandra#190]
**Elasticsearch version**: 5.5.0.14

**JVM version**: 1.8

**OS version**: Ubuntu 16.04 LTS

**Description of the problem including expected versus actual behavior**:
I have elassandra cluster with 5 replicas.
One of elassandra nodes has red indecies, other nodes work.
I tried to rebuild, flush, reboot but without result.

> curl localhost:9200/_cat/indices?v
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2641  100  2641    0     0   363k      0 --:--:-- --:--:-- --:--:--  368k
health status index                                       uuid                   pri rep docs.count docs.deleted store.size pri.store.size
red*   open   .kibana                                     rF2i0E1KRkm3gaeb5V_chg                                                          
red*   open   commands-command                   MbMbVFHAS3OAQlIgQz13PQ                                                          
red*   open   registrations-registrationresponse wWSchmGHSAKSbPI8lAGpZg                                                          
red*   open   alarms-alarmdelayedabort           p4WOofRuQ-SwORMkyE0xtA                                                          
red*   open   registrations-registrationrequest  d-MN9hS7SiS0of2IQRyFxQ                                                          
red*   open   alarms-alarmdelayedack             neYC46fKQ4C9oYHGshbLPg                                                          
red*   open   alarms-alarm                       Yee36m7MRgW34kf3qcao8w                                                          
red*   open   alarms-alarmdelayed                Z2yi-CmAQSCV6SijfgiK3A                                                          
red*   open   alarms-alarmdeliveryresultforipcs  gyFBvpCbRPeK1J5ynmHD4g                                                          
red*   open   qos-association                    T3-PlPE-Rw-QTt8BDxn6Fw                                                          
red*   open   alarms-alarmdelayedabortack        o4beLF1qSk-vrpPkyDOYdw                                                          
red*   open   alarms-alarmack                    x1ajd2ykQMi2IX_pnZHNrA                                                          
red*   open   alarms-alarmdelayedupdateack       EKLsZZqPSE-59PcCiVnwcA                                                          
red*   open   qos-checkin                        BWBppTFWTOinp6R6LiY0dg                                                          
red*   open   alarms-alarmmessageforipcs         q_bGEnFcSuaHbzWyrn4z4Q                                                          
red*   open   alarms-alarmdelayedupdate          GeKxDyalTa-b-WgMZGCbeg                                                          
red*   open   checkins-latecheckin               axNE4e83RBeSoP1u4DwTQg                                                          
red*   open   checkins-checkin                   OKt7rDMmR1yq3R4y2M-DXQ   

Exceptions:
>2018-05-02 12:28:49,804 WARN  [elasticsearch[10.244.13.77][index][T#1]] org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.finishWithUnexpectedFailure(TransportReplicationAction.java:859) unexpected error during the primary phase for action [indices:data/write/bulk[s]], request [BulkShardRequest [[.kibana][0]] containing [index {[.kibana][config][5.5.3], source[{"buildNum":"15460","timepicker:timeDefaults":"{\n  \"from\": \"now-1d\",\n  \"to\": \"now\",\n  \"mode\": \"quick\"\n}","dateFormat:dow":"Monday","defaultIndex":null}]}]]
org.elasticsearch.index.IndexNotFoundException: no such index
	at org.elasticsearch.cluster.routing.RoutingTable.shardRoutingTable(RoutingTable.java:141)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.primary(TransportReplicationAction.java:738)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.doRun(TransportReplicationAction.java:667)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.action.support.replication.TransportReplicationAction.doExecute(TransportReplicationAction.java:147)
	at org.elasticsearch.action.support.replication.TransportReplicationAction.doExecute(TransportReplicationAction.java:92)
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:170)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:142)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:84)
	at org.elasticsearch.action.bulk.TransportBulkAction$BulkOperation.doRun(TransportBulkAction.java:363)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.action.bulk.TransportBulkAction.executeBulk(TransportBulkAction.java:478)
	at org.elasticsearch.action.bulk.TransportBulkAction.doExecute(TransportBulkAction.java:171)
	at org.elasticsearch.action.bulk.TransportBulkAction.doExecute(TransportBulkAction.java:85)
	at 

and a lot of these:
> 2018-05-02 11:18:16,518 WARN  [CompactionExecutor:1] org.elassandra.index.ElasticSecondaryIndex.isIndexing(ElasticSecondaryIndex.java:2075) No Elasticsearch index ready alarms_alarmack.kafka_connect
2018-05-02 11:18:16,519 WARN  [CompactionExecutor:1] org.elassandra.index.ElasticSecondaryIndex.isIndexing(ElasticSecondaryIndex.java:2075) No Elasticsearch index ready alarms_alarmack.kafka_connect
2018-05-02 11:18:16,519 WARN  [CompactionExecutor:1] org.elassandra.index.ElasticSecondaryIndex.isIndexing(ElasticSecondaryIndex.java:2075) No Elasticsearch index ready alarms_alarmack.kafka_connect
2018-05-02 11:18:16,519 WARN  [CompactionExecutor:1] org.elassandra.index.ElasticSecondaryIndex.isIndexing(ElasticSecondaryIndex.java:2075) No Elasticsearch index ready alarms_alarmack.kafka_connect

Here is the output of curl localhost:9200/_cluster/state/?pretty=true

>
[log.txt](https://github.com/strapdata/elassandra/files/1967241/log.txt)

Please help me to resolve this issue.

**Comment by vroyer** [comment]
You should reboot the node and check for error message in the logs, you may have a file system full or something else preventing elassandra to open elasticsearch shards.
Thanks.

**Comment by ignatev** [comment]
Thank you for the reply. 
I rebooted the node, it started to rebuild indexes but after this process, I did not find anything in logs that was related to red indices.

Finally, we rebuilt the whole cluster and now it works as expected. 
Here are the logs.
[log.txt](https://github.com/strapdata/elassandra/files/1974097/log.txt)
