### ISSUE TITLE
Deletion of ALL elements of a List doesn't removes the document on ES

### ISSUE THREAD

**Issue by andre-paris** [strapdata/elassandra#199]
**Elassandra version**: 5.5.0.18

The problem occurs from a table with a compound key and a list of any type.
When the last element of the list is removed, the row is deleted from cassandra but the document remains on ES without the source.

**Steps to reproduce**:
 1. Given the table
```sql
CREATE TABLE table_test (
    id1 text,
    id2 text,
    list list<text>,
    PRIMARY KEY (id1, id2)
);
```
 2. The ES index mapping
```json
{
  "settings": {
    "keyspace": "ks_test"
  },
  "mappings": {
    "table_test": {
      "discover": ".*"
    }
  }
}
```
 3. Insert a row into the table:
```sql
UPDATE table_test SET list = list + ['foo'] where id1='1' and id2='2';
```
 4. Search the document on ES:
```bash
get ks_test/_search?pretty=true
```
```json
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "ks_test",
        "_type" : "table_test",
        "_id" : "[\"1\",\"2\"]",
        "_score" : 1.0,
        "_source" : {
          "id2" : "2",
          "id1" : "1",
          "list" : "foo"
        }
      }
    ]
  }
```
5. Remove the last element from the list:
```sql
UPDATE table_test SET list = list - ['foo'] where id1='1' and id2='2';
```
 6. Search the document on ES again:
```bash
get ks_test/_search?pretty=true
```
```json
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "ks_test",
        "_type" : "table_test",
        "_id" : "[\"1\",\"2\"]",
        "_score" : 1.0
      }
    ]
  }
}
```
7. But on Cassandra...
```sql
SELECT * FROM table_test;
``` 
```plain
 id1 | id2 | list
-----+-----+------

(0 rows)
```
Thanks in advance.

**Comment by andre-paris** [comment]
This is a Cassandra issue: https://issues.apache.org/jira/browse/CASSANDRA-14505

**Comment by andre-paris** [comment]
According to this issue https://issues.apache.org/jira/browse/CASSANDRA-14505 , it's a natural C* behavior.

**Comment by vroyer** [comment]
Yes, you right, there is a subtil difference between INSERT and UPDATE. 
I’m going to fix that.

**Comment by vroyer** [comment]
Fixed in 5.5.0.19

**Comment by andre-paris** [comment]
Vincent, I'm getting this error when trying to run cassandra with elasticsearch enabled (bin/cassandra -e) :
```
2018-06-25 10:41:28,216 ERROR [main] ElassandraDaemon.java:588 main Exception
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:203)
	at org.elasticsearch.common.network.NetworkAddress.format(NetworkAddress.java:93)
	at org.elasticsearch.common.network.NetworkAddress.format(NetworkAddress.java:69)
	at org.elassandra.discovery.CassandraDiscovery.buildNodeName(CassandraDiscovery.java:137)
	at org.apache.cassandra.service.ElassandraDaemon.nodeSettings(ElassandraDaemon.java:453)
	at org.apache.cassandra.service.ElassandraDaemon.getSettings(ElassandraDaemon.java:436)
	at org.apache.cassandra.service.ElassandraDaemon.activate(ElassandraDaemon.java:187)
	at org.apache.cassandra.service.ElassandraDaemon.main(ElassandraDaemon.java:551)
```

**Comment by vroyer** [comment]
Hi,
It seems that your cassandra broadcast address is not defined ? (broadcast_address in your cassandra.yaml)

**Comment by andre-paris** [comment]
ok, tomorrow I'm going to validate this version again and comment here asap.
I'll open another issue for the npe.
Thanks

**Comment by andre-paris** [comment]
It's ok.
Thank you again.
