### ISSUE TITLE
Elassandra 6.2.3.1 index issue

### ISSUE THREAD

**Issue by Gappa88** [strapdata/elassandra#203]
I'm using **Elassandra 6.2.3.1.**

I have created a keyspace `mykeyspace` through CQLsh and a table `mytable` in it.
After that  I have dynamically mapped `mykeyspace` into Elasticsearch (`myindex`).
That correctly worked.

I have also created a little **nodejs** (v8.9.4) testing program that sends data to Elassandra using **cassandra-driver** [https://github.com/datastax/nodejs-driver](url) library one at a time sleeping between 0 to 2 seconds between each sends.

The problem is that I can count the right number of data sent by my testing program into CQLsh command line but I can't get the same value through elasticsearch `_search `API.

here some info:

```
GET myindex/_count
{
  "count": 38,
  "_shards": {
    "total": 3,
    "successful": 3,
    "skipped": 0,
    "failed": 0
  }
}

```

```
Connected to Test Cluster at 192.168.250.55:9042.
[cqlsh 5.0.1 | Cassandra 3.11.2 | CQL spec 3.4.4 | Native protocol v4]
Use HELP for help.
cqlsh> select count(*) from mykeyspace.mytable ;

 count
-------
   501

(1 rows)

Warnings :
Aggregation query used without partition key
```

is there any mistake I made to cause this issue?

Thank you
Marco

PS: while I'm writing this issue I'm also trying to refresh ES `_count ` but the counting remains the same so it seems not to be a refreshing interval problem.

**Comment by Gappa88** [comment]
I tried to:
- repair the keyspace
- rebuild_index
- disable and enable refresh interval

but nothing worked

**Comment by Gappa88** [comment]
ok, I think I found the problem:

```
2018-06-20 09:59:05,787 ERROR [MutationStage-3] ElasticSecondaryIndex.java:2063 index document CF=mykeyspace.mytable index/type=mykeyspace/mytable id=["175900",53829639000] version=1 created=false static=false ttl=0 refresh=false
java.lang.IllegalArgumentException: Document contains at least one immense term in field="raw" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms. 
The prefix of the first immense term is: '[60, 33, 68, 79, 67, 84, 89, 80, 69, 32, 104, 116, 109, 108, 62, 10, 60, 104, 116, 109, 108, 32, 120, 109, 108, 58, 108, 97, 110, 103]...', original message: bytes can be at most 32766 in length; got 65871
        at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:796)
        at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:430)
        at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:392)
        at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:240)
        at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:496)
        at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1729)
        at org.elasticsearch.index.engine.VersionLessInternalEngine.update(VersionLessInternalEngine.java:1168)
        at org.elasticsearch.index.engine.VersionLessInternalEngine.indexIntoLucene(VersionLessInternalEngine.java:1018)
        at org.elasticsearch.index.engine.VersionLessInternalEngine.index(VersionLessInternalEngine.java:882)
        at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:816)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$RowcumentIndexer$Rowcument.index(ElasticSecondaryIndex.java:2060)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$RowcumentIndexer$Rowcument.index(ElasticSecondaryIndex.java:1993)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$RowcumentIndexer$Rowcument.write(ElasticSecondaryIndex.java:1976)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$WideRowcumentIndexer$WideRowcument.write(ElasticSecondaryIndex.java:1374)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$WideRowcumentIndexer.commit(ElasticSecondaryIndex.java:1465)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$RowcumentIndexer.finish(ElasticSecondaryIndex.java:1685)
        at org.apache.cassandra.index.SecondaryIndexManager$WriteTimeTransaction.commit(SecondaryIndexManager.java:983)
        at org.apache.cassandra.db.partitions.AtomicBTreePartition.addAllWithSizeDelta(AtomicBTreePartition.java:181)
        at org.apache.cassandra.db.Memtable.put(Memtable.java:282)
        at org.apache.cassandra.db.ColumnFamilyStore.apply(ColumnFamilyStore.java:1342)
        at org.apache.cassandra.db.Keyspace.applyInternal(Keyspace.java:631)
        at org.apache.cassandra.db.Keyspace.apply(Keyspace.java:475)
        at org.apache.cassandra.db.Mutation.apply(Mutation.java:227)
        at org.apache.cassandra.db.Mutation.apply(Mutation.java:232)
        at org.apache.cassandra.db.Mutation.apply(Mutation.java:241)
        at org.apache.cassandra.service.StorageProxy$8.runMayThrow(StorageProxy.java:1408)
        at org.apache.cassandra.service.StorageProxy$LocalMutationRunnable.run(StorageProxy.java:2647)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:162)
        at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$LocalSessionFutureTask.run(AbstractLocalAwareExecutorService.java:134)
        at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:109)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.lucene.util.BytesRefHash$MaxBytesLengthExceededException: bytes can be at most 32766 in length; got 65871
        at org.apache.lucene.util.BytesRefHash.add(BytesRefHash.java:263)
        at org.apache.lucene.index.TermsHashPerField.add(TermsHashPerField.java:151)
        at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:786)
```

It did not happen in Elassandra 5.5.0.4 because I used the same Nodejs testing program to send data to Elassandra.

**Comment by vroyer** [comment]
Yes, you write too long text for lucene.
