### ISSUE TITLE
Indexing of UDT fails

### ISSUE THREAD

**Issue by filthz** [strapdata/elassandra#210]
This error occurs with elassandra 5.5.018 and 6.2.3.2.
I have this table structure:

    CREATE TYPE applicationinfo (
        industry text,
        area_of_application text,
        product_group text,
        sic_code text,
        conveyed_product text,
        flowability text,
        viscosity text,
        solids_content text,
        size_of_solids text,
        concentration text,
        composition text,
        specific_gravity text,
        ph_value text,
        product_temperature_min int,
        product_temperature_max int
    );
    
  
    CREATE TABLE deviceinfo (
        id text,
        "applicationinfo" applicationinfo
        PRIMARY KEY (id)
    );

In my test-case there are some (about 100 entries inserted).
When i try to create an elastic index for the deviceinfo table it fails with this exception:

    2018-07-04 14:49:56,894 ERROR [SecondaryIndexManagement:3] CassandraDaemon.java:231 uncaughtException Exception in thread Thread[SecondaryIndexManagement:3,5,main]
    java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.nio.BufferUnderflowException
    	at org.apache.cassandra.utils.Throwables.maybeFail(Throwables.java:51)
    	at org.apache.cassandra.utils.FBUtilities.waitOnFutures(FBUtilities.java:373)
    	at org.apache.cassandra.index.SecondaryIndexManager.buildIndexesBlocking(SecondaryIndexManager.java:392)
    	at org.apache.cassandra.index.SecondaryIndexManager.buildIndexesBlocking(SecondaryIndexManager.java:367)
    	at org.apache.cassandra.index.SecondaryIndexManager.buildIndexBlocking(SecondaryIndexManager.java:288)
    	at org.elassandra.index.ElasticSecondaryIndex.lambda$getInitializationTask$5(ElasticSecondaryIndex.java:2266)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    	at org.apache.cassandra.concurrent.NamedThreadFactory.lambda$threadLocalDeallocator$0(NamedThreadFactory.java:81)
    	at java.lang.Thread.run(Thread.java:748)
    Caused by: java.util.concurrent.ExecutionException: java.nio.BufferUnderflowException
    	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    	at org.apache.cassandra.utils.FBUtilities.waitOnFutures(FBUtilities.java:366)
    	... 9 common frames omitted

**Comment by vroyer** [comment]
Hi,
Could you please provide your elasticsearch cluster state please ?
Thanks.

**Comment by filthz** [comment]
Hi,

here is the output with removed ip adresses

```
{
  "cluster_name" : "Test Cluster",
  "compressed_size_in_bytes" : 915,
  "version" : 17,
  "state_uuid" : "EYMNlYIqRqWWpRZT0skkwQ",
  "master_node" : "91a2a15c-6ba3-4c65-b35b-414f1f28c651",
  "blocks" : { },
  "nodes" : {
    "4472fdcc-e9d1-4299-ad7c-138636366487" : {
      "name" : "yyy.xxx.0.237",
      "status" : "ALIVE",
      "ephemeral_id" : "4472fdcc-e9d1-4299-ad7c-138636366487",
      "transport_address" : "yyy.xxx.0.237:9300",
      "attributes" : {
        "rack" : "rack1",
        "dc" : "datacenter1"
      }
    },
    "91a2a15c-6ba3-4c65-b35b-414f1f28c651" : {
      "name" : "yyy.xxx..0.236",
      "status" : "ALIVE",
      "ephemeral_id" : "91a2a15c-6ba3-4c65-b35b-414f1f28c651",
      "transport_address" : "yyy.xxx.0.236:9300",
      "attributes" : {
        "rack" : "rack1",
        "dc" : "datacenter1"
      }
    }
  },
  "metadata" : {
    "version" : 7,
    "cluster_uuid" : "4472fdcc-e9d1-4299-ad7c-138636366487",
    "templates" : { },
    "indices" : {
      "deviceinformation" : {
        "state" : "open",
        "settings" : {
          "index" : {
            "keyspace" : "deviceinformation",
            "number_of_shards" : "2",
            "provided_name" : "deviceinformation",
            "creation_date" : "1530716379241",
            "number_of_replicas" : "0",
            "uuid" : "cdPRk1KrQ-a-nYD80h2qYA",
            "version" : {
              "created" : "6020399"
            }
          }
        },
        "mappings" : {
          "deviceinfo" : {
            "properties" : {
              "id" : {
                "cql_partition_key" : true,
                "cql_primary_key_order" : 0,
                "type" : "keyword",
                "cql_collection" : "singleton"
              },
              "applicationinfo" : {
                "cql_udt_name" : "applicationinfo",
                "type" : "nested",
                "properties" : {
                  "solids_content" : {
                    "type" : "keyword",
                    "cql_collection" : "singleton"
                  },
                  "product_temperature_min" : {
                    "type" : "integer",
                    "cql_collection" : "singleton"
                  },
                  "conveyed_product" : {
                    "type" : "keyword",
                    "cql_collection" : "singleton"
                  },
                  "concentration" : {
                    "type" : "keyword",
                    "cql_collection" : "singleton"
                  },
                  "industry" : {
                    "type" : "keyword",
                    "cql_collection" : "singleton"
                  },
                  "specific_gravity" : {
                    "type" : "keyword",
                    "cql_collection" : "singleton"
                  },
                  "area_of_application" : {
                    "type" : "keyword",
                    "cql_collection" : "singleton"
                  },
                  "sic_code" : {
                    "type" : "keyword",
                    "cql_collection" : "singleton"
                  },
                  "size_of_solids" : {
                    "type" : "keyword",
                    "cql_collection" : "singleton"
                  },
                  "viscosity" : {
                    "type" : "keyword",
                    "cql_collection" : "singleton"
                  },
                  "composition" : {
                    "type" : "keyword",
                    "cql_collection" : "singleton"
                  },
                  "product_temperature_max" : {
                    "type" : "integer",
                    "cql_collection" : "singleton"
                  },
                  "flowability" : {
                    "type" : "keyword",
                    "cql_collection" : "singleton"
                  },
                  "product_group" : {
                    "type" : "keyword",
                    "cql_collection" : "singleton"
                  },
                  "ph_value" : {
                    "type" : "keyword",
                    "cql_collection" : "singleton"
                  }
                },
                "cql_collection" : "singleton"
              }
            }
          }
        },
        "aliases" : [ ],
        "primary_terms" : {
          "0" : 0,
          "1" : 0
        },
        "in_sync_allocations" : {
          "1" : [ ],
          "0" : [ ]
        }
      }
    },
    "index-graveyard" : {
      "tombstones" : [
        {
          "index" : {
            "index_name" : "deviceinformation",
            "index_uuid" : "hrENWB1dR7KvepbE9gQMGQ"
          },
          "delete_date_in_millis" : 1530715806399
        },
        {
          "index" : {
            "index_name" : "deviceinformation",
            "index_uuid" : "LjlQCKkIRD-qp0TTkC5gnQ"
          },
          "delete_date_in_millis" : 1530716228066
        },
        {
          "index" : {
            "index_name" : "deviceinformation",
            "index_uuid" : "isq7786aRTKPQHwDEIEVpQ"
          },
          "delete_date_in_millis" : 1530716375150
        }
      ]
    }
  },
  "routing_table" : {
    "indices" : {
      "deviceinformation" : {
        "shards" : {
          "1" : [
            {
              "state" : "STARTED",
              "primary" : true,
              "node" : "4472fdcc-e9d1-4299-ad7c-138636366487",
              "relocating_node" : null,
              "shard" : 1,
              "index" : "deviceinformation",
              "token_ranges" : [
                "(-9223372036854775808,-9164353838376425554]",
                "(-9106551174901557685,-9103153699858118199]",
                "(-9036104188015768274,-9017725390315715179]",
                "(-8898333255722981642,-8840388298730943838]",
                "(-8810390561744331052,-8807077322687872574]",
                "(-8735005334836629189,-8688729791521870688]",
                "(-8657956642456327543,-8569563980116564546]",
                "(-8374430193393068604,-8341401387045829933]",
                "(-8283719576096653190,-8250346348992411207]",
                "(-8029502698789545562,-7932553828891942577]",
                "(-7901903036291244750,-7852088155768629745]",
                "(-7635484885438594702,-7546573226739893431]",
                "(-7535240817137976761,-7496372760180373801]",
                "(-7350453190900917391,-6816383833573334078]",
                "(-6813137813811619847,-6701504700376069397]",
                "(-6625100874597137717,-6537805600841224010]",
                "(-6459533953357754722,-6418022770814367899]",
                "(-6312620919268356712,-6292658931228913246]",
                "(-6291226423389121821,-6220220377109654188]",
                "(-6191432778427784315,-6144145365672334226]",
                "(-6057929528365040330,-6047365514334479026]",
                "(-5999908853771796768,-5937812924448644951]",
                "(-5859532039450068975,-5564048899690119419]",
                "(-5462376947816916149,-5435977600376954064]",
                "(-5315881981855611262,-5093381377444133171]",
                "(-5049614583622821777,-4916326474609619769]",
                "(-4900975584252738493,-4794171234479961343]",
                "(-4786788241633820910,-4766066507111873342]",
                "(-4727297991030089161,-4687441608752233529]",
                "(-4636410709128648804,-4636024268500236901]",
                "(-4597958184068438518,-4592724975269469306]",
                "(-4496335142423784277,-4479964776206982368]",
                "(-4438798970881176100,-4418560127960777085]",
                "(-4158724760878189254,-3951527215250716575]",
                "(-3663716683733521411,-3455591873895020462]",
                "(-3355889544854873202,-3307182510437582444]",
                "(-3149816137610221510,-3033365992808011512]",
                "(-2961017080443621753,-2719069192474545984]",
                "(-2715385529786628770,-2660070842223008999]",
                "(-2635411549055383595,-2635055016812101461]",
                "(-2424686829894171514,-2419297982435764584]",
                "(-2313264745966906791,-2176954329996725039]",
                "(-2082949269855597344,-2009156013488102164]",
                "(-2001442911261339098,-1956081754520617085]",
                "(-1841688444054726051,-1825902791079866385]",
                "(-1813462801862313988,-1783043064210529760]",
                "(-1752066529618429043,-1674274239049656206]",
                "(-1645860391712173771,-1631425686755749133]",
                "(-1630185002200958621,-1621183048389212300]",
                "(-1614210584960001657,-1598861813651484117]",
                "(-1513118180405195159,-1476309827511869700]",
                "(-1384349709327707295,-1283172825456794957]",
                "(-1215056172499297581,-1195662280845453702]",
                "(-1164569284806206010,-1004832336757912597]",
                "(-894746349885778819,-865073167362581113]",
                "(-773563654095076813,-719299601264024440]",
                "(-666319136840219234,-593265143278258201]",
                "(-509759909749276682,-453800382187121006]",
                "(-450253876957688018,-333967672954446042]",
                "(-274452790062921167,-146152296205016810]",
                "(2128525409780262,19736905924581411]",
                "(84784533174142561,127024227475909621]",
                "(127371802123798758,146725547219150230]",
                "(232894355420349903,440604899158620500]",
                "(474916280448521802,569753279619577301]",
                "(702236396849074623,705247780278377924]",
                "(776609031486294225,784167935852888678]",
                "(971211946466419657,1050808230381045960]",
                "(1063673710779298414,1160306043356361489]",
                "(1175780038688345532,1223583517026936309]",
                "(1283832247127890769,1309911137903640429]",
                "(1359610321989852180,1394513532835644713]",
                "(1428366478218119690,1444773471109267211]",
                "(1488918663691071629,1492924870666132756]",
                "(1512995042934941520,1580956878686055406]",
                "(1654386597698570122,1675113364915891413]",
                "(1690552807457656208,1700668112298316708]",
                "(1716121228269282544,1764523796767756092]",
                "(1812375068482516431,2022768812149779733]",
                "(2189687221221038069,2323848878247353576]",
                "(2379089087194371586,2387262020310996956]",
                "(2490129695524396687,2640396608644689090]",
                "(2721526124263893911,2770299601034385487]",
                "(2774666776528219588,2873464461859794577]",
                "(2915703741561741617,2960469701835753234]",
                "(3051925523465040266,3317231233673914967]",
                "(3518201612184795199,3591066282286780442]",
                "(3597956034273696860,3773380328940827276]",
                "(3961719897806899256,3987055430208259400]",
                "(4201809908940411646,4335300016806175266]",
                "(4423609841574119375,4492722217752686779]",
                "(4693458664339633395,4722923765030384429]",
                "(4741151442726843986,4770579386463622601]",
                "(4845904627921651496,5042208577670385759]",
                "(5056825088816569557,5164769736377317937]",
                "(5167473828378897056,5323022560625612105]",
                "(5340012308572640319,5523826265194232453]",
                "(5679967245094490109,5714828991145508874]",
                "(5893464889730792867,6163234557222717848]",
                "(6164440549128700992,6185239259064952527]",
                "(6269127386565762582,6295152078944667523]",
                "(6461158737250409094,6479940884100451487]",
                "(6514062502449828619,6581398819105918889]",
                "(6667764326145021474,6835991130850053580]",
                "(6847129000879497357,7096291091725719323]",
                "(7171640579491358547,7276858326092471133]",
                "(7292891236423767496,7350337137659706760]",
                "(7485125413961215086,7613146867538464998]",
                "(7668566492335498424,7680991030209305734]",
                "(7689553775629322708,7732302788026585529]",
                "(7831433433717513000,7862438639597742728]",
                "(7943089971046868348,7966752885227412497]",
                "(7988866191476643466,8143035352388518664]",
                "(8163242131847407771,8237696592381288109]",
                "(8278745704453600754,8331230236349070660]",
                "(8339090688797402550,8402352151546561341]",
                "(8576961210794784200,8589603289824117748]",
                "(8591076064986983476,8599010261620213391]",
                "(8599813379872286461,8716524020007853872]",
                "(8765225722325670079,8843612061926712813]",
                "(8857529171033788593,8871744222436385914]",
                "(8899566201654098805,8940322425935306673]",
                "(9024570482854470157,9076965797400073281]",
                "(9089857433759062935,9223372036854775807]"
              ],
              "allocation_id" : {
                "id" : "dummy_alloc_id"
              }
            }
          ],
          "0" : [
            {
              "state" : "STARTED",
              "primary" : true,
              "node" : "91a2a15c-6ba3-4c65-b35b-414f1f28c651",
              "relocating_node" : null,
              "shard" : 0,
              "index" : "deviceinformation",
              "token_ranges" : [
                "(-9164353838376425554,-9106551174901557685]",
                "(-9103153699858118199,-9036104188015768274]",
                "(-9017725390315715179,-8898333255722981642]",
                "(-8840388298730943838,-8810390561744331052]",
                "(-8807077322687872574,-8735005334836629189]",
                "(-8688729791521870688,-8657956642456327543]",
                "(-8569563980116564546,-8374430193393068604]",
                "(-8341401387045829933,-8283719576096653190]",
                "(-8250346348992411207,-8029502698789545562]",
                "(-7932553828891942577,-7901903036291244750]",
                "(-7852088155768629745,-7635484885438594702]",
                "(-7546573226739893431,-7535240817137976761]",
                "(-7496372760180373801,-7350453190900917391]",
                "(-6816383833573334078,-6813137813811619847]",
                "(-6701504700376069397,-6625100874597137717]",
                "(-6537805600841224010,-6459533953357754722]",
                "(-6418022770814367899,-6312620919268356712]",
                "(-6292658931228913246,-6291226423389121821]",
                "(-6220220377109654188,-6191432778427784315]",
                "(-6144145365672334226,-6057929528365040330]",
                "(-6047365514334479026,-5999908853771796768]",
                "(-5937812924448644951,-5859532039450068975]",
                "(-5564048899690119419,-5462376947816916149]",
                "(-5435977600376954064,-5315881981855611262]",
                "(-5093381377444133171,-5049614583622821777]",
                "(-4916326474609619769,-4900975584252738493]",
                "(-4794171234479961343,-4786788241633820910]",
                "(-4766066507111873342,-4727297991030089161]",
                "(-4687441608752233529,-4636410709128648804]",
                "(-4636024268500236901,-4597958184068438518]",
                "(-4592724975269469306,-4496335142423784277]",
                "(-4479964776206982368,-4438798970881176100]",
                "(-4418560127960777085,-4158724760878189254]",
                "(-3951527215250716575,-3663716683733521411]",
                "(-3455591873895020462,-3355889544854873202]",
                "(-3307182510437582444,-3149816137610221510]",
                "(-3033365992808011512,-2961017080443621753]",
                "(-2719069192474545984,-2715385529786628770]",
                "(-2660070842223008999,-2635411549055383595]",
                "(-2635055016812101461,-2424686829894171514]",
                "(-2419297982435764584,-2313264745966906791]",
                "(-2176954329996725039,-2082949269855597344]",
                "(-2009156013488102164,-2001442911261339098]",
                "(-1956081754520617085,-1841688444054726051]",
                "(-1825902791079866385,-1813462801862313988]",
                "(-1783043064210529760,-1752066529618429043]",
                "(-1674274239049656206,-1645860391712173771]",
                "(-1631425686755749133,-1630185002200958621]",
                "(-1621183048389212300,-1614210584960001657]",
                "(-1598861813651484117,-1513118180405195159]",
                "(-1476309827511869700,-1384349709327707295]",
                "(-1283172825456794957,-1215056172499297581]",
                "(-1195662280845453702,-1164569284806206010]",
                "(-1004832336757912597,-894746349885778819]",
                "(-865073167362581113,-773563654095076813]",
                "(-719299601264024440,-666319136840219234]",
                "(-593265143278258201,-509759909749276682]",
                "(-453800382187121006,-450253876957688018]",
                "(-333967672954446042,-274452790062921167]",
                "(-146152296205016810,2128525409780262]",
                "(19736905924581411,84784533174142561]",
                "(127024227475909621,127371802123798758]",
                "(146725547219150230,232894355420349903]",
                "(440604899158620500,474916280448521802]",
                "(569753279619577301,702236396849074623]",
                "(705247780278377924,776609031486294225]",
                "(784167935852888678,971211946466419657]",
                "(1050808230381045960,1063673710779298414]",
                "(1160306043356361489,1175780038688345532]",
                "(1223583517026936309,1283832247127890769]",
                "(1309911137903640429,1359610321989852180]",
                "(1394513532835644713,1428366478218119690]",
                "(1444773471109267211,1488918663691071629]",
                "(1492924870666132756,1512995042934941520]",
                "(1580956878686055406,1654386597698570122]",
                "(1675113364915891413,1690552807457656208]",
                "(1700668112298316708,1716121228269282544]",
                "(1764523796767756092,1812375068482516431]",
                "(2022768812149779733,2189687221221038069]",
                "(2323848878247353576,2379089087194371586]",
                "(2387262020310996956,2490129695524396687]",
                "(2640396608644689090,2721526124263893911]",
                "(2770299601034385487,2774666776528219588]",
                "(2873464461859794577,2915703741561741617]",
                "(2960469701835753234,3051925523465040266]",
                "(3317231233673914967,3518201612184795199]",
                "(3591066282286780442,3597956034273696860]",
                "(3773380328940827276,3961719897806899256]",
                "(3987055430208259400,4201809908940411646]",
                "(4335300016806175266,4423609841574119375]",
                "(4492722217752686779,4693458664339633395]",
                "(4722923765030384429,4741151442726843986]",
                "(4770579386463622601,4845904627921651496]",
                "(5042208577670385759,5056825088816569557]",
                "(5164769736377317937,5167473828378897056]",
                "(5323022560625612105,5340012308572640319]",
                "(5523826265194232453,5679967245094490109]",
                "(5714828991145508874,5893464889730792867]",
                "(6163234557222717848,6164440549128700992]",
                "(6185239259064952527,6269127386565762582]",
                "(6295152078944667523,6461158737250409094]",
                "(6479940884100451487,6514062502449828619]",
                "(6581398819105918889,6667764326145021474]",
                "(6835991130850053580,6847129000879497357]",
                "(7096291091725719323,7171640579491358547]",
                "(7276858326092471133,7292891236423767496]",
                "(7350337137659706760,7485125413961215086]",
                "(7613146867538464998,7668566492335498424]",
                "(7680991030209305734,7689553775629322708]",
                "(7732302788026585529,7831433433717513000]",
                "(7862438639597742728,7943089971046868348]",
                "(7966752885227412497,7988866191476643466]",
                "(8143035352388518664,8163242131847407771]",
                "(8237696592381288109,8278745704453600754]",
                "(8331230236349070660,8339090688797402550]",
                "(8402352151546561341,8576961210794784200]",
                "(8589603289824117748,8591076064986983476]",
                "(8599010261620213391,8599813379872286461]",
                "(8716524020007853872,8765225722325670079]",
                "(8843612061926712813,8857529171033788593]",
                "(8871744222436385914,8899566201654098805]",
                "(8940322425935306673,9024570482854470157]",
                "(9076965797400073281,9089857433759062935]"
              ],
              "allocation_id" : {
                "id" : "dummy_alloc_id"
              }
            }
          ]
        }
      }
    }
  },
  "routing_nodes" : {
    "unassigned" : [ ],
    "nodes" : {
      "4472fdcc-e9d1-4299-ad7c-138636366487" : [
        {
          "state" : "STARTED",
          "primary" : true,
          "node" : "4472fdcc-e9d1-4299-ad7c-138636366487",
          "relocating_node" : null,
          "shard" : 1,
          "index" : "deviceinformation",
          "token_ranges" : [
            "(-9223372036854775808,-9164353838376425554]",
            "(-9106551174901557685,-9103153699858118199]",
            "(-9036104188015768274,-9017725390315715179]",
            "(-8898333255722981642,-8840388298730943838]",
            "(-8810390561744331052,-8807077322687872574]",
            "(-8735005334836629189,-8688729791521870688]",
            "(-8657956642456327543,-8569563980116564546]",
            "(-8374430193393068604,-8341401387045829933]",
            "(-8283719576096653190,-8250346348992411207]",
            "(-8029502698789545562,-7932553828891942577]",
            "(-7901903036291244750,-7852088155768629745]",
            "(-7635484885438594702,-7546573226739893431]",
            "(-7535240817137976761,-7496372760180373801]",
            "(-7350453190900917391,-6816383833573334078]",
            "(-6813137813811619847,-6701504700376069397]",
            "(-6625100874597137717,-6537805600841224010]",
            "(-6459533953357754722,-6418022770814367899]",
            "(-6312620919268356712,-6292658931228913246]",
            "(-6291226423389121821,-6220220377109654188]",
            "(-6191432778427784315,-6144145365672334226]",
            "(-6057929528365040330,-6047365514334479026]",
            "(-5999908853771796768,-5937812924448644951]",
            "(-5859532039450068975,-5564048899690119419]",
            "(-5462376947816916149,-5435977600376954064]",
            "(-5315881981855611262,-5093381377444133171]",
            "(-5049614583622821777,-4916326474609619769]",
            "(-4900975584252738493,-4794171234479961343]",
            "(-4786788241633820910,-4766066507111873342]",
            "(-4727297991030089161,-4687441608752233529]",
            "(-4636410709128648804,-4636024268500236901]",
            "(-4597958184068438518,-4592724975269469306]",
            "(-4496335142423784277,-4479964776206982368]",
            "(-4438798970881176100,-4418560127960777085]",
            "(-4158724760878189254,-3951527215250716575]",
            "(-3663716683733521411,-3455591873895020462]",
            "(-3355889544854873202,-3307182510437582444]",
            "(-3149816137610221510,-3033365992808011512]",
            "(-2961017080443621753,-2719069192474545984]",
            "(-2715385529786628770,-2660070842223008999]",
            "(-2635411549055383595,-2635055016812101461]",
            "(-2424686829894171514,-2419297982435764584]",
            "(-2313264745966906791,-2176954329996725039]",
            "(-2082949269855597344,-2009156013488102164]",
            "(-2001442911261339098,-1956081754520617085]",
            "(-1841688444054726051,-1825902791079866385]",
            "(-1813462801862313988,-1783043064210529760]",
            "(-1752066529618429043,-1674274239049656206]",
            "(-1645860391712173771,-1631425686755749133]",
            "(-1630185002200958621,-1621183048389212300]",
            "(-1614210584960001657,-1598861813651484117]",
            "(-1513118180405195159,-1476309827511869700]",
            "(-1384349709327707295,-1283172825456794957]",
            "(-1215056172499297581,-1195662280845453702]",
            "(-1164569284806206010,-1004832336757912597]",
            "(-894746349885778819,-865073167362581113]",
            "(-773563654095076813,-719299601264024440]",
            "(-666319136840219234,-593265143278258201]",
            "(-509759909749276682,-453800382187121006]",
            "(-450253876957688018,-333967672954446042]",
            "(-274452790062921167,-146152296205016810]",
            "(2128525409780262,19736905924581411]",
            "(84784533174142561,127024227475909621]",
            "(127371802123798758,146725547219150230]",
            "(232894355420349903,440604899158620500]",
            "(474916280448521802,569753279619577301]",
            "(702236396849074623,705247780278377924]",
            "(776609031486294225,784167935852888678]",
            "(971211946466419657,1050808230381045960]",
            "(1063673710779298414,1160306043356361489]",
            "(1175780038688345532,1223583517026936309]",
            "(1283832247127890769,1309911137903640429]",
            "(1359610321989852180,1394513532835644713]",
            "(1428366478218119690,1444773471109267211]",
            "(1488918663691071629,1492924870666132756]",
            "(1512995042934941520,1580956878686055406]",
            "(1654386597698570122,1675113364915891413]",
            "(1690552807457656208,1700668112298316708]",
            "(1716121228269282544,1764523796767756092]",
            "(1812375068482516431,2022768812149779733]",
            "(2189687221221038069,2323848878247353576]",
            "(2379089087194371586,2387262020310996956]",
            "(2490129695524396687,2640396608644689090]",
            "(2721526124263893911,2770299601034385487]",
            "(2774666776528219588,2873464461859794577]",
            "(2915703741561741617,2960469701835753234]",
            "(3051925523465040266,3317231233673914967]",
            "(3518201612184795199,3591066282286780442]",
            "(3597956034273696860,3773380328940827276]",
            "(3961719897806899256,3987055430208259400]",
            "(4201809908940411646,4335300016806175266]",
            "(4423609841574119375,4492722217752686779]",
            "(4693458664339633395,4722923765030384429]",
            "(4741151442726843986,4770579386463622601]",
            "(4845904627921651496,5042208577670385759]",
            "(5056825088816569557,5164769736377317937]",
            "(5167473828378897056,5323022560625612105]",
            "(5340012308572640319,5523826265194232453]",
            "(5679967245094490109,5714828991145508874]",
            "(5893464889730792867,6163234557222717848]",
            "(6164440549128700992,6185239259064952527]",
            "(6269127386565762582,6295152078944667523]",
            "(6461158737250409094,6479940884100451487]",
            "(6514062502449828619,6581398819105918889]",
            "(6667764326145021474,6835991130850053580]",
            "(6847129000879497357,7096291091725719323]",
            "(7171640579491358547,7276858326092471133]",
            "(7292891236423767496,7350337137659706760]",
            "(7485125413961215086,7613146867538464998]",
            "(7668566492335498424,7680991030209305734]",
            "(7689553775629322708,7732302788026585529]",
            "(7831433433717513000,7862438639597742728]",
            "(7943089971046868348,7966752885227412497]",
            "(7988866191476643466,8143035352388518664]",
            "(8163242131847407771,8237696592381288109]",
            "(8278745704453600754,8331230236349070660]",
            "(8339090688797402550,8402352151546561341]",
            "(8576961210794784200,8589603289824117748]",
            "(8591076064986983476,8599010261620213391]",
            "(8599813379872286461,8716524020007853872]",
            "(8765225722325670079,8843612061926712813]",
            "(8857529171033788593,8871744222436385914]",
            "(8899566201654098805,8940322425935306673]",
            "(9024570482854470157,9076965797400073281]",
            "(9089857433759062935,9223372036854775807]"
          ],
          "allocation_id" : {
            "id" : "dummy_alloc_id"
          }
        }
      ],
      "91a2a15c-6ba3-4c65-b35b-414f1f28c651" : [
        {
          "state" : "STARTED",
          "primary" : true,
          "node" : "91a2a15c-6ba3-4c65-b35b-414f1f28c651",
          "relocating_node" : null,
          "shard" : 0,
          "index" : "deviceinformation",
          "token_ranges" : [
            "(-9164353838376425554,-9106551174901557685]",
            "(-9103153699858118199,-9036104188015768274]",
            "(-9017725390315715179,-8898333255722981642]",
            "(-8840388298730943838,-8810390561744331052]",
            "(-8807077322687872574,-8735005334836629189]",
            "(-8688729791521870688,-8657956642456327543]",
            "(-8569563980116564546,-8374430193393068604]",
            "(-8341401387045829933,-8283719576096653190]",
            "(-8250346348992411207,-8029502698789545562]",
            "(-7932553828891942577,-7901903036291244750]",
            "(-7852088155768629745,-7635484885438594702]",
            "(-7546573226739893431,-7535240817137976761]",
            "(-7496372760180373801,-7350453190900917391]",
            "(-6816383833573334078,-6813137813811619847]",
            "(-6701504700376069397,-6625100874597137717]",
            "(-6537805600841224010,-6459533953357754722]",
            "(-6418022770814367899,-6312620919268356712]",
            "(-6292658931228913246,-6291226423389121821]",
            "(-6220220377109654188,-6191432778427784315]",
            "(-6144145365672334226,-6057929528365040330]",
            "(-6047365514334479026,-5999908853771796768]",
            "(-5937812924448644951,-5859532039450068975]",
            "(-5564048899690119419,-5462376947816916149]",
            "(-5435977600376954064,-5315881981855611262]",
            "(-5093381377444133171,-5049614583622821777]",
            "(-4916326474609619769,-4900975584252738493]",
            "(-4794171234479961343,-4786788241633820910]",
            "(-4766066507111873342,-4727297991030089161]",
            "(-4687441608752233529,-4636410709128648804]",
            "(-4636024268500236901,-4597958184068438518]",
            "(-4592724975269469306,-4496335142423784277]",
            "(-4479964776206982368,-4438798970881176100]",
            "(-4418560127960777085,-4158724760878189254]",
            "(-3951527215250716575,-3663716683733521411]",
            "(-3455591873895020462,-3355889544854873202]",
            "(-3307182510437582444,-3149816137610221510]",
            "(-3033365992808011512,-2961017080443621753]",
            "(-2719069192474545984,-2715385529786628770]",
            "(-2660070842223008999,-2635411549055383595]",
            "(-2635055016812101461,-2424686829894171514]",
            "(-2419297982435764584,-2313264745966906791]",
            "(-2176954329996725039,-2082949269855597344]",
            "(-2009156013488102164,-2001442911261339098]",
            "(-1956081754520617085,-1841688444054726051]",
            "(-1825902791079866385,-1813462801862313988]",
            "(-1783043064210529760,-1752066529618429043]",
            "(-1674274239049656206,-1645860391712173771]",
            "(-1631425686755749133,-1630185002200958621]",
            "(-1621183048389212300,-1614210584960001657]",
            "(-1598861813651484117,-1513118180405195159]",
            "(-1476309827511869700,-1384349709327707295]",
            "(-1283172825456794957,-1215056172499297581]",
            "(-1195662280845453702,-1164569284806206010]",
            "(-1004832336757912597,-894746349885778819]",
            "(-865073167362581113,-773563654095076813]",
            "(-719299601264024440,-666319136840219234]",
            "(-593265143278258201,-509759909749276682]",
            "(-453800382187121006,-450253876957688018]",
            "(-333967672954446042,-274452790062921167]",
            "(-146152296205016810,2128525409780262]",
            "(19736905924581411,84784533174142561]",
            "(127024227475909621,127371802123798758]",
            "(146725547219150230,232894355420349903]",
            "(440604899158620500,474916280448521802]",
            "(569753279619577301,702236396849074623]",
            "(705247780278377924,776609031486294225]",
            "(784167935852888678,971211946466419657]",
            "(1050808230381045960,1063673710779298414]",
            "(1160306043356361489,1175780038688345532]",
            "(1223583517026936309,1283832247127890769]",
            "(1309911137903640429,1359610321989852180]",
            "(1394513532835644713,1428366478218119690]",
            "(1444773471109267211,1488918663691071629]",
            "(1492924870666132756,1512995042934941520]",
            "(1580956878686055406,1654386597698570122]",
            "(1675113364915891413,1690552807457656208]",
            "(1700668112298316708,1716121228269282544]",
            "(1764523796767756092,1812375068482516431]",
            "(2022768812149779733,2189687221221038069]",
            "(2323848878247353576,2379089087194371586]",
            "(2387262020310996956,2490129695524396687]",
            "(2640396608644689090,2721526124263893911]",
            "(2770299601034385487,2774666776528219588]",
            "(2873464461859794577,2915703741561741617]",
            "(2960469701835753234,3051925523465040266]",
            "(3317231233673914967,3518201612184795199]",
            "(3591066282286780442,3597956034273696860]",
            "(3773380328940827276,3961719897806899256]",
            "(3987055430208259400,4201809908940411646]",
            "(4335300016806175266,4423609841574119375]",
            "(4492722217752686779,4693458664339633395]",
            "(4722923765030384429,4741151442726843986]",
            "(4770579386463622601,4845904627921651496]",
            "(5042208577670385759,5056825088816569557]",
            "(5164769736377317937,5167473828378897056]",
            "(5323022560625612105,5340012308572640319]",
            "(5523826265194232453,5679967245094490109]",
            "(5714828991145508874,5893464889730792867]",
            "(6163234557222717848,6164440549128700992]",
            "(6185239259064952527,6269127386565762582]",
            "(6295152078944667523,6461158737250409094]",
            "(6479940884100451487,6514062502449828619]",
            "(6581398819105918889,6667764326145021474]",
            "(6835991130850053580,6847129000879497357]",
            "(7096291091725719323,7171640579491358547]",
            "(7276858326092471133,7292891236423767496]",
            "(7350337137659706760,7485125413961215086]",
            "(7613146867538464998,7668566492335498424]",
            "(7680991030209305734,7689553775629322708]",
            "(7732302788026585529,7831433433717513000]",
            "(7862438639597742728,7943089971046868348]",
            "(7966752885227412497,7988866191476643466]",
            "(8143035352388518664,8163242131847407771]",
            "(8237696592381288109,8278745704453600754]",
            "(8331230236349070660,8339090688797402550]",
            "(8402352151546561341,8576961210794784200]",
            "(8589603289824117748,8591076064986983476]",
            "(8599010261620213391,8599813379872286461]",
            "(8716524020007853872,8765225722325670079]",
            "(8843612061926712813,8857529171033788593]",
            "(8871744222436385914,8899566201654098805]",
            "(8940322425935306673,9024570482854470157]",
            "(9076965797400073281,9089857433759062935]"
          ],
          "allocation_id" : {
            "id" : "dummy_alloc_id"
          }
        }
      ]
    }
  },
  "snapshots" : {
    "snapshots" : [ ]
  },
  "restore" : {
    "snapshots" : [ ]
  },
  "snapshot_deletions" : {
    "snapshot_deletions" : [ ]
  }
}
```

**Comment by vroyer** [comment]
You should frozen your UDT by creating your table like this :

CREATE TABLE deviceinfo ( id text, "applicationinfo" frozen<applicationinfo>, PRIMARY KEY (id) );

Then, re-create your index.
Thanks.

**Comment by filthz** [comment]
This worked, thanks a lot.
Why do the UDTs have to be frozen?

It would be useful to show a more comprehensive error, I think :)

**Comment by vroyer** [comment]
Cassandra serializes a frozen value having multiple components into a single value, so elassandra can properly decode a frozen UDT and map each component to a sub-field. We will add check when discovering the schema.

**Comment by vroyer** [comment]
Fixed.
