### ISSUE TITLE
partitioned-index solution can not work well on index mapping with nested field

### ISSUE THREAD

**Issue by zallan114** [strapdata/elassandra#233]
**Elasticsearch version**:
docker.io/strapdata/elassandra   5.5.0.10

**Plugins installed**: []
no

**JVM version** (`java -version`):
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-1~bpo8+1-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Red Hat Enterprise Linux Server release 7.5 (Maipo)

**Description of the problem including expected versus actual behavior**:

PUT /kpi_data_20180922
{
  "settings": {
      "keyspace":"kpi_data",
      "index.partition_function":"toDayIndex kpi_data_{0,date,yyyyMMdd} transtime",
      "index.partition_function_class":"org.elassandra.index.MessageFormatPartitionFunction"
  },
  "mappings": {
      "raw_kpi_data" : { "discover" : ".*" }
  }
}

this index should fetch all data of the date specified, but actually it reports many exceptions and only few records collected in this index when using  kpi_data_20180922/_search.

2018-11-01 06:01:05,641 ERROR [CompactionExecutor:18793] org.elassandra.index.ElasticSecondaryIndex$Context.addField(ElasticSecondaryIndex.java:499) error while updating mapping
org.elasticsearch.ElasticsearchTimeoutException: blocking update timeout
	at org.elasticsearch.cluster.service.ClusterService$BlockingActionListener.waitForUpdate(ClusterService.java:2238)
	at org.elasticsearch.cluster.service.ClusterService.blockingMappingUpdate(ClusterService.java:2276)
	at org.elassandra.index.ElasticSecondaryIndex$Context.addField(ElasticSecondaryIndex.java:492)
	at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$RowcumentIndexer$Rowcument.buildContext(ElasticSecondaryIndex.java:1819)
	at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$WideRowcumentIndexer$WideRowcument.buildContext(ElasticSecondaryIndex.java:1295)
	at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$RowcumentIndexer$Rowcument.index(ElasticSecondaryIndex.java:1893)
	at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$RowcumentIndexer$Rowcument.index(ElasticSecondaryIndex.java:1881)
	at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$WideRowcumentIndexer$WideRowcument.index(ElasticSecondaryIndex.java:1295)
	at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$WideRowcumentIndexer.flush(ElasticSecondaryIndex.java:1378)
	at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$RowcumentIndexer.finish(ElasticSecondaryIndex.java:1598)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.apache.cassandra.index.SecondaryIndexManager.indexPartition(SecondaryIndexManager.java:642)
	at org.apache.cassandra.index.internal.CollatedViewIndexBuilder.build(CollatedViewIndexBuilder.java:139)
	at org.apache.cassandra.db.compaction.CompactionManager$14.run(CompactionManager.java:1605)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.cassandra.concurrent.NamedThreadFactory.lambda$threadLocalDeallocator$0(NamedThreadFactory.java:81)
	at java.lang.Thread.run(Thread.java:748)
2018-11-01 06:01:05,642 ERROR [CompactionExecutor:18793] org.elassandra.index.ElasticSecondaryIndex$Context.addField(ElasticSecondaryIndex.java:515) submapper not found for nested field [TERM_CALL_ATT]
2018-11-01 06:01:05,642 INFO  [CompactionExecutor:18793] org.elassandra.index.ElasticSecondaryIndex$Context.addField(ElasticSecondaryIndex.java:490) updating mapping={"raw_kpi_data":{"properties":{"counters":{"type":"nested","cql_struct":"map","cql_collection":"singleton","properties":{"TERM_CALL_DROP":{"type":"integer"}}}}}}

**Steps to reproduce**:

1. create elassandra table

CREATE TABLE kpi_data.raw_kpi_data (
    ...
    transtime timestamp,
    ...
    counters map<text, int>,
    ....
    PRIMARY KEY (....)
) ....

2. create mapping 
PUT /kpi_data_20180922
{
  "settings": {
      "keyspace":"kpi_data",
      "index.partition_function":"toDayIndex kpi_data_{0,date,yyyyMMdd} transtime",
      "index.partition_function_class":"org.elassandra.index.MessageFormatPartitionFunction"
  },
  "mappings": {
      "raw_kpi_data" : { "discover" : ".*" }
  }
}

3. reporting exeptions and only few records found in the newly-created index.....

GET kpi_data_20180922/_search

**Comment by vroyer** [comment]
Hi,

Your mapping request timeout because your cluster does not respond for some reasons.
It can be due to lack of ressources, network issues, unavailable nodes to reach a QUORUM...
Please provide the result of node goosipinfo to check that X2 is the same on all nodes.

**Comment by zallan114** [comment]
#nodetool status
Datacenter: DC1
===============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address      Load       Tokens       Owns    Host ID                               Rack
UN  10.xx.xx.129  239.09 MiB  8            ?       63152562-cc70-4b28-a74b-349f71af2a75  r1
UN  10.xx.xx.100  126.62 MiB  8            ?       4340ebc5-cec3-4756-ae77-315ba735315e  r1
UN  10.xx.xx.136  123.23 MiB  8            ?       27fb73df-dffa-485a-8be4-bf1ba480d094  r1


even when I execute to create the mapping, it returns true, but still reporting: 

2018-11-01 10:03:01,095 WARN  [elasticsearch[10.xx.xx.129][clusterService#updateTask][T#1]] org.elasticsearch.cluster.service.ClusterService.lambda$publishAndApplyChanges$3(ClusterService.java:1600) failed to notify ClusterStateListener
java.lang.NullPointerException: null
	at org.elasticsearch.cluster.service.ClusterService$6.clusterChanged(ClusterService.java:1504)
	at org.elasticsearch.cluster.service.ClusterService.lambda$publishAndApplyChanges$3(ClusterService.java:1598)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at org.elasticsearch.cluster.service.ClusterService.publishAndApplyChanges(ClusterService.java:1595)
	at org.elasticsearch.cluster.service.BaseClusterService.runTasks(BaseClusterService.java:583)
	at org.elasticsearch.cluster.service.BaseClusterService$ClusterServiceTaskBatcher.run(BaseClusterService.java:263)
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
	at org.elasticsearch.cluster.service.BaseClusterService$ClusterServiceTaskBatcher$UpdateTask.run(BaseClusterService.java:266)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:247)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:210)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

**Comment by vroyer** [comment]
Please update to 5.5.0.24, and provide full cluster information including the cluster state and nodetool **gossipinfo**.
Thanks in advance.

**Comment by zallan114** [comment]
# nodetool gossipinfo
/10.xx.xx.129
  generation:1541065414
  heartbeat:56319
  STATUS:16:NORMAL,-3703150110047363296
  LOAD:56296:2.50765825E8
  SCHEMA:2941:3b06c1af-6527-3848-be90-eaa85163323d
  DC:8:DC1
  RACK:10:r1
  RELEASE_VERSION:4:3.11.1.2
  INTERNAL_IP:6:10.xx.xx.129
  RPC_ADDRESS:3:10.xx.xx.129
  NET_VERSION:1:11
  HOST_ID:2:63152562-cc70-4b28-a74b-349f71af2a75
  RPC_READY:44:true
  X1:2123:{"logs-000001":3,"logs-2018.10.23-000002":3,"logs-2018.10.23-000003":3,"dbt":3,".kibana":3,"dbt_2_0_ubt_trl_data":3,"kpi_data":3,"kpi_data_20180922":3,"logs-2018.10.23-1":3,"kpi_data_20180925":3}
  X2:2932:27fb73df-dffa-485a-8be4-bf1ba480d094/2004
  TOKENS:15:<hidden>
/10.xx.xx.100
  generation:1541065353
  heartbeat:56400
  STATUS:16:NORMAL,-5273837635697480681
  LOAD:56342:1.3278374E8
  SCHEMA:3047:3b06c1af-6527-3848-be90-eaa85163323d
  DC:8:DC1
  RACK:10:r1
  RELEASE_VERSION:4:3.11.1.2
  INTERNAL_IP:6:10.xx.xx.100
  RPC_ADDRESS:3:10.xx.xx.100
  NET_VERSION:1:11
  HOST_ID:2:4340ebc5-cec3-4756-ae77-315ba735315e
  RPC_READY:32:true
  X1:2220:{"logs-000001":3,"logs-2018.10.23-000002":3,"logs-2018.10.23-000003":3,"dbt":3,".kibana":3,"dbt_2_0_ubt_trl_data":3,"kpi_data":3,"kpi_data_20180922":3,"logs-2018.10.23-1":3,"kpi_data_20180925":3}
  X2:3030:27fb73df-dffa-485a-8be4-bf1ba480d094/2004
  TOKENS:15:<hidden>
/10.xx.xx.136
  generation:1541065366
  heartbeat:56324
  STATUS:16:NORMAL,-5911414817999602560
  LOAD:56279:1.2920235E8
  SCHEMA:2970:3b06c1af-6527-3848-be90-eaa85163323d
  DC:8:DC1
  RACK:10:r1
  RELEASE_VERSION:4:3.11.1.2
  INTERNAL_IP:6:10.xx.xx.136
  RPC_ADDRESS:3:10.xx.xx.136
  NET_VERSION:1:11
  HOST_ID:2:27fb73df-dffa-485a-8be4-bf1ba480d094
  RPC_READY:36:true
  X1:2192:{"logs-000001":3,"logs-2018.10.23-000002":3,"logs-2018.10.23-000003":3,"dbt":3,".kibana":3,"dbt_2_0_ubt_trl_data":3,"kpi_data":3,"kpi_data_20180922":3,"logs-2018.10.23-1":3,"kpi_data_20180925":3}
  X2:2957:27fb73df-dffa-485a-8be4-bf1ba480d094/2004
  TOKENS:15:<hidden>

this is the gossip info, do you mean  I have to upgrade to 5.5.0.24, that will mean much to do....

**Comment by zallan114** [comment]
too many this kind of exception, is this cluster getting to some issues??

[clusterService#updateTask][T#1]] org.elasticsearch.cluster.service.ClusterService.lambda$publishAndApplyChanges$3(ClusterService.java:1600) failed to notify ClusterStateListener
java.lang.NullPointerException: null

**Comment by zallan114** [comment]
will try to upgrade, thanks
