### ISSUE TITLE
Problem with hints 

### ISSUE THREAD

**Issue by prog-toolbox** [strapdata/elassandra#234]
Elassandra : 5.5.0.20

JDK : 1.8

Hello,

I have a problem with the hints in my cluster.
In fact, my cluster is composed of 5 nodes : 3 of them running as "Cassandra-Only" Nodes (located in a DataCenter) and the other 2 are running as "Cassandra+Elasticsearch" Nodes (located as well in another DataCenter).
The size of the hints folder increases rapidly and it reaches nearly the 90% of the hard drive (50 Gb).
The test scenario is the following : I applied 1000 UPDATE requests per second on the first DC. I wanted to make this test lasts 3 hours. The first node of the second DC stopped, and after few minutes, the second node stopped as well. The hints files started to increase rapidly and consumed a big part of my hard drive.
This test fails after few minutes.
The replication factor is 2 for both DCs and the consistency level is LOCAL_ONE.

My goal is to synchronize data between both DCs. I use the first one for all my INSERT operations and the second one, I use it for all my reasearch operations (Elasticsearch). 

In your point of view, are the LOCAL_ONE and RF = 2 the best configuration to apply for my use case ?
Could you please tell me also, what is the best configuration of the hints properties : hinted_handoff_throttle_in_kb, max_hint_window_in_ms and max_hints_delivery_threads ?
 
I appreciate your help.

**Comment by vroyer** [comment]
Hi,
This issue seems is not related to elassandra but to cassandra hinted handoff.
If you stop nodes from DC2, coordinator nodes in DC1 writes hinted-handoff files for 3 hours until dead nodes restarts. You can reduce max_hint_window_in_ms if you want to write less.
hinted_handoff_throttle_in_kb + max_hints_delivery_threads parameter manage the throughput when sending hint files to restarted node, the goal is to avoid to flood restarted nodes...

**Comment by prog-toolbox** [comment]
Hello Vincent,

I uncommented the parameter **bootstrap.lock_memory = true** in **elasticsearch.yml**, which made my test lasted for 3 hours with 1000 req/s with makes a total of more than 10 million requests.
But after 4 minutes, the 2 node running as "Cassandra+Elasticsearch" stopped with the following exception : 

**First issue :** 

```
9021278,-2817472381189690266], (-3929188133397672571,-3913833468870685396], (-4033093803027185562,-4016836577530498110], (8901882011341929445,8904647106802551150], (7578457191851604982,7595626512202877369], (-4974005584955699594,-4968629594710433057], (-4097249812887672084,-4058449273266743545]]] Sync failed between /Cassandra_Node_IP and /Elassandra_Node_IP
        at org.apache.cassandra.repair.RemoteSyncTask.syncComplete(RemoteSyncTask.java:67)
        at org.apache.cassandra.repair.RepairSession.syncComplete(RepairSession.java:202)
        at org.apache.cassandra.service.ActiveRepairService.handleMessage(ActiveRepairService.java:498)
        at org.apache.cassandra.repair.RepairMessageVerbHandler.doVerb(RepairMessageVerbHandler.java:162)
        at org.apache.cassandra.net.MessageDeliveryTask.run(MessageDeliveryTask.java:66)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.cassandra.concurrent.NamedThreadFactory.lambda$threadLocalDeallocator$0(NamedThreadFactory.java:81)
        at java.lang.Thread.run(Thread.java:748)
2018-11-08 14:38:42,584 WARN  [elasticsearch[10.68.253.23][generic][T#4]] NodeConnectionsService.java:165 validateAndConnectIfNeeded failed to connect to node {Elassandra_Node_IP}{7ee1ea53-4e74-4a1c-b393-5f4f9398b1a4}{7ee1ea53-4e74-4a1c-b393-5f4f9398b1a4}{Elassandra_Node_IP}{Elassandra_Node_IP:9300}{ALIVE}{rack=RAC1, dc=DC-ES} (tried [1] times)
org.elasticsearch.transport.ConnectTransportException: [Elassandra_Node_IP][Elassandra_Node_IP:9300] connect_timeout[30s]
        at org.elasticsearch.transport.netty4.Netty4Transport.connectToChannels(Netty4Transport.java:366)
        at org.elasticsearch.transport.TcpTransport.openConnection(TcpTransport.java:548)
        at org.elasticsearch.transport.TcpTransport.connectToNode(TcpTransport.java:472)
        at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:344)
        at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:331)
        at org.elasticsearch.cluster.NodeConnectionsService.validateAndConnectIfNeeded(NodeConnectionsService.java:156)
        at org.elasticsearch.cluster.NodeConnectionsService$ConnectionChecker.doRun(NodeConnectionsService.java:185)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /Elassandra_Node_IP:9300
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:352)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:632)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:544)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        ... 1 common frames omitted
Caused by: java.net.ConnectException: Connection refused
        ... 10 common frames omitted
2018-11-08 14:38:56,225 INFO  [GossipTasks:1] Gossiper.java:1034 markDead InetAddress /Elassandra_Node_IP is now DOWN
2018-11-08 14:38:56,355 ERROR [GossipTasks:1] AnticompactionTask.java:171 convict [repair #/Elassandra_Node_IP] Endpoint 4c8f5fb0-e355-11e8-a1b2-0b2de6b8dcfa died during anti-compaction
java.io.IOException: Endpoint /Elassandra_Node_IP died during anti-compaction.
        at org.apache.cassandra.repair.AnticompactionTask.convict(AnticompactionTask.java:167)
        at org.apache.cassandra.gms.FailureDetector.interpret(FailureDetector.java:307)
        at org.apache.cassandra.gms.Gossiper.doStatusCheck(Gossiper.java:802)
        at org.apache.cassandra.gms.Gossiper.access$700(Gossiper.java:68)
        at org.apache.cassandra.gms.Gossiper$GossipTask.run(Gossiper.java:194)
        at org.apache.cassandra.concurrent.DebuggableScheduledThreadPoolExecutor$UncomplainingRunnable.run(DebuggableScheduledThreadPoolExecutor.java:118)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.cassandra.concurrent.NamedThreadFactory.lambda$threadLocalDeallocator$0(NamedThreadFactory.java:81)
        at java.lang.Thread.run(Thread.java:748)
2018-11-08 14:39:13,398 WARN  [PERIODIC-COMMIT-LOG-SYNCER] NoSpamLogger.java:94 log Out of 30 commit log syncs over the past 295.53s with average duration of 432.28ms, 20 have exceeded the configured commit interval by an average of 471.03ms
2018-11-08 14:39:45,934 INFO  [MemtableFlushWriter:65] ElasticSecondaryIndex.java:2347 lambda$getBlockingFlushTask$6 Elasticsearch index=[MY_INDICE] type=[MY_TYPE] flushed, duration=2849ms
2018-11-08 14:40:31,294 INFO  [Service Thread] GCInspector.java:284 handleNotification G1 Young Generation GC in 263ms.  G1 Eden Space: 2634022912 -> 0; G1 Survivor Space: 96468992 -> 117440512;

```
**Second issue :** 

One more thing, I tried to activate the native Elasticsearch log by uncommenting the log part in **elasticsearch.yml** and I obtained a NullPointerException about the **cassandra-topology.properties**. Is there a link between the 2 files ? 
Anyway, I had already deleted the **cassandra-topology.properties** before starting all nodes long time ago : 
https://docs.datastax.com/en/cassandra/3.0/cassandra/architecture/archsnitchGossipPF.html :
**To allow migration from the PropertyFileSnitch, the GossipingPropertyFileSnitch uses the cassandra-topology.properties file when present. Delete the file after the migration is complete. For more information about migration, see Switching snitches.

Note: The GossipingPropertyFileSnitch always loads cassandra-topology.properties when that file is present. Remove the file from each node on any new cluster or any cluster migrated from the PropertyFileSnitch.**

Log **system.log** : 
```
org.apache.cassandra.config.DatabaseDescriptor.applySimpleConfig(DatabaseDescriptor.java:429) Global memtable off-heap threshold is enabled at 2048MB
2018-11-08 10:32:38,852 WARN  [main] DatabaseDescriptor.java:550 applySimpleConfig Only 62.377GiB free across all data volumes. Consider adding more capacity to your cluster or removing obsolete snapshots
2018-11-08 10:32:38,852 WARN  [main] org.apache.cassandra.config.DatabaseDescriptor.applySimpleConfig(DatabaseDescriptor.java:550) Only 62.377GiB free across all data volumes. Consider adding more capacity to your cluster or removing obsolete snapshots
2018-11-08 10:32:38,920 INFO  [main] RateBasedBackPressure.java:123 <init> Initialized back-pressure with high ratio: 0.9, factor: 5, flow: FAST, window size: 60000.
2018-11-08 10:32:38,920 INFO  [main] org.apache.cassandra.net.RateBasedBackPressure.<init>(RateBasedBackPressure.java:123) Initialized back-pressure with high ratio: 0.9, factor: 5, flow: FAST, window size: 60000.
2018-11-08 10:32:38,921 INFO  [main] DatabaseDescriptor.java:729 applySimpleConfig Back-pressure is disabled with strategy null.
2018-11-08 10:32:38,921 INFO  [main] org.apache.cassandra.config.DatabaseDescriptor.applySimpleConfig(DatabaseDescriptor.java:729) Back-pressure is disabled with strategy null.
2018-11-08 10:32:38,985 INFO  [main] GossipingPropertyFileSnitch.java:68 <init> Unable to load cassandra-topology.properties; compatibility mode disabled
2018-11-08 10:32:38,985 INFO  [main] org.apache.cassandra.locator.GossipingPropertyFileSnitch.<init>(GossipingPropertyFileSnitch.java:68) Unable to load cassandra-topology.properties; compatibility mode disabled
```
What are the causes for these 2 issues ?

**Comment by vroyer** [comment]
Hi,

This quite normal to have connection issue to a stopped node, but your log is incomplet to see why the node stopped. For the bootstrap.lock_memory, you should check in the beginning of your logs than JNA is ok.

For the 2nd issue, logging should only be configured in conf/logback.xml, and there s no NPE in the logs  you provided, but a warning indicating the cassandra-topology.properties was not loaded ?

(Please use distinct tickets for distincts issues)
Thanks.
