### ISSUE TITLE
Creating kibana Index using Elassandra and Sentinl

### ISSUE THREAD

**Issue by sawdyj** [strapdata/elassandra#260]
My project is using Elassandra alongside Kibana to visualise our data. I'm trying to use sentinl as a plugin for Kibana to allow us to report and alert on events. Using Elasticsearch and Kibana separately works perfectly fine but when using a clear Elassandra, Kibana errors on an indexing issue. 

I raised the following on the Sentinl page but I thought there might also be some help on here.
https://github.com/sirensolutions/sentinl/issues/650 

The issue is found as soon as I make a kibana index on my data. Please see the below log. 
If anyone has seen this issue before I would appreciate some help or guidance on the index mapping issue. Many thanks!

I am using Kibana and Elassandra 6.2.3.

**I get the following log**
C:\kibana-6.2.3-windows-x86_64\bin>kibana.bat
log [14:48:01.265] [info][status][plugin:kibana@6.2.3] Status changed from uninitialized to gree
n - Ready
log [14:48:01.345] [info][status][plugin:elasticsearch@6.2.3] Status changed from uninitialized
to yellow - Waiting for Elasticsearch
log [14:48:01.351] [info][status][plugin:sentinl@6.0.0] Status changed from uninitialized to gre
en - Ready
log [14:48:01.359] [info][status][plugin:console@6.2.3] Status changed from uninitialized to gre
en - Ready
log [14:48:01.366] [info][status][plugin:metrics@6.2.3] Status changed from uninitialized to gre
en - Ready
log [14:48:02.191] [info][status][plugin:timelion@6.2.3] Status changed from uninitialized to gr
een - Ready
log [14:48:02.228] [info][listening] Server running at http://localhost:5601
log [14:48:02.366] [info][status][plugin:elasticsearch@6.2.3] Status changed from yellow to gree
n - Ready
log [14:48:02.371] [info][Sentinl][init] initializing ...
log [14:48:02.436] [info][Sentinl][init] Chrome bin found at: C:\kibana-6.2.3-windows-x86_64\plu
gins\sentinl\node_modules\puppeteer.local-chromium\linux-564778\chrome-linux\chrome
log [14:48:02.493] [info][Sentinl][init_indices] checking .kibana index ...
log [14:48:02.871] [info][Sentinl][init_indices] creating .kibana index ...
log [14:48:03.652] [error][Sentinl][init] start: Error: init indices: Error: create index: [i_o_
exception] Unknown type _kibana.doc_sentinl-watcher_input :: {"path":"/.kibana","query":{},"body":"{
"mappings":{"doc":{"properties":{"sentinl-watcher":{"properties":{"wizard":{"type":"o
bject","enabled":false},"input":{"type":"object","enabled":false},"actions":{"type":
"object","enabled":false},"transform":{"type":"object","enabled":false},"condition":{"
type":"object","enabled":false},"trigger":{"type":"object","enabled":false},"report":
{"type":"boolean"},"disable":{"type":"boolean"},"save_payload":{"type":"boolean"},"
impersonate":{"type":"boolean"},"spy":{"type":"boolean"},"title":{"type":"text"},"
username":{"type":"text"},"sentinl":{"type":"object","enabled":false},"dashboard_link
":{"type":"text"},"custom":{"type":"object","enabled":false}}},"sentinl-user":{"prope
rties":{"username":{"type":"text"},"sha":{"type":"text"},"password":{"type":"text
"}}}}}}}","statusCode":500,"response":"{"error":{"root_cause":[{"type":"i_o_exception","rea
son":"Unknown type _kibana.doc_sentinl-watcher_input"}],"type":"i_o_exception","reason":"U
nknown type _kibana.doc_sentinl-watcher_input","caused_by":{"type":"invalid_request_exception
","reason":"Unknown type _kibana.doc_sentinl-watcher_input"}},"status":500}"}
log [14:48:04.071] [info][Sentinl][init] PhantomJS bin found at: C:\kibana-6.2.3-windows-x86_64
plugins\sentinl\phantomjs\phantomjs-2.1.1-windows\bin\phantomjs.exe
error [14:58:32.943] [i_o_exception] Unknown type _kibana.doc_sentinl-watcher_input :: {"path":"/
.kibana/doc/index-pattern%3Ab82b0340-0467-11e9-b401-e956cf8b6277","query":{"refresh":"wait_for"},"bo
dy":"{"type":"index-pattern","updated_at":"2018-12-20T14:58:32.948Z","index-pattern":{"ti
tle":"observable*","timeFieldName":"timestamp"}}","statusCode":500,"response":"{"error":{"
root_cause":[{"type":"i_o_exception","reason":"Unknown type _kibana.doc_sentinl-watcher_inpu
t"}],"type":"i_o_exception","reason":"Unknown type _kibana.doc_sentinl-watcher_input","cau
sed_by":{"type":"invalid_request_exception","reason":"Unknown type _kibana.doc_sentinl-watch
er_input"}},"status":500}"}
at respond (C:\kibana-6.2.3-windows-x86_64\node_modules\elasticsearch\src\lib\transport.js:295:1
5)
at checkRespForFailure (C:\kibana-6.2.3-windows-x86_64\node_modules\elasticsearch\src\lib\transp
ort.js:254:7)
at HttpConnector. (C:\kibana-6.2.3-windows-x86_64\node_modules\elasticsearch\src\lib
connectors\http.js:159:7)
at IncomingMessage.bound (C:\kibana-6.2.3-windows-x86_64\node_modules\elasticsearch\node_modules
\lodash\dist\lodash.js:729:21)
at emitNone (events.js:91:20)
at IncomingMessage.emit (events.js:185:7)
at endReadableNT (_stream_readable.js:974:12)
at _combinedTickCallback (internal/process/next_tick.js:80:11)
at process._tickDomainCallback (internal/process/next_tick.js:128:9)

**Comment by vroyer** [comment]
The dash in doc_sentinl-watcher_input is not supported by cassandra.
Normally, it should be converted to doc_sentinl_watcher_input automatically.
How do you create it ?
What's your elassandra version 6.2.3.x ?
Thanks.

**Comment by sawdyj** [comment]
Sorry for my late response. I am running elassandra 6.2.3.5 with Kibana 6.2.3.
The sentinl watcher seems to get created automatically when I try to create an index within kibana as this is when it crashes. I'm unsure why the - is not converted.
