### ISSUE TITLE
Issue in Loading Enterprise Trail License for Multi DC setup

### ISSUE THREAD

**Issue by ackarande** [strapdata/elassandra#266]
Trying to evaluate Elassandra enterprise TRIAL version

**Elassandra version**: Elassandra 6.2.3.8

**Plugins installed**: [strapdata-plugin]

**JVM version** (`java -version`): 1.8.0_181

**OS version** (`uname -a` if on a Unix-like system): x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
There is a failure in loading Enterprise trial license for Multi Data center setup.

**Steps to reproduce**:

 1. Install Enterprise plugin
 2. Update elasticsearch providing data center group and https.enabled: true. (Multi Data center setup)
 3. Start elassandra with and check logs.

* elassandra logs (logs/system.logs or /var/lib/cassandra/system.log)

2019-02-06 14:25:00,944 ERROR [elasticsearch[10.247.13.22][clusterApplierService#updateTask][T#1]] InternalLicenseService.java:359 init Failed to create licenses table or load default license file
org.apache.cassandra.exceptions.ConfigurationException: Keyspace elastic_admin doesn't exist
        at org.apache.cassandra.config.Schema.getKSMetaDataSafe(Schema.java:304)
        at org.apache.cassandra.cql3.statements.CreateTableStatement$RawStatement.prepare(CreateTableStatement.java:198)
        at org.apache.cassandra.cql3.QueryProcessor.getStatement(QueryProcessor.java:564)
        at org.apache.cassandra.cql3.QueryProcessor.prepare(QueryProcessor.java:419)
        at org.apache.cassandra.cql3.QueryProcessor.prepare(QueryProcessor.java:410)
        at org.apache.cassandra.cql3.QueryProcessor.prepare(QueryProcessor.java:404)
        at org.elasticsearch.cluster.service.ClusterService.process(ClusterService.java:521)
        at org.elasticsearch.cluster.service.ClusterService.process(ClusterService.java:511)
        at org.elasticsearch.cluster.service.ClusterService.process(ClusterService.java:487)

**Comment by vroyer** [comment]
Hi,

Thanks for reporting this bug.
This will be fix in the next release 6.2.3.11 planned for tomorrow.

**Comment by vroyer** [comment]
This is fixed in release 6.2.3.11 now available with the [enterprise plugin 6.2.3.11](https://packages.strapdata.com/strapdata-enterprise-6.2.3.11.zip).
Thanks.
