### ISSUE TITLE
cannot change DocValues type from NUMERIC to SORTED_NUMERIC for field "_token"

### ISSUE THREAD

**Issue by dazoot** [strapdata/elassandra#287]
**Elassandra version**: 6.2.3.14 

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_201

**OS version** (`uname -a` if on a Unix-like system): `3.2.0-4-amd64 #1 SMP Debian 3.2.93-1 x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**:

For one of our indexes i am getting lots of IllegalArgumentExceptions when inserting data.

```
2019-05-07 18:10:31,413 ERROR [MutationStage-1] ElasticSecondaryIndex.java:2358 indexParsedDocument document CF=nzcab_abonat.nzcab_abonat_abonat index/type=nzcab_abonat/nzcab_abonat_abonat id=198314843 version=1 created=false static=false ttl=0 refresh=false
java.lang.IllegalArgumentException: cannot change DocValues type from NUMERIC to SORTED_NUMERIC for field "_token"
```

**Steps to reproduce**:

1. Create the index
2. Insert some data in batches (Elastic Search Bulk API)

* elassandra logs (logs/system.logs or /var/lib/cassandra/system.log)
```
2019-05-07 18:10:31,413 ERROR [MutationStage-1] ElasticSecondaryIndex.java:2358 indexParsedDocument document CF=nzcab_abonat.nzcab_abonat_abonat index/type=nzcab_abonat/nzcab_abonat_abonat id=198314843 version=1 created=false static=false ttl=0 refresh=false
java.lang.IllegalArgumentException: cannot change DocValues type from NUMERIC to SORTED_NUMERIC for field "_token"
        at org.apache.lucene.index.FieldInfos$FieldNumbers.verifyConsistent(FieldInfos.java:296)
        at org.apache.lucene.index.FieldInfos$FieldNumbers.setDocValuesType(FieldInfos.java:344)
        at org.apache.lucene.index.DefaultIndexingChain.indexDocValue(DefaultIndexingChain.java:524)
        at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:466)
        at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:392)
        at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:240)
        at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:496)
        at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1729)
        at org.elasticsearch.index.engine.VersionLessInternalEngine.update(VersionLessInternalEngine.java:1168)
        at org.elasticsearch.index.engine.VersionLessInternalEngine.indexIntoLucene(VersionLessInternalEngine.java:1018)
        at org.elasticsearch.index.engine.VersionLessInternalEngine.index(VersionLessInternalEngine.java:882)
        at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:816)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$RowcumentIndexer$Rowcument.indexParsedDocument(ElasticSecondaryIndex.java:2355)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$RowcumentIndexer$Rowcument.index(ElasticSecondaryIndex.java:2318)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$RowcumentIndexer$Rowcument.index(ElasticSecondaryIndex.java:2267)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$SkinnyRowcumentIndexer$SkinnyRowcument.index(ElasticSecondaryIndex.java:1739)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$RowcumentIndexer$Rowcument.write(ElasticSecondaryIndex.java:2250)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$SkinnyRowcumentIndexer$SkinnyRowcument.write(ElasticSecondaryIndex.java:1739)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$SkinnyRowcumentIndexer.update(ElasticSecondaryIndex.java:1780)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$RowcumentIndexer.finish(ElasticSecondaryIndex.java:1964)
        at org.apache.cassandra.index.SecondaryIndexManager$WriteTimeTransaction.commit(SecondaryIndexManager.java:1408)
        at org.apache.cassandra.db.partitions.AtomicBTreePartition.addAllWithSizeDelta(AtomicBTreePartition.java:181)
        at org.apache.cassandra.db.Memtable.put(Memtable.java:282)
        at org.apache.cassandra.db.ColumnFamilyStore.apply(ColumnFamilyStore.java:1359)
        at org.apache.cassandra.db.Keyspace.applyInternal(Keyspace.java:631)
        at org.apache.cassandra.db.Keyspace.apply(Keyspace.java:475)
        at org.apache.cassandra.db.Mutation.apply(Mutation.java:227)
        at org.apache.cassandra.db.Mutation.apply(Mutation.java:232)
        at org.apache.cassandra.db.Mutation.apply(Mutation.java:241)
        at org.apache.cassandra.service.StorageProxy$8.runMayThrow(StorageProxy.java:1398)
        at org.apache.cassandra.service.StorageProxy$LocalMutationRunnable.run(StorageProxy.java:2637)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:162)
        at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:114)
        at java.lang.Thread.run(Thread.java:748)
```

* cassandra schema (cqlsh>DESC KEYSPACE <your_keyspace>)
```
cqlsh> desc keyspace nzcab_abonat;

CREATE KEYSPACE nzcab_abonat WITH replication = {'class': 'NetworkTopologyStrategy', 'DC1': '1'}  AND durable_writes = true;

CREATE TABLE nzcab_abonat.nzcab_abonat_abonat (
    "_id" text PRIMARY KEY,
    abonat_id list<int>,
    active_status list<int>,
    bounce_status list<int>,
    confirm_date list<timestamp>,
    domain list<text>,
    email list<text>,
    firstname list<text>,
    lastname list<text>,
    list_id list<int>,
    sub_datetime list<timestamp>,
    sub_type list<text>,
    subscription_status list<int>
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';
CREATE CUSTOM INDEX elastic_nzcab_abonat_abonat_idx ON nzcab_abonat.nzcab_abonat_abonat () USING 'org.elassandra.index.ExtendedElasticSecondaryIndex';
```
* cassandra gossip state (run: nodetool gossipinfo)
```
/192.168.1.1
  generation:1557240958
  heartbeat:1784
  STATUS:16:NORMAL,-1864418171401340897
  LOAD:1761:5.1198726963E10
  SCHEMA:12:0e994327-fd21-35db-96ba-b64a06ce3452
  DC:8:DC1
  RACK:10:r1
  RELEASE_VERSION:4:3.11.4
  INTERNAL_IP:6:192.168.1.1
  RPC_ADDRESS:3:192.168.1.1
  NET_VERSION:1:11
  HOST_ID:2:389f205a-b9dd-4ffc-b5b5-9daccbdd02f4
  RPC_READY:28:true
  X1:30:{"dev_ecommerce_product_view":3,"dev_ecommerce_purchase":3,"nzsrv_abonat":3,"dev_ecommerce_product_category2":3,"ecommerce_subscriber":3,"ecommerce_product_category2":3,"ecommerce_product_category":3,"ecommerce_product_view2":3,"dev_ecommerce_subscriber":3,"dev_ecommerce_product_category":3,"nzcab_abonat":3,"dev_abonat":3,"ecommerce_cart":3,"dev_ecommerce_product_view2":3,"dev_ecommerce_cart":3,"ecommerce_purchase":3,"ecommerce_product_view":3}
  X2:32:389f205a-b9dd-4ffc-b5b5-9daccbdd02f4/34
  TOKENS:15:<hidden>
```

**Comment by vroyer** [comment]
Hi,
Elassandra 6.2.3.10 introduced a breaking change in _token storage and you probably have lucene files generated with this version in you /var/lib/cassandra/elasticsearch.data. The workaround is to delete those indices and recreate it from the cassandra data. This breaking changed has been fixed in 6.2.3.11, so 6.2.3.10 is this only version that could cause this issue.

**Comment by dazoot** [comment]
I did:

1. `curl -X DELETE http://localhost:9200/nzcab_abonat`
2. `nodetool  rebuild_index --threads 4 nzcab_abonat nzcab_abonat_abonat elastic_nzcab_abonat_abonat_idx`

Now i get too many errors like this:
```
java.lang.ClassCastException: null
2019-05-08 09:47:45,867 ERROR [CompactionExecutor:2] ElasticSecondaryIndex.java:2255 write Unexpected error
java.lang.ClassCastException: null
2019-05-08 09:47:45,868 ERROR [CompactionExecutor:2] ElasticSecondaryIndex.java:2255 write Unexpected error
java.lang.ClassCastException: null
2019-05-08 09:47:45,869 ERROR [CompactionExecutor:2] ElasticSecondaryIndex.java:2255 write Unexpected error
java.lang.ClassCastException: null
2019-05-08 09:47:45,873 ERROR [CompactionExecutor:2] ElasticSecondaryIndex.java:2255 write Unexpected error
java.lang.ClassCastException: null
2019-05-08 09:47:45,874 ERROR [CompactionExecutor:2] ElasticSecondaryIndex.java:2255 write Unexpected error
```

**Comment by vroyer** [comment]
You need to re-create your index (with a mapping) before rebuilding it.

**Comment by dazoot** [comment]
Yup. This fixed it.
