### ISSUE TITLE
index.mapping.ignore_malformed not working on Multifield

### ISSUE THREAD

**Issue by ackarande** [strapdata/elassandra#292]
Hi,
I have ignore_malformed set at index level which is not working.
Version of Elassandra: 6.2.3.11

I see data present in cassandra but when searched through rest api I am unable to retrieve.

I see below error in logs:
**2019-05-15 07:50:35,627 ERROR [MutationStage-1] ElasticSecondaryIndex.java:2250 write Unexpected error
java.lang.ClassCastException: null**

My index mappings:
{
    "version": 1,
    "settings": {
        "replication": "DC1:2",
        "drop_on_delete_index": true,
        "index.codec": "best_compression",
        "number_of_shards": 1,
        "index.mapping.ignore_malformed": true
    },
    "aliases": {},
    "mappings": {
        "doc": {
            "_source": {"enabled": true},
            "properties": {
                "testfield": {
                    "type": "nested",
                    "properties": {
                        "testfieldName": {
                            "type": "text",
                            "analyzer": "keyword"
                        },
                        "testfieldValue": {
                            "type": "text",
                            "analyzer": "keyword",
                            "fields": {
                                "text": {
                                    "type": "text",
                                    "analyzer": "keyword"
                                },
                                "numeric": {"type": "double"},
                                "date": {"type": "date"}
                            }
                        }
                    }
                }
            }
        }
    }
}

Input data:
{
"testfield":{
"testfieldName":"test",
"testfieldValue":"testValue"
}
}

########################
Few more errors for OTHER type of data

2019-05-14 14:52:32,890 ERROR [MutationStage-1] ElasticSecondaryIndex.java:2250 write Unexpected error
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long
        at org.elasticsearch.index.mapper.DateFieldMapper.createField(DateFieldMapper.java:554)
        at org.elasticsearch.index.mapper.FieldMapper$MultiFields.create(FieldMapper.java:683)
        at org.elasticsearch.index.mapper.FieldMapper.createField(FieldMapper.java:375)
        at org.elasticsearch.index.mapper.TextFieldMapper.createField(TextFieldMapper.java:386)
        at org.elassandra.index.ElasticSecondaryIndex.addField(ElasticSecondaryIndex.java:414)
        at org.elassandra.index.ElasticSecondaryIndex.addField(ElasticSecondaryIndex.java:388)
        at org.elassandra.index.ElasticSecondaryIndex.addField(ElasticSecondaryIndex.java:514)
        at org.elassandra.index.ElasticSecondaryIndex.addField(ElasticSecondaryIndex.java:388)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$RowcumentIndexer$Rowcument.buildContext(ElasticSecondaryIndex.java:2192)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$SkinnyRowcumentIndexer$SkinnyRowcument.buildContext(ElasticSecondaryIndex.java:1738)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$RowcumentIndexer$Rowcument.index(ElasticSecondaryIndex.java:2285)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$RowcumentIndexer$Rowcument.index(ElasticSecondaryIndex.java:2262)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$SkinnyRowcumentIndexer$SkinnyRowcument.index(ElasticSecondaryIndex.java:1738)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$RowcumentIndexer$Rowcument.write(ElasticSecondaryIndex.java:2245)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$SkinnyRowcumentIndexer$SkinnyRowcument.write(ElasticSecondaryIndex.java:1738)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$SkinnyRowcumentIndexer.update(ElasticSecondaryIndex.java:1779)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$RowcumentIndexer.finish(ElasticSecondaryIndex.java:1962)
        at org.apache.cassandra.index.SecondaryIndexManager$WriteTimeTransaction.commit(SecondaryIndexManager.java:1406)
        at org.apache.cassandra.db.partitions.AtomicBTreePartition.addAllWithSizeDelta(AtomicBTreePartition.java:181)
        at org.apache.cassandra.db.Memtable.put(Memtable.java:282)
        at org.apache.cassandra.db.ColumnFamilyStore.apply(ColumnFamilyStore.java:1342)
        at org.apache.cassandra.db.Keyspace.applyInternal(Keyspace.java:631)
        at org.apache.cassandra.db.Keyspace.apply(Keyspace.java:475)
        at org.apache.cassandra.db.Keyspace.apply(Keyspace.java:455)
        at org.apache.cassandra.service.paxos.PaxosState.commit(PaxosState.java:150)
        at org.apache.cassandra.service.paxos.CommitVerbHandler.doVerb(CommitVerbHandler.java:33)
        at org.apache.cassandra.net.MessageDeliveryTask.run(MessageDeliveryTask.java:66)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:162)
        at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$LocalSessionFutureTask.run(AbstractLocalAwareExecutorService.java:134)
        at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:109)
        at java.lang.Thread.run(Unknown Source)

**Comment by ackarande** [comment]
Hi, can you please advice as I am blocked

**Comment by vroyer** [comment]
Please provide the full mapping (in a pretty format) and the CQL schema.
Thanks.

**Comment by ackarande** [comment]
Hi,

**Complete mapping:**
{
    "version": 1,
    "settings": {
        "replication": "DC1:2",
        "drop_on_delete_index": true,
        "index.codec": "best_compression",
        "number_of_shards": 1,
        "index.mapping.ignore_malformed": true
    },
    "aliases": {},
    "mappings": {
        "doc": {
            "_source": {"enabled": true},
            "properties": {
                "testfield": {
                    "type": "nested",
                    "properties": {
                        "testfieldName": {
                            "type": "text",
                            "analyzer": "keyword"
                        },
                        "testfieldValue": {
                            "type": "text",
                            "analyzer": "keyword",
                            "fields": {
                                "text": {
                                    "type": "text",
                                    "analyzer": "keyword"
                                },
                                "numeric": {"type": "double"},
                                "date": {"type": "date"}
                            }
                        }
                    }
                }
            }
        }
    }
}

**Input document for failure scenario**
{
    "testfield":{
    "testfieldName":"test",
    "testfieldValue":123
}
}

CQL Schema:

describe test_index2;

CREATE KEYSPACE test_index2 WITH replication = {'class': 'NetworkTopologyStrategy', 'DC1': '2'}  AND durable_writes = true;

CREATE TYPE test_index2.doc_testfield (
    "testfieldValue" list<text>,
    "testfieldName" list<text>
);

CREATE TABLE test_index2.doc (
    "_id" text PRIMARY KEY,
    "_source" blob,
    testfield list<frozen<doc_testfield>>
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';
CREATE CUSTOM INDEX elastic_doc_idx ON test_index2.doc () USING 'org.elassandra.index.ExtendedElasticSecondaryIndex';

Stacktrace in logs:
2019-05-22 14:00:28,921 WARN  [elasticsearch[10.247.17.29][bulk][T#2]] BytesRestResponse.java:133 build path: /test_index2/doc/112233, params: {index=test_index2, id=112233, type=doc}
org.elasticsearch.transport.RemoteTransportException: [10.247.17.29][10.247.17.29:9300][indices:data/write/bulk[s][p]]
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
        at org.apache.cassandra.serializers.AbstractTextSerializer.serialize(AbstractTextSerializer.java:28)
        at org.apache.cassandra.db.marshal.AbstractType.decompose(AbstractType.java:121)
        at org.elassandra.cluster.Serializer.serialize(Serializer.java:217)
        at org.elassandra.cluster.Serializer.serialize(Serializer.java:210)
        at org.elassandra.cluster.Serializer.serialize(Serializer.java:177)
        at org.elassandra.cluster.Serializer.serialize(Serializer.java:210)
        at org.elassandra.cluster.QueryManager.upsertDocument(QueryManager.java:803)
        at org.elassandra.cluster.QueryManager.insertDocument(QueryManager.java:665)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.executeIndexRequestOnPrimary(TransportShardBulkAction.java:574)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.executeIndexRequest(TransportShardBulkAction.java:148)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:246)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:129)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:115)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:73)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:1065)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:1043)
        at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:104)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:331)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:297)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:284)
        at com.strapdata.elasticsearch.plugin.aaa.transport.AAATransportRequestHandler.messageReceived(AAATransportRequestHandler.java:87)
        at com.strapdata.elasticsearch.plugin.EnterprisePlugin$5$1.messageReceived(EnterprisePlugin.java:384)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66)
        at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:661)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:672)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by ackarande** [comment]
Hi, 
The above mapping were formatted but seem it gets wrapped.

**Comment by vroyer** [comment]
Syntax seems to be incorrect in your UDT:

CREATE TYPE test_index2.doc_testfield (
        ... "testfieldValue" list,
        ... "testfieldName" list
        ... );

You are probably inserting text in a field interpreted as a date, causing an error, because elassandra was expecting a timestamp. I'have reproduce a similar issue and we can provide a fix in the next release. Let me know if you want to test this fix before the next release.
Thanks.

**Comment by ackarande** [comment]
Hi, 
Very much thanks for the reply. Appreciate the effort here.
Can you please let me know exact steps to test this change and I can test before next release?
Thanks

**Comment by ackarande** [comment]
The reason I want to test first is because my exact attribute in mapping is as below.
Which includes number, boolean, date, etc

"myAttribute": {
  "type": "nested",
  "properties": {
    "text": {
      "type": "text",
      "analyzer": "keyword"
    },
    "numeric": {
      "type": "double"
    },
    "date": {
      "type": "date"
    },
    "logical": {
      "type": "boolean"
    }
  }
}
