### ISSUE TITLE
Starting Elassandra [ecstart]

### ISSUE THREAD

**Issue by ChrisFeldmeier** [strapdata/elassandra#3]
Hello,

I always get this error if I start Elassandra:

What could be the problem?

CASSANDRA_HOME is set correct.

```
Starting with JVM debug address=4242 suspend=n
Starting with Elasticsearch enabled.
CLASSPATH=/root/elassandra-2.1.1-2//conf:/root/elassandra-2.1.1-2//bin/../lib/HdrHistogram-2.1.6.jar:/root/elassandra-2.1.1-2//bin/../lib/ST4-4.0.8.jar:/root/elassandra-2.1.1-2//bin/../lib/airline-0.6.jar:/root/elassandra-2.1.1-2//bin/../lib/ant-1.8.2.jar:/root/elassandra-2.1.1-2//bin/../lib/antlr-3.5.2.jar:/root/elassandra-2.1.1-2//bin/../lib/antlr-runtime-3.5.jar:/root/elassandra-2.1.1-2//bin/../lib/apache-log4j-extras-1.2.17.jar:/root/elassandra-2.1.1-2//bin/../lib/asm-4.1.jar:/root/elassandra-2.1.1-2//bin/../lib/asm-commons-4.1.jar:/root/elassandra-2.1.1-2//bin/../lib/cassandra-thrift-2.2.4.jar:/root/elassandra-2.1.1-2//bin/../lib/commons-cli-1.3.1.jar:/root/elassandra-2.1.1-2//bin/../lib/commons-codec-1.6.jar:/root/elassandra-2.1.1-2//bin/../lib/commons-lang3-3.1.jar:/root/elassandra-2.1.1-2//bin/../lib/commons-math3-3.2.jar:/root/elassandra-2.1.1-2//bin/../lib/compiler-0.8.13.jar:/root/elassandra-2.1.1-2//bin/../lib/compress-lzf-1.0.2.jar:/root/elassandra-2.1.1-2//bin/../lib/concurrentlinkedhashmap-lru-1.4.jar:/root/elassandra-2.1.1-2//bin/../lib/crc32ex-0.1.1.jar:/root/elassandra-2.1.1-2//bin/../lib/disruptor-3.0.1.jar:/root/elassandra-2.1.1-2//bin/../lib/elassandra-2.1.1-2.jar:/root/elassandra-2.1.1-2//bin/../lib/fastutil-6.5.7.jar:/root/elassandra-2.1.1-2//bin/../lib/groovy-all-2.4.4-indy.jar:/root/elassandra-2.1.1-2//bin/../lib/guava-18.0.jar:/root/elassandra-2.1.1-2//bin/../lib/hibernate-validator-4.3.0.Final.jar:/root/elassandra-2.1.1-2//bin/../lib/high-scale-lib-1.0.6.jar:/root/elassandra-2.1.1-2//bin/../lib/hppc-0.7.1.jar:/root/elassandra-2.1.1-2//bin/../lib/httpcore-4.2.4.jar:/root/elassandra-2.1.1-2//bin/../lib/icu4j-54.1.jar:/root/elassandra-2.1.1-2//bin/../lib/jackson-core-2.6.2.jar:/root/elassandra-2.1.1-2//bin/../lib/jackson-core-asl-1.9.13.jar:/root/elassandra-2.1.1-2//bin/../lib/jackson-dataformat-cbor-2.6.2.jar:/root/elassandra-2.1.1-2//bin/../lib/jackson-dataformat-smile-2.6.2.jar:/root/elassandra-2.1.1-2//bin/../lib/jackson-dataformat-yaml-2.6.2.jar:/root/elassandra-2.1.1-2//bin/../lib/jackson-mapper-asl-1.9.13.jar:/root/elassandra-2.1.1-2//bin/../lib/jamm-0.3.0.jar:/root/elassandra-2.1.1-2//bin/../lib/javassist-3.20.0-GA.jar:/root/elassandra-2.1.1-2//bin/../lib/javax.inject-1.jar:/root/elassandra-2.1.1-2//bin/../lib/jbcrypt-0.3m.jar:/root/elassandra-2.1.1-2//bin/../lib/jboss-logging-3.1.0.CR2.jar:/root/elassandra-2.1.1-2//bin/../lib/jcl-over-slf4j-1.7.7.jar:/root/elassandra-2.1.1-2//bin/../lib/jna-4.1.0.jar:/root/elassandra-2.1.1-2//bin/../lib/joda-convert-1.2.jar:/root/elassandra-2.1.1-2//bin/../lib/joda-time-2.8.2.jar:/root/elassandra-2.1.1-2//bin/../lib/json-simple-1.1.jar:/root/elassandra-2.1.1-2//bin/../lib/jsr166e-1.1.0.jar:/root/elassandra-2.1.1-2//bin/../lib/jts-1.13.jar:/root/elassandra-2.1.1-2//bin/../lib/junit-4.10.jar:/root/elassandra-2.1.1-2//bin/../lib/libthrift-0.9.2.jar:/root/elassandra-2.1.1-2//bin/../lib/log4j-1.2.17.jar:/root/elassandra-2.1.1-2//bin/../lib/log4j-over-slf4j-1.7.7.jar:/root/elassandra-2.1.1-2//bin/../lib/logback-classic-1.1.3.jar:/root/elassandra-2.1.1-2//bin/../lib/logback-core-1.1.3.jar:/root/elassandra-2.1.1-2//bin/../lib/lucene-analyzers-common-5.3.1.jar:/root/elassandra-2.1.1-2//bin/../lib/lucene-analyzers-icu-5.3.1.jar:/root/elassandra-2.1.1-2//bin/../lib/lucene-analyzers-kuromoji-5.3.1.jar:/root/elassandra-2.1.1-2//bin/../lib/lucene-analyzers-phonetic-5.3.1.jar:/root/elassandra-2.1.1-2//bin/../lib/lucene-analyzers-smartcn-5.3.1.jar:/root/elassandra-2.1.1-2//bin/../lib/lucene-analyzers-stempel-5.3.1.jar:/root/elassandra-2.1.1-2//bin/../lib/lucene-backward-codecs-5.3.1.jar:/root/elassandra-2.1.1-2//bin/../lib/lucene-codecs-5.3.1.jar:/root/elassandra-2.1.1-2//bin/../lib/lucene-core-5.3.1.jar:/root/elassandra-2.1.1-2//bin/../lib/lucene-expressions-5.3.1.jar:/root/elassandra-2.1.1-2//bin/../lib/lucene-grouping-5.3.1.jar:/root/elassandra-2.1.1-2//bin/../lib/lucene-highlighter-5.3.1.jar:/root/elassandra-2.1.1-2//bin/../lib/lucene-join-5.3.1.jar:/root/elassandra-2.1.1-2//bin/../lib/lucene-memory-5.3.1.jar:/root/elassandra-2.1.1-2//bin/../lib/lucene-misc-5.3.1.jar:/root/elassandra-2.1.1-2//bin/../lib/lucene-queries-5.3.1.jar:/root/elassandra-2.1.1-2//bin/../lib/lucene-queryparser-5.3.1.jar:/root/elassandra-2.1.1-2//bin/../lib/lucene-sandbox-5.3.1.jar:/root/elassandra-2.1.1-2//bin/../lib/lucene-spatial-5.3.1.jar:/root/elassandra-2.1.1-2//bin/../lib/lucene-spatial3d-5.3.1.jar:/root/elassandra-2.1.1-2//bin/../lib/lucene-suggest-5.3.1.jar:/root/elassandra-2.1.1-2//bin/../lib/lucene-test-framework-5.3.1.jar:/root/elassandra-2.1.1-2//bin/../lib/lz4-1.3.0.jar:/root/elassandra-2.1.1-2//bin/../lib/metrics-core-3.1.0.jar:/root/elassandra-2.1.1-2//bin/../lib/netty-3.10.5.Final.jar:/root/elassandra-2.1.1-2//bin/../lib/netty-all-4.0.23.Final.jar:/root/elassandra-2.1.1-2//bin/../lib/reporter-config-base-3.0.0.jar:/root/elassandra-2.1.1-2//bin/../lib/reporter-config3-3.0.0.jar:/root/elassandra-2.1.1-2//bin/../lib/sigar-1.6.4.jar:/root/elassandra-2.1.1-2//bin/../lib/slf4j-api-1.7.7.jar:/root/elassandra-2.1.1-2//bin/../lib/snakeyaml-1.15.jar:/root/elassandra-2.1.1-2//bin/../lib/snappy-java-1.1.1.7.jar:/root/elassandra-2.1.1-2//bin/../lib/spatial4j-0.5.jar:/root/elassandra-2.1.1-2//bin/../lib/stream-2.5.2.jar:/root/elassandra-2.1.1-2//bin/../lib/super-csv-2.1.0.jar:/root/elassandra-2.1.1-2//bin/../lib/t-digest-3.0.jar:/root/elassandra-2.1.1-2//bin/../lib/thrift-server-0.3.7.jar:/root/elassandra-2.1.1-2//bin/../lib/validation-api-1.0.0.GA.jar
root@v22016022703732037:~/elassandra-2.1.1-2/bin# CompilerOracle: inline org/apache/cassandra/db/AbstractNativeCell.compareTo (Lorg/apache/cassandra/db/composites/Composite;)I
CompilerOracle: inline org/apache/cassandra/db/composites/AbstractSimpleCellNameType.compareUnsigned (Lorg/apache/cassandra/db/composites/Composite;Lorg/apache/cassandra/db/composites/Composite;)I
CompilerOracle: inline org/apache/cassandra/io/util/Memory.checkBounds (JJ)V
CompilerOracle: inline org/apache/cassandra/io/util/SafeMemory.checkBounds (JJ)V
CompilerOracle: inline org/apache/cassandra/utils/ByteBufferUtil.compare (Ljava/nio/ByteBuffer;[B)I
CompilerOracle: inline org/apache/cassandra/utils/ByteBufferUtil.compare ([BLjava/nio/ByteBuffer;)I
CompilerOracle: inline org/apache/cassandra/utils/ByteBufferUtil.compareUnsigned (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
CompilerOracle: inline org/apache/cassandra/utils/FastByteOperations$UnsafeOperations.compareTo (Ljava/lang/Object;JILjava/lang/Object;JI)I
CompilerOracle: inline org/apache/cassandra/utils/FastByteOperations$UnsafeOperations.compareTo (Ljava/lang/Object;JILjava/nio/ByteBuffer;)I
CompilerOracle: inline org/apache/cassandra/utils/FastByteOperations$UnsafeOperations.compareTo (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
Listening for transport dt_socket at address: 4242
{2.1.2-SNAPSHOT}: Setup Failed ...
- NullPointerException[null value in entry: path.home=null]
java.lang.NullPointerException: null value in entry: path.home=null
    at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:33)
    at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:135)
    at com.google.common.collect.ImmutableSortedMap.fromEntries(ImmutableSortedMap.java:282)
    at com.google.common.collect.ImmutableSortedMap.copyOfInternal(ImmutableSortedMap.java:275)
    at com.google.common.collect.ImmutableSortedMap.copyOf(ImmutableSortedMap.java:206)
    at org.elasticsearch.common.settings.Settings.<init>(Settings.java:83)
    at org.elasticsearch.common.settings.Settings$Builder.build(Settings.java:1214)
    at org.apache.cassandra.service.ElassandraDaemon.main(ElassandraDaemon.java:250)
```

**Comment by vroyer** [comment]
Hi,
Just set and export CASSANDRA_HOME=&lt;your_elassandra_install_dir&gt;
Elassandra set the elasticsearch **path.home** to CASSANDRA_HOME.

**Comment by ChrisFeldmeier** [comment]
perfect, thanks!
