### ISSUE TITLE
Elassandra 6.2.3.21: org.apache.cassandra.exceptions.WriteTimeoutException: Operation timed out - received only 0 responses.

### ISSUE THREAD

**Issue by Deliver88** [strapdata/elassandra#312]
Hello, 

I am a beginner in using Elassandra and used the elassandra version 6.2.3.21 and tried to perform the example from https://github.com/strapdata/elassandra : 

curl -XPUT 'http://10.10.10.126:9200/twitter/_doc/1?pretty' -H 'Content-Type: application/json' -d '{
    "user": "Poulpy",
    "post_date": "2017-10-04T13:12:00Z",
    "message": "Elassandra adds dynamic mapping to Cassandra"
}'

Unfortunately, I got after ca. 30 sec. the following error:

curl -XPUT 'http://10.10.10.126:9200/twitter/_doc/1?pretty' -H 'Content-Type: application/json' -d '{
     "user": "Poulpy",
    "post_date": "2017-10-04T13:12:00Z",
    "message": "Elassandra adds dynamic mapping to Cassandra"
}
{
  "error" : {
    "root_cause" : [
      {
        "type" : "paxos_meta_data_update_exception",
        "reason" : "org.apache.cassandra.exceptions.WriteTimeoutException: Operation timed out - received only 0 responses."
      }
    ],
    "type" : "exception",
    "reason" : "PaxosMetaDataUpdateException[org.apache.cassandra.exceptions.WriteTimeoutException: Operation timed out - received only 0 responses.]; nested: WriteTimeoutException[Operation timed out - received only 0 responses.];",
    "caused_by" : {
      "type" : "paxos_meta_data_update_exception",
      "reason" : "org.apache.cassandra.exceptions.WriteTimeoutException: Operation timed out - received only 0 responses.",
      "caused_by" : {
        "type" : "write_timeout_exception",
        "reason" : "Operation timed out - received only 0 responses."
      }
    }
  },
  "status" : 500
}

In cassandra.yaml the listen address, broadcast address and rcp address are setting to the local ip. The nodetool status detect all nodes and they are able to "see" each othe, as can be seen below:

Datacenter: DC1
===============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load       Tokens       Owns    Host ID                               Rack
UN  10.10.10.124  371.07 KiB  256          ?       8a1dee56-1b5c-45ce-8699-b2ea198e3344  r1
UN  10.10.10.127  261.03 KiB  256          ?       309636f9-6a37-401c-b1b8-fad11aa41da9  r1
UN  10.10.10.126  205.61 KiB  256          ?       fd084e16-ab87-481e-8f45-cc3be58aac45  r1

**The Elassandra node (seed node in cassandra.yaml) on which I performad the curl shown above shows this error:**

2019-11-20 13:50:22,291 WARN  [elasticsearch[10.10.10.126][masterService#updateTask][T#1]] org.elasticsearch.cluster.service.ClusterService.processWriteConditional(ClusterService.java:576) PAXOS write timeout query=UPDATE "elastic_admin"."metadata_log" SET owner = ?, version = ?, source= ?, ts = dateOf(now()) WHERE cluster_name= ? AND v = ? IF version = ? values=[fd084e16-ab87-481e-8f45-cc3be58aac45, 1, create-index [twitter], cause [auto(bulk api)], Test Cluster, 1, 0]. Check your cluster load or increase the cas_contention_timeout_in_ms.
org.apache.cassandra.exceptions.WriteTimeoutException: Operation timed out - received only 0 responses.
        at org.apache.cassandra.service.paxos.AbstractPaxosCallback.await(AbstractPaxosCallback.java:64)
        at org.apache.cassandra.service.StorageProxy.preparePaxos(StorageProxy.java:489)
        at org.apache.cassandra.service.StorageProxy.beginAndRepairPaxos(StorageProxy.java:402)
        at org.apache.cassandra.service.StorageProxy.cas(StorageProxy.java:237)
        at org.apache.cassandra.cql3.statements.ModificationStatement.executeWithCondition(ModificationStatement.java:449)
        at org.apache.cassandra.cql3.statements.ModificationStatement.execute(ModificationStatement.java:424)
        at org.apache.cassandra.cql3.QueryProcessor.processStatement(QueryProcessor.java:225)
        at org.apache.cassandra.cql3.QueryProcessor.process(QueryProcessor.java:256)
        at org.apache.cassandra.cql3.QueryProcessor.process(QueryProcessor.java:241)
        at org.elasticsearch.cluster.service.ClusterService.process(ClusterService.java:552)
        at org.elasticsearch.cluster.service.ClusterService.processWriteConditional(ClusterService.java:564)
        at org.elasticsearch.cluster.service.ClusterService.commitMetaData(ClusterService.java:1284)
        at org.elassandra.discovery.CassandraDiscovery.publishAsCoordinator(CassandraDiscovery.java:1004)
        at org.elassandra.discovery.CassandraDiscovery.publish(CassandraDiscovery.java:953)
        at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:251)
        at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:152)
        at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
        at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:573)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-11-20 13:50:22,292 WARN  [elasticsearch[10.10.10.126][masterService#updateTask][T#1]] org.elassandra.discovery.CassandraDiscovery.publishAsCoordinator(CassandraDiscovery.java:1090) PAXOS write timeout, source=create-index [twitter], cause [auto(bulk api)] metadata=fd084e16-ab87-481e-8f45-cc3be58aac45/1 writeType=CAS, reading the owner of version=1
2019-11-20 13:50:42,301 ERROR [elasticsearch[10.10.10.126][masterService#updateTask][T#1]] org.elasticsearch.cluster.service.ClusterService.readMetaDataOwner(ClusterService.java:1330) Failed to read metadata owner for version=10 after 10 attempts
2019-11-20 13:50:42,301 WARN  [elasticsearch[10.10.10.126][masterService#updateTask][T#1]] org.elassandra.discovery.CassandraDiscovery.publishAsCoordinator(CassandraDiscovery.java:1096) PAXOS timeout and failed to write version=1, owner=null
2019-11-20 13:50:42,301 WARN  [elasticsearch[10.10.10.126][masterService#updateTask][T#1]] org.elassandra.discovery.CassandraDiscovery.publish(CassandraDiscovery.java:967) failed to execute cluster state update in 22s, state:
version [9], source [create-index [twitter], cause [auto(bulk api)]]

org.elassandra.PaxosMetaDataUpdateException: org.apache.cassandra.exceptions.WriteTimeoutException: Operation timed out - received only 0 responses.
        at org.elassandra.discovery.CassandraDiscovery.publishAsCoordinator(CassandraDiscovery.java:1097)
        at org.elassandra.discovery.CassandraDiscovery.publish(CassandraDiscovery.java:953)
        at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:251)
        at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:152)
        at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
        at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:573)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.cassandra.exceptions.WriteTimeoutException: Operation timed out - received only 0 responses.
        at org.apache.cassandra.service.paxos.AbstractPaxosCallback.await(AbstractPaxosCallback.java:64)
        at org.apache.cassandra.service.StorageProxy.preparePaxos(StorageProxy.java:489)
        at org.apache.cassandra.service.StorageProxy.beginAndRepairPaxos(StorageProxy.java:402)
        at org.apache.cassandra.service.StorageProxy.cas(StorageProxy.java:237)
        at org.apache.cassandra.cql3.statements.ModificationStatement.executeWithCondition(ModificationStatement.java:449)
        at org.apache.cassandra.cql3.statements.ModificationStatement.execute(ModificationStatement.java:424)
        at org.apache.cassandra.cql3.QueryProcessor.processStatement(QueryProcessor.java:225)
        at org.apache.cassandra.cql3.QueryProcessor.process(QueryProcessor.java:256)
        at org.apache.cassandra.cql3.QueryProcessor.process(QueryProcessor.java:241)
        at org.elasticsearch.cluster.service.ClusterService.process(ClusterService.java:552)
        at org.elasticsearch.cluster.service.ClusterService.processWriteConditional(ClusterService.java:564)
        at org.elasticsearch.cluster.service.ClusterService.commitMetaData(ClusterService.java:1284)
        at org.elassandra.discovery.CassandraDiscovery.publishAsCoordinator(CassandraDiscovery.java:1004)
        ... 11 common frames omitted
2019-11-20 13:50:42,302 WARN  [elasticsearch[10.10.10.126][masterService#updateTask][T#1]] org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:282) failed to publish updated cluster state in [22s]:
version [13], uuid [TbtBBvAdQ0-z2ovPxmb1pg], source [create-index [twitter], cause [auto(bulk api)]]
cluster uuid: fd084e16-ab87-481e-8f45-cc3be58aac45
version: 13
state uuid: TbtBBvAdQ0-z2ovPxmb1pg
from_diff: false
meta data version: 0
   [twitter/xkJAErGYSSuYeJQkiO3_9Q]: v[1]
      0: p_term [0], isa_ids []
      1: p_term [0], isa_ids []
      2: p_term [0], isa_ids []
nodes:
   {10.10.10.126}{fd084e16-ab87-481e-8f45-cc3be58aac45}{fd084e16-ab87-481e-8f45-cc3be58aac45}{10.10.10.126}{10.10.10.126:9300}{ALIVE}{rack=r1, dc=DC1}, local, master
   {10.10.10.127}{309636f9-6a37-401c-b1b8-fad11aa41da9}{309636f9-6a37-401c-b1b8-fad11aa41da9}{10.10.10.127}{10.10.10.127:9300}{ALIVE}{rack=r1, dc=DC1}
   {10.10.10.124}{8a1dee56-1b5c-45ce-8699-b2ea198e3344}{8a1dee56-1b5c-45ce-8699-b2ea198e3344}{10.10.10.124}{10.10.10.124:9300}{ALIVE}{rack=r1, dc=DC1}
routing_table (version 8):
-- index [[twitter/xkJAErGYSSuYeJQkiO3_9Q]]
----shard_id [twitter][0][[(-9223372036854775808,9223372036854775807]]]
--------[twitter][0], node[fd084e16-ab87-481e-8f45-cc3be58aac45], [P], recovery_source[local shards recovery], s[INITIALIZING], a[id=dummy_alloc_id], unassigned_info[[reason=INDEX_CREATED], at[2019-11-20T13:44:40.788Z], delayed=false, allocation_status[no_attempt]]

routing_nodes:
-----node_id[fd084e16-ab87-481e-8f45-cc3be58aac45][V]
--------[twitter][0], node[fd084e16-ab87-481e-8f45-cc3be58aac45], [P], recovery_source[local shards recovery], s[INITIALIZING], a[id=dummy_alloc_id], unassigned_info[[reason=INDEX_CREATED], at[2019-11-20T13:44:40.788Z], delayed=false, allocation_status[no_attempt]]
-----node_id[8a1dee56-1b5c-45ce-8699-b2ea198e3344][V]
-----node_id[309636f9-6a37-401c-b1b8-fad11aa41da9][V]
---- unassigned
customs:
   snapshots: SnapshotsInProgress[]   restore: RestoreInProgress[]   snapshot_deletions: SnapshotDeletionsInProgress[]
org.elasticsearch.ElasticsearchException: PaxosMetaDataUpdateException[org.apache.cassandra.exceptions.WriteTimeoutException: Operation timed out - received only 0 responses.]; nested: WriteTimeoutException[Operation timed out - received only 0 responses.];
        at org.elassandra.discovery.CassandraDiscovery.publish(CassandraDiscovery.java:968)
        at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:251)
        at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:152)
        at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
        at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:573)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.elassandra.PaxosMetaDataUpdateException: org.apache.cassandra.exceptions.WriteTimeoutException: Operation timed out - received only 0 responses.
        at org.elassandra.discovery.CassandraDiscovery.publishAsCoordinator(CassandraDiscovery.java:1097)
        at org.elassandra.discovery.CassandraDiscovery.publish(CassandraDiscovery.java:953)
        ... 10 common frames omitted
Caused by: org.apache.cassandra.exceptions.WriteTimeoutException: Operation timed out - received only 0 responses.
        at org.apache.cassandra.service.paxos.AbstractPaxosCallback.await(AbstractPaxosCallback.java:64)
        at org.apache.cassandra.service.StorageProxy.preparePaxos(StorageProxy.java:489)
        at org.apache.cassandra.service.StorageProxy.beginAndRepairPaxos(StorageProxy.java:402)
        at org.apache.cassandra.service.StorageProxy.cas(StorageProxy.java:237)
        at org.apache.cassandra.cql3.statements.ModificationStatement.executeWithCondition(ModificationStatement.java:449)
        at org.apache.cassandra.cql3.statements.ModificationStatement.execute(ModificationStatement.java:424)
        at org.apache.cassandra.cql3.QueryProcessor.processStatement(QueryProcessor.java:225)
        at org.apache.cassandra.cql3.QueryProcessor.process(QueryProcessor.java:256)
        at org.apache.cassandra.cql3.QueryProcessor.process(QueryProcessor.java:241)
        at org.elasticsearch.cluster.service.ClusterService.process(ClusterService.java:552)
        at org.elasticsearch.cluster.service.ClusterService.processWriteConditional(ClusterService.java:564)
        at org.elasticsearch.cluster.service.ClusterService.commitMetaData(ClusterService.java:1284)
        at org.elassandra.discovery.CassandraDiscovery.publishAsCoordinator(CassandraDiscovery.java:1004)
        ... 11 common frames omitted
2019-11-20 13:50:42,302 WARN  [elasticsearch[10.10.10.126][masterService#updateTask][T#1]] org.elasticsearch.rest.BytesRestResponse.build(BytesRestResponse.java:133) path: /twitter/_doc/1, params: {pretty=, index=twitter, id=1, type=_doc}
org.elasticsearch.ElasticsearchException: PaxosMetaDataUpdateException[org.apache.cassandra.exceptions.WriteTimeoutException: Operation timed out - received only 0 responses.]; nested: WriteTimeoutException[Operation timed out - received only 0 responses.];
        at org.elassandra.discovery.CassandraDiscovery.publish(CassandraDiscovery.java:968)
        at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:251)
        at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:152)
        at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
        at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:573)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.elassandra.PaxosMetaDataUpdateException: org.apache.cassandra.exceptions.WriteTimeoutException: Operation timed out - received only 0 responses.
        at org.elassandra.discovery.CassandraDiscovery.publishAsCoordinator(CassandraDiscovery.java:1097)
        at org.elassandra.discovery.CassandraDiscovery.publish(CassandraDiscovery.java:953)
        ... 10 common frames omitted
Caused by: org.apache.cassandra.exceptions.WriteTimeoutException: Operation timed out - received only 0 responses.
        at org.apache.cassandra.service.paxos.AbstractPaxosCallback.await(AbstractPaxosCallback.java:64)
        at org.apache.cassandra.service.StorageProxy.preparePaxos(StorageProxy.java:489)
        at org.apache.cassandra.service.StorageProxy.beginAndRepairPaxos(StorageProxy.java:402)
        at org.apache.cassandra.service.StorageProxy.cas(StorageProxy.java:237)
        at org.apache.cassandra.cql3.statements.ModificationStatement.executeWithCondition(ModificationStatement.java:449)
        at org.apache.cassandra.cql3.statements.ModificationStatement.execute(ModificationStatement.java:424)
        at org.apache.cassandra.cql3.QueryProcessor.processStatement(QueryProcessor.java:225)
        at org.apache.cassandra.cql3.QueryProcessor.process(QueryProcessor.java:256)
        at org.apache.cassandra.cql3.QueryProcessor.process(QueryProcessor.java:241)
        at org.elasticsearch.cluster.service.ClusterService.process(ClusterService.java:552)
        at org.elasticsearch.cluster.service.ClusterService.processWriteConditional(ClusterService.java:564)
        at org.elasticsearch.cluster.service.ClusterService.commitMetaData(ClusterService.java:1284)
        at org.elassandra.discovery.CassandraDiscovery.publishAsCoordinator(CassandraDiscovery.java:1004)
        ... 11 common frames omitted

**I got this warning too:**
` WARN  [main] org.elasticsearch.cluster.service.ClusterService.createOrUpdateElasticAdminKeyspace(ClusterService.java:1240) Keyspace [elastic_admin] replication factor DC1=1, you should increase this replication factor to avoid possible issue if quorum cannot be reach to update the elasticsearch mapping.` 

How can I increase this? There:

cqlsh> select * FROM elastic_admin.metadata_log  ;

 cluster_name | v | version | owner | source | ts
--------------+---+---------+-------+--------+----

(0 rows)

**Cluster state provides:**

{
  "cluster_name" : "Test Cluster",
  "compressed_size_in_bytes" : 302,
  "version" : 5,
  "state_uuid" : "ebBHqn_uSrKvsdBhvUXSrA",
  "master_node" : "fd084e16-ab87-481e-8f45-cc3be58aac45",
  "blocks" : { },
  "nodes" : {
    "309636f9-6a37-401c-b1b8-fad11aa41da9" : {
      "name" : "10.10.10.127",
      "status" : "ALIVE",
      "ephemeral_id" : "309636f9-6a37-401c-b1b8-fad11aa41da9",
      "transport_address" : "10.10.10.127:9300",
      "attributes" : {
        "rack" : "r1",
        "dc" : "DC1"
      }
    },
    "8a1dee56-1b5c-45ce-8699-b2ea198e3344" : {
      "name" : "10.10.10.124",
      "status" : "ALIVE",
      "ephemeral_id" : "8a1dee56-1b5c-45ce-8699-b2ea198e3344",
      "transport_address" : "10.10.10.124:9300",
      "attributes" : {
        "rack" : "r1",
        "dc" : "DC1"
      }
    },
    "fd084e16-ab87-481e-8f45-cc3be58aac45" : {
      "name" : "10.10.10.126",
      "status" : "ALIVE",
      "ephemeral_id" : "fd084e16-ab87-481e-8f45-cc3be58aac45",
      "transport_address" : "10.10.10.126:9300",
      "attributes" : {
        "rack" : "r1",
        "dc" : "DC1"
      }
    }
  },
  "metadata" : {
    "version" : 0,
    "cluster_uuid" : "fd084e16-ab87-481e-8f45-cc3be58aac45",
    "templates" : { },
    "indices" : { },
    "index-graveyard" : {
      "tombstones" : [ ]
    }
  },
  "routing_table" : {
    "indices" : { }
  },
  "routing_nodes" : {
    "unassigned" : [ ],
    "nodes" : {
      "fd084e16-ab87-481e-8f45-cc3be58aac45" : [ ],
      "8a1dee56-1b5c-45ce-8699-b2ea198e3344" : [ ],
      "309636f9-6a37-401c-b1b8-fad11aa41da9" : [ ]
    }
  },
  "snapshots" : {
    "snapshots" : [ ]
  },
  "restore" : {
    "snapshots" : [ ]
  },
  "snapshot_deletions" : {
    "snapshot_deletions" : [ ]
  }
}
'

**nodetool describecluster:**

`Cluster Information:
        Name: Test Cluster
        Snitch: org.apache.cassandra.locator.GossipingPropertyFileSnitch
        DynamicEndPointSnitch: enabled
        Partitioner: org.apache.cassandra.dht.Murmur3Partitioner
        Schema versions:
                0ed1a5c2-4bb5-3388-980b-003fb0fa787e: [10.10.10.124, 10.10.10.127]

                48dad6bc-7ddd-33d9-bb12-16d0c19377c0: [10.10.10.126]`

**Nodetool gossipinfo:**

/10.10.10.124
  generation:1574257459
  heartbeat:1004
  STATUS:16:NORMAL,-1054584241857477271
  LOAD:957:379971.0
  SCHEMA:12:0ed1a5c2-4bb5-3388-980b-003fb0fa787e
  DC:8:DC1
  RACK:10:r1
  RELEASE_VERSION:4:3.11.4.3
  INTERNAL_IP:6:10.10.10.124
  RPC_ADDRESS:3:10.10.10.124
  NET_VERSION:1:11
  HOST_ID:2:8a1dee56-1b5c-45ce-8699-b2ea198e3344
  RPC_READY:28:true
  X1:30:{}
  X2:32:8a1dee56-1b5c-45ce-8699-b2ea198e3344/0
  TOKENS:15:<hidden>
/10.10.10.127
  generation:1574257377
  heartbeat:1091
  STATUS:16:NORMAL,-1155830131360624957
  LOAD:1081:267299.0
  SCHEMA:12:0ed1a5c2-4bb5-3388-980b-003fb0fa787e
  DC:8:DC1
  RACK:10:r1
  RELEASE_VERSION:4:3.11.4.3
  INTERNAL_IP:6:10.10.10.127
  RPC_ADDRESS:3:10.10.10.127
  NET_VERSION:1:11
  HOST_ID:2:309636f9-6a37-401c-b1b8-fad11aa41da9
  RPC_READY:28:true
  X1:30:{}
  X2:32:309636f9-6a37-401c-b1b8-fad11aa41da9/0
  TOKENS:15:<hidden>
/10.10.10.126
  generation:1574257882
  heartbeat:578
  STATUS:16:NORMAL,-1006563523643784887
  LOAD:533:210549.0
  SCHEMA:29:48dad6bc-7ddd-33d9-bb12-16d0c19377c0
  DC:8:DC1
  RACK:10:r1
  RELEASE_VERSION:4:3.11.4.3
  INTERNAL_IP:6:10.10.10.126
  RPC_ADDRESS:3:10.10.10.126
  NET_VERSION:1:11
  HOST_ID:2:fd084e16-ab87-481e-8f45-cc3be58aac45
  RPC_READY:40:true
  X1:42:{}
  X2:44:fd084e16-ab87-481e-8f45-cc3be58aac45/0
  TOKENS:15:<hidden>

**And java version:**

java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)

**The errors above are sometimes not shown and I get follows error:**

2019-11-21 13:43:46,932 WARN  [elasticsearch[10.10.10.126][masterService#updateTask][T#1]] org.elasticsearch.cluster.service.ClusterService.commitMetaData(ClusterService.java:1301) PAXOS Failed to update metadata source=create-index [twitter], cause [api] prevMetadata=fd084e16-ab87-481e-8f45-cc3be58aac45/0 nextMetaData=fd084e16-ab87-481e-8f45-cc3be58aac45/1
2019-11-21 13:43:46,933 WARN  [elasticsearch[10.10.10.126][masterService#updateTask][T#1]] org.elassandra.discovery.CassandraDiscovery.publishAsCoordinator(CassandraDiscovery.java:1079) PAXOS concurrent update, source=create-index [twitter], cause [api] metadata=fd084e16-ab87-481e-8f45-cc3be58aac45/1, resubmit task on next metadata change

Thanks a lot!

**Comment by leleueri** [comment]
Hello,

I have just tried the README example using a 3 node cluster (on my local machine using aliases on the 'lo' interface ). Everything is ok for me (See output here after), Did you copy/past the exemple on a fresh installed cluster without data on it?
 
You may have this issue when you create an index on an existing cassandra table containing a map with some entries. In this specific case, you have to create the index first using __opaque_map__ (https://elassandra.readthedocs.io/en/latest/mapping.html#dynamic-mapping-of-cassandra-map)

About the replication_factor, to alter the number of replicas you have to alter the keyspace.
(http://cassandra.apache.org/doc/latest/cql/ddl.html#alter-keyspace) 

Regards,
Eric


```
./bin/nodetool status
Datacenter: DC1
===============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens       Owns (effective)  Host ID                               Rack
UN  127.0.0.1  91,24 KiB  8            28.5%             b21b75a1-6347-4692-b515-bbe5bcc94f6e  r1
UN  127.0.0.2  114,9 KiB  8            20.8%             dbaed19e-7af5-4d46-b105-a424da702122  r1
UN  127.0.0.3  168,26 KiB  8            50.6%             0e84ea73-67f8-4a2b-8221-9d458e223dee  r1


curl -XGET localhost:9200/_cluster/state?pretty
{
  "cluster_name" : "Test Cluster",
  "compressed_size_in_bytes" : 296,
  "version" : 9,
  "state_uuid" : "EwcaAMtBRsigI3Fi68triQ",
  "master_node" : "b21b75a1-6347-4692-b515-bbe5bcc94f6e",
  "blocks" : { },
  "nodes" : {
    "0e84ea73-67f8-4a2b-8221-9d458e223dee" : {
      "name" : "127.0.0.3",
      "status" : "ALIVE",
      "ephemeral_id" : "0e84ea73-67f8-4a2b-8221-9d458e223dee",
      "transport_address" : "127.0.0.3:9300",
      "attributes" : {
        "rack" : "r1",
        "dc" : "DC1"
      }
    },
    "dbaed19e-7af5-4d46-b105-a424da702122" : {
      "name" : "127.0.0.2",
      "status" : "ALIVE",
      "ephemeral_id" : "dbaed19e-7af5-4d46-b105-a424da702122",
      "transport_address" : "127.0.0.2:9300",
      "attributes" : {
        "rack" : "r1",
        "dc" : "DC1"
      }
    },
    "b21b75a1-6347-4692-b515-bbe5bcc94f6e" : {
      "name" : "127.0.0.1",
      "status" : "ALIVE",
      "ephemeral_id" : "b21b75a1-6347-4692-b515-bbe5bcc94f6e",
      "transport_address" : "127.0.0.1:9300",
      "attributes" : {
        "rack" : "r1",
        "dc" : "DC1"
      }
    }
  },
  "metadata" : {
    "version" : 0,
    "cluster_uuid" : "b21b75a1-6347-4692-b515-bbe5bcc94f6e",
    "templates" : { },
    "indices" : { },
    "index-graveyard" : {
      "tombstones" : [ ]
    }
  },
  "routing_table" : {
    "indices" : { }
  },
  "routing_nodes" : {
    "unassigned" : [ ],
    "nodes" : {
      "dbaed19e-7af5-4d46-b105-a424da702122" : [ ],
      "0e84ea73-67f8-4a2b-8221-9d458e223dee" : [ ],
      "b21b75a1-6347-4692-b515-bbe5bcc94f6e" : [ ]
    }
  },
  "restore" : {
    "snapshots" : [ ]
  },
  "snapshot_deletions" : {
    "snapshot_deletions" : [ ]
  },
  "snapshots" : {
    "snapshots" : [ ]
  }
}



curl -XPUT 'http://localhost:9200/twitter/_doc/1?pretty' -H 'Content-Type: application/json' -d '{
>     "user": "Poulpy",
>     "post_date": "2017-10-04T13:12:00Z",
>     "message": "Elassandra adds dynamic mapping to Cassandra"
> }'
{
  "_index" : "twitter",
  "_type" : "_doc",
  "_id" : "1",
  "_version" : 1,
  "result" : "created",
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  }
}
```
