### ISSUE TITLE
Can elassandra be used as a storage engine for skywalking

### ISSUE THREAD

**Issue by huangkaiyan10** [strapdata/elassandra#316]
I wanted to use elassandra's elasticsearch feature on this project and integrate skywalking link tracking to discover this problem.I used the skywalking version is apache-skywalking-apm-6.5.0.

Below is the error log

2019-12-26 16:38:15,547 - org.apache.skywalking.oap.server.starter.OAPServerStartUp - 55 [main] ERROR [] - Elasticsearch exception [type=invalid_request_exception, reason=Keyspace names shouldn't be more than 48 characters long (got "instance_clr_available_completion_port_threads_hour_20191226")]
org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=invalid_request_exception, reason=Keyspace names shouldn't be more than 48 characters long (got "instance_clr_available_completion_port_threads_hour_20191226")]
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:653) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:628) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:535) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:508) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
	at org.elasticsearch.client.IndicesClient.create(IndicesClient.java:99) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
	at org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient.createIndex(ElasticSearchClient.java:168) ~[library-client-6.5.0.jar:6.5.0]
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.StorageEsInstaller.createTable(StorageEsInstaller.java:82) ~[storage-elasticsearch-plugin-6.5.0.jar:6.5.0]
	at org.apache.skywalking.oap.server.core.storage.model.ModelInstaller.install(ModelInstaller.java:61) ~[server-core-6.5.0.jar:6.5.0]
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider.start(StorageModuleElasticsearchProvider.java:136) ~[storage-elasticsearch-plugin-6.5.0.jar:6.5.0]
	at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:61) ~[library-module-6.5.0.jar:6.5.0]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:67) ~[library-module-6.5.0.jar:6.5.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:43) [server-starter-6.5.0.jar:6.5.0]

**Comment by vroyer** [comment]
Yes, this is an Elassandra limitation (documented in the limitations section).
Cassandra keyspace names are limited to 48 characters, and so Elasticsearch index names are also limited to 48 characters.
You should shorten your index name.
Thanks.

**Comment by huangkaiyan10** [comment]
Can  solve the problem by setting Cassandra?Because I can't change the skywalking source

**Comment by vroyer** [comment]
We add a system property to increase that in Cassandra, this will be available next week in the next release.
Please let us know if you succeed to run sky walking.
Thanks.

**Comment by huangkaiyan10** [comment]
thanks.  property name is what?I expect next release

**Comment by vroyer** [comment]
Cassandra property to enlarge key space/table name is “cassandra.max_name_length”

**Comment by vroyer** [comment]
The last release 6.2.3.23 (and 6.8.4.0) can now support longer index names by setting the system property cassandra.max_name_length=64 for example (default cassandra length is 48).
Please let me know if this works with skywalking.
Thanks.

**Comment by vroyer** [comment]
Thank's for your feedback !
