### ISSUE TITLE
Elassandra mappings with type coercing aren't behaving the same as elasticsearch

### ISSUE THREAD

**Issue by epsniff** [strapdata/elassandra#323]
**Elassandra version**: 6.8.4.0
**JVM version** (`java -version`): docker image
**OS version** (`uname -a` if on a Unix-like system): host system is OSx but I also tested it in GKE.

**Description of the problem including expected versus actual behavior**:
When using a mapping template, that enables type coercing, Elassandra doesn't behave the same as ElasticSearch.  Instead it returns a 500 and an exception. 

**Steps to reproduce**:

In both of these examples we'll be inserting a document that has an integer mapping.  And in both cases the int field's value will be submitted as a string value.  

#### Testing Elasticsearch 6.8
```
docker pull docker.elastic.co/elasticsearch/elasticsearch:6.8.6
docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:6.8.6
export HOST=localhost
export INDEX=ents_type_site1
echo '{
  "index_patterns": "ents_*",
  "mappings": {
    "_doc": {
      "properties": {
        "_created": {
          "type": "date"
        }
      },
      "dynamic_templates": [
        {
          "integer_fields": {
            "match": "int_*",
            "mapping": {
              "coerce": true,
              "type": "long"
            }
          }
        }
      ]
    }
  }
}' | http PUT http://$HOST:9200/_template/ent_table_template
{
    "acknowledged": true
}

echo '{"int__eventcnt":"1"}' |   http POST http://$HOST:9200/$INDEX/_doc/a1bc=:1cd==
{
    "_id": "a1bc=:1cd==",
    "_index": "ents_type_site1",
    "_primary_term": 1,
    "_seq_no": 0,
    "_shards": {
        "failed": 0,
        "successful": 1,
        "total": 2
    },
    "_type": "_doc",
    "_version": 1,
    "result": "created"
}
```
* Note that elasticsearch handled the casting of the string to an int. 

#### Testing elassandra 6.8

```
docker run  -p 9200:9200 -p 9300:9300 --name node0 -d strapdata/elassandra:6.8.4.0  
export INDEX=ents_type_site1
echo '{
  "index_patterns": "ents_*",
  "mappings": {
    "_doc": {
      "properties": {
        "_created": {
          "type": "date"
        }
      },
      "dynamic_templates": [
        {
          "integer_fields": {
            "match": "int_*",
            "mapping": {
              "coerce": true,
              "type": "long"
            }
          }
        }
      ]
    }
  }
}' | http PUT http://$HOST:9200/_template/ent_table_template
{
    "acknowledged": true
}

echo '{"int__eventcnt":"1"}' |   http POST http://$HOST:9200/$INDEX/_doc/a1bc=:1cd==
{
    "error": {
        "reason": "java.lang.String cannot be cast to java.lang.Number",
        "root_cause": [
            {
                "reason": "[172.17.0.2][172.17.0.2:9300][indices:data/write/bulk[s][p]]",
                "type": "remote_transport_exception"
            }
        ],
        "type": "class_cast_exception"
    },
    "status": 500
}
```

**Please provide the following information**:

* elassandra logs (logs/system.logs or /var/lib/cassandra/system.log)
```
2020-01-10 06:01:40,015 WARN  [elasticsearch[172.17.0.2][http_server_worker][T#2]] org.elasticsearch.common.logging.DeprecationLogger.deprecated(DeprecationLogger.java:242) [types removal] The parameter include_type_name should be explicitly specified in put template requests to prepare for 7.0. In 7.0 include_type_name will default to 'false', and requests are expected to omit the type name in mapping definitions.
2020-01-10 06:01:42,691 INFO  [elasticsearch[172.17.0.2][generic][T#3]] org.elassandra.shard.CassandraShardStateListener.afterIndexShardStarted(CassandraShardStateListener.java:69) shard [ents_type_site1][0] started
2020-01-10 06:01:42,994 ERROR [elasticsearch[172.17.0.2][write][T#1]] org.elassandra.cluster.QueryManager.upsertDocument(QueryManager.java:842) [java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number].[ents_type_site1] failed to parse field _doc=int__eventcnt
2020-01-10 06:01:43,011 WARN  [elasticsearch[172.17.0.2][write][T#1]] org.elasticsearch.rest.BytesRestResponse.build(BytesRestResponse.java:133) path: /ents_type_site1/_doc/a1bc=:1cd==, params: {index=ents_type_site1, id=a1bc=:1cd==, type=_doc}
org.elasticsearch.transport.RemoteTransportException: [172.17.0.2][172.17.0.2:9300][indices:data/write/bulk[s][p]]
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
        at org.elasticsearch.index.mapper.NumberFieldMapper$NumberType$7.cqlValue(NumberFieldMapper.java:870)
        at org.elasticsearch.index.mapper.NumberFieldMapper$NumberFieldType.cqlValue(NumberFieldMapper.java:1057)
        at org.elasticsearch.index.mapper.MappedFieldType.cqlValue(MappedFieldType.java:423)
        at org.elassandra.cluster.Serializer.serialize(Serializer.java:230)
        at org.elassandra.cluster.Serializer.serialize(Serializer.java:223)
        at org.elassandra.cluster.QueryManager.upsertDocument(QueryManager.java:840)
        at org.elassandra.cluster.QueryManager.insertDocument(QueryManager.java:694)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.lambda$executeIndexRequestOnPrimary$3(TransportShardBulkAction.java:468)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.executeOnPrimaryWhileHandlingMappingUpdates(TransportShardBulkAction.java:495)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.executeIndexRequestOnPrimary(TransportShardBulkAction.java:464)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:226)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:169)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:160)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:146)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:83)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:1088)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:1066)
        at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:105)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.runWithPrimaryShardReference(TransportReplicationAction.java:445)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:387)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:327)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:314)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66)
        at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:696)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:751)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
* elasticsearch cluster state (curl http://localhost:9200/_cluster/state)
* cassandra schema (cqlsh>DESC KEYSPACE <your_keyspace>)
* cassandra gossip state (run: nodetool gossipinfo)

**Comment by vroyer** [comment]
Elassandra is not Elasticsearch, so don't force the discovery to single-node and follow the [Elassandra quick-start guide ](http://doc.elassandra.io/en/latest/quickstart.html).

**Comment by epsniff** [comment]
@vroyer what?  This has nothing to do with discovery...  This about index mappings and string coercing, i.e. Elassandra can't handle coercing the term "100" into 100. 

See: 
```
"reason": "java.lang.String cannot be cast to java.lang.Number",
```

**Comment by epsniff** [comment]
I only used docker in the reproduction steps to keep things simple.  And the same exception happens when you use the _bulk api.  

For our evaluation we are testing Elassandra in Kubernetes, which I setup using Google's Application Market place.   

The reason we use coercing is that when converting int64's to float64's for JSON, some precision is lose.  So, for large numbers we marshal the int64 as strings, and then let Elasticsearch coerce them back into number types.

**Comment by epsniff** [comment]
@vroyer I think I figured out your confusion.  In the reproduction steps I had steps for starting up both an ElasticSearch node and steps for starting up a Elassandra node.  The command `"discovery.type=single-node"` was only used in the ElasticSearch example, please continue reading...  The important part is the results of inserting a single document into both ElasticSearch vs Elassandra.

**Comment by vroyer** [comment]
Sorry for closing the ticker, i thought you were trying to run elassandra with the single-node discovery.

Effectively, quoted numbers are not interpreted as number by elassandra, while it is properly interpreted by elasticsearch.  Without quotes, elassandra works fine:

put "$INDEX/_doc/a1bc=:1cd==?pretty" '{"int__eventcnt":1}'
{
  "_index" : "ents_type_site1",
  "_type" : "_doc",
  "_id" : "a1bc=:1cd==",
  "_version" : 1,
  "result" : "created",
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  }
}

We are going to fix that quickly. Thanks for reporting the issue.

**Comment by leleueri** [comment]
Hi,

The Elassandra 6.8.4.1 has just been released and fix your issue : 
```

:/# curl -X PUT -H "Content-Type: application/json" "http://localhost:9200/_template/ent_table_template" -d '{
>   "index_patterns": "ents_*",
>   "mappings": {
>     "_doc": {
>       "properties": {
>         "_created": {
>           "type": "date"
>         }
>       },
>       "dynamic_templates": [
>         {
>           "integer_fields": {
>             "match": "int_*",
>             "mapping": {
>               "coerce": true,
>               "type": "long"
>             }
>           }
>         }
>       ]
>     }
>   }
> }'

:/# curl -X POST  -H "Content-Type: application/json" "http://localhost:9200/ents_type_site1/_doc/a1bc=:1cd==" -d '{"int__eventcnt":"1"}' 
{"_index":"ents_type_site1","_type":"_doc","_id":"a1bc=:1cd==","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":1,"_primary_term":1}

:/# curl -X POST  -H "Content-Type: application/json" "http://localhost:9200/ents_type_site1/_search?pretty" 
{
  "took" : 60,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "ents_type_site1",
        "_type" : "_doc",
        "_id" : "a1bc=:1cd==",
        "_score" : 1.0,
        "_source" : {
          "int__eventcnt" : 1
        }
      }
    ]
  }
}

```

The docker image is available on DockerHub.

- strapdata/elassandra:6.8.4.1
- DIGEST:sha256:3370bb8e47932ec9f7fa0c40e04b39b65c971bafde910cfe9dec191273a00cd0
