### ISSUE TITLE
Creating a Frozen<List<Frozen<UDT>>> fails

### ISSUE THREAD

**Issue by dioptre** [strapdata/elassandra#327]
I'm using docker: strapdata/elassandra:6.8.4.0

As per:
https://github.com/sfproductlabs/msgxc/blob/53523fe804bde18cfc2ce1d8d77dea9337d38a6e/xcs/.setup/schema/cassandra/schema.1.cql#L243-L264

I create a type:
```
create type mxcdevice (
  mtype text,
  did text,
  updated timestamp
);
```

Then add this to a table:
```
alter table users add mdevices frozen<list<frozen<mxcdevice>>>; --prioritized list of devices
```

Then go to index it:
```
curl -w "\n" -k -H 'Content-Type: application/json'  -XPUT  "http://localhost:9200/mxcusers/" -d '{
    "settings" : { "keyspace" : "msgxc" },
    "mappings": {
        "users": {
            "properties" : {
                "uid": { "type": "keyword", "index": true, "cql_collection": "singleton" },
                "mtypes": { "type": "keyword", "index": true, "cql_collection": "list" },
                "mdevices": {    
                    "type": "nested",       
                    "cql_collection" : "list",
                    "cql_struct" : "map",             
                    "properties": {
                        "mtype":    { "type": "keyword", "index": false,  "cql_collection": "singleton" },
                        "did":      { "type": "keyword", "index": false,  "cql_collection": "singleton" },
                        "updated":  { "type": "date", "index": false, "cql_collection": "singleton" }
                    }
                }
                
            }
        }
    }
}'
```

No matter what I do, if I include mdevices (above) I get the following error **Not enough bytes to read 1th field did**:
```
cassandra    | 2020-01-21 12:28:44,386 INFO  [elasticsearch[172.20.0.3][generic][T#4]] org.elassandra.shard.CassandraShardStateListener.afterIndexShardStarted(CassandraShardStateListener.java:69) shard [mxcusers][0] started
cassandra    | 2020-01-21 12:28:44,454 ERROR [CompactionExecutor:1865] org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$RowcumentIndexer.finish(ElasticSecondaryIndex.java:1979) Unexpected error
cassandra    | org.apache.cassandra.serializers.MarshalException: Not enough bytes to read 1th field did
cassandra    | 	at org.apache.cassandra.serializers.UserTypeSerializer.validate(UserTypeSerializer.java:56)
cassandra    | 	at org.apache.cassandra.db.marshal.AbstractType.validate(AbstractType.java:162)
cassandra    | 	at org.apache.cassandra.cql3.UserTypes$Value.fromSerialized(UserTypes.java:166)
cassandra    | 	at org.elassandra.cluster.Serializer.deserialize(Serializer.java:265)
cassandra    | 	at org.elassandra.cluster.Serializer.deserialize(Serializer.java:258)
cassandra    | 	at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$RowcumentIndexer$Rowcument.readCellValue(ElasticSecondaryIndex.java:2115)
cassandra    | 	at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$SkinnyRowcumentIndexer$SkinnyRowcument.readCellValue(ElasticSecondaryIndex.java:1745)
cassandra    | 	at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$RowcumentIndexer$Rowcument.readCellValues(ElasticSecondaryIndex.java:2096)
cassandra    | 	at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$SkinnyRowcumentIndexer$SkinnyRowcument.readCellValues(ElasticSecondaryIndex.java:1745)
cassandra    | 	at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$RowcumentIndexer$Rowcument.<init>(ElasticSecondaryIndex.java:2083)
cassandra    | 	at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$SkinnyRowcumentIndexer$SkinnyRowcument.<init>(ElasticSecondaryIndex.java:1747)
cassandra    | 	at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$SkinnyRowcumentIndexer.update(ElasticSecondaryIndex.java:1785)
cassandra    | 	at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$RowcumentIndexer.finish(ElasticSecondaryIndex.java:1966)
cassandra    | 	at java.lang.Iterable.forEach(Iterable.java:75)
cassandra    | 	at org.apache.cassandra.index.SecondaryIndexManager.indexPartition(SecondaryIndexManager.java:1096)
cassandra    | 	at org.apache.cassandra.index.internal.CollatedViewIndexBuilder.build(CollatedViewIndexBuilder.java:139)
cassandra    | 	at org.apache.cassandra.db.compaction.CompactionManager$14.run(CompactionManager.java:1707)
cassandra    | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
cassandra    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
cassandra    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
cassandra    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
cassandra    | 	at org.apache.cassandra.concurrent.NamedThreadFactory.lambda$threadLocalDeallocator$0(NamedThreadFactory.java:84)
cassandra    | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
cassandra    | 	at java.lang.Thread.run(Thread.java:748)
```

Please help!

Is it even possible to have a list of a udt?

**Comment by vroyer** [comment]
Hi,


Could you try with the following CQL schema ?

alter table users add mdevices list<frozen<mxcdevice>>

**Comment by dioptre** [comment]
Fixed it thanks!
