### ISSUE TITLE
elassandra-6.2.3.13 works fine when installed as a separate cluster but stops working when added as a new DC to an existing apache-cassandra-3.11.3 cluster

### ISSUE THREAD

**Issue by rsr999** [strapdata/elassandra#336]
**Elassandra version**: 6.2.3.13

**Plugins installed**: []

**JVM version** (`java -version`): openjdk version "1.8.0_232"

**OS version** (`uname -a` if on a Unix-like system):  Linux 3.10.0-1062.9.1.el7.x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
Elassandra-6.2.3.13 works fine when installed as a separate cluster but the ElasticSearch part stops working when added as a new DC to an existing apache-cassandra-3.11.3 cluster.
The cassandra functionality works without any issues though.

We successfully installed an independent 3 nodes elassandra-6.2.3.13 cluster and were able to create elasticsearch indexes on tables without any issues.
But since we already have all our data in an existing Cassandra cluster so we tried to add the 3 elassandra nodes as a new DC to the existing Cassandra cluster (v3.11.3 , 5-nodes).
Although we are able to add the Ealssandra nodes as a new DC to the existing cassandra cluster and we are also able to stream all the data with "nodetool rebuild" to the elassandra nodes but after all this when we try to create an ElasticSearch index on any of the tables, it fails with the following errors:

Please note : redacting part of IP's for security reasons:

2020-04-02 18:25:06,978 WARN  [elasticsearch[xx.xx.xxx.224][masterService#updateTask][T#1]] CassandraDiscovery.java:891 publish failed to execute cluster state update in 2ms, state:
version [7], source [create-index [test], cause [api]]

java.lang.NullPointerException: null
        at org.elasticsearch.cluster.service.ClusterService.addMetadataMutations(ClusterService.java:730)
        at org.elasticsearch.cluster.service.ClusterService.writeMetadataToSchemaMutations(ClusterService.java:745)
        at org.elassandra.discovery.CassandraDiscovery.publishAsCoordinator(CassandraDiscovery.java:920)
        at org.elassandra.discovery.CassandraDiscovery.publish(CassandraDiscovery.java:878)
        at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:251)
        at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:152)
        at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
        at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:573)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-04-02 18:25:07,005 WARN  [elasticsearch[xx.xx.xxx.224][masterService#updateTask][T#1]] MasterService.java:282 runTasks failed to publish updated cluster state in [221ms]:
version [8], uuid [EnERPt9qS4mWvKjPCkGdqQ], source [create-index [test], cause [api]]
cluster uuid: caa8d34c-3eb7-425a-951a-b1c28346f4f6
version: 8
state uuid: EnERPt9qS4mWvKjPCkGdqQ
from_diff: false
meta data version: 0
   [test/BuaKdBVqSkeh8WtAO8rIzA]: v[1]
      0: p_term [0], isa_ids []
      1: p_term [0], isa_ids []
      2: p_term [0], isa_ids []
nodes:
   {xx.xx.xxx.171}{ebefaf04-06e2-4759-a9e2-36ae3de522c7}{ebefaf04-06e2-4759-a9e2-36ae3de522c7}{xx.xx.xxx.171}{xx.xx.xxx.171:9300}{ALIVE}{rack=2a, dc=us-west-prepops}
   {xx.xx.xxx.61}{3d8aa6e0-ca98-44ba-8905-e53f998ea068}{3d8aa6e0-ca98-44ba-8905-e53f998ea068}{xx.xx.xxx.61}{xx.xx.xxx.61:9300}{ALIVE}{rack=2a, dc=us-west-prepops}
   {xx.xx.xxx.224}{caa8d34c-3eb7-425a-951a-b1c28346f4f6}{caa8d34c-3eb7-425a-951a-b1c28346f4f6}{xx.xx.xxx.224}{xx.xx.xxx.224:9300}{ALIVE}{rack=2a, dc=us-west-prepops}, local, master
routing_table (version 2):
-- index [[test/BuaKdBVqSkeh8WtAO8rIzA]]
----shard_id [test][0][[(-9223372036854775808,9223372036854775807]]]
--------[test][0], node[caa8d34c-3eb7-425a-951a-b1c28346f4f6], [P], recovery_source[local shards recovery], s[INITIALIZING], a[id=dummy_alloc_id], unassigned_info[[reason=INDEX_CREATED], at[2020-04-02T22:25:06.962Z], delayed=false, allocation_status[no_attempt]]
--------[test][0], node[null], [R], recovery_source[peer recovery], s[UNASSIGNED], unassigned_info[[reason=ALLOCATION_FAILED], at[1970-01-01T00:00:00.000Z], failed_attempts[1], delayed=false, details[shard or keyspace unavailable], allocation_status[deciders_no]]
--------[test][0], node[null], [R], recovery_source[peer recovery], s[UNASSIGNED], unassigned_info[[reason=ALLOCATION_FAILED], at[1970-01-01T00:00:00.000Z], failed_attempts[1], delayed=false, details[shard or keyspace unavailable], allocation_status[deciders_no]]

routing_nodes:
-----node_id[ebefaf04-06e2-4759-a9e2-36ae3de522c7][V]
-----node_id[3d8aa6e0-ca98-44ba-8905-e53f998ea068][V]
-----node_id[caa8d34c-3eb7-425a-951a-b1c28346f4f6][V]
--------[test][0], node[caa8d34c-3eb7-425a-951a-b1c28346f4f6], [P], recovery_source[local shards recovery], s[INITIALIZING], a[id=dummy_alloc_id], unassigned_info[[reason=INDEX_CREATED], at[2020-04-02T22:25:06.962Z], delayed=false, allocation_status[no_attempt]]
---- unassigned
--------[test][0], node[null], [R], recovery_source[peer recovery], s[UNASSIGNED], unassigned_info[[reason=ALLOCATION_FAILED], at[1970-01-01T00:00:00.000Z], failed_attempts[1], delayed=false, details[shard or keyspace unavailable], allocation_status[deciders_no]]
--------[test][0], node[null], [R], recovery_source[peer recovery], s[UNASSIGNED], unassigned_info[[reason=ALLOCATION_FAILED], at[1970-01-01T00:00:00.000Z], failed_attempts[1], delayed=false, details[shard or keyspace unavailable], allocation_status[deciders_no]]
customs:
   restore: RestoreInProgress[]   snapshots: SnapshotsInProgress[]   snapshot_deletions: SnapshotDeletionsInProgress[]
org.elasticsearch.ElasticsearchException: java.lang.NullPointerException
        at org.elassandra.discovery.CassandraDiscovery.publish(CassandraDiscovery.java:892)
        at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:251)
        at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:152)
        at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
        at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:573)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
        at org.elasticsearch.cluster.service.ClusterService.addMetadataMutations(ClusterService.java:730)
        at org.elasticsearch.cluster.service.ClusterService.writeMetadataToSchemaMutations(ClusterService.java:745)
        at org.elassandra.discovery.CassandraDiscovery.publishAsCoordinator(CassandraDiscovery.java:920)
        at org.elassandra.discovery.CassandraDiscovery.publish(CassandraDiscovery.java:878)
        ... 10 common frames omitted
2020-04-02 18:25:07,009 WARN  [elasticsearch[xx.xx.xxx.224][masterService#updateTask][T#1]] BytesRestResponse.java:133 build path: /test, params: {index=test}
org.elasticsearch.ElasticsearchException: java.lang.NullPointerException
        at org.elassandra.discovery.CassandraDiscovery.publish(CassandraDiscovery.java:892)
        at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:251)
        at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:152)
        at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
        at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:573)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
        at org.elasticsearch.cluster.service.ClusterService.addMetadataMutations(ClusterService.java:730)
        at org.elasticsearch.cluster.service.ClusterService.writeMetadataToSchemaMutations(ClusterService.java:745)
        at org.elassandra.discovery.CassandraDiscovery.publishAsCoordinator(CassandraDiscovery.java:920)
        at org.elassandra.discovery.CassandraDiscovery.publish(CassandraDiscovery.java:878)
        ... 10 common frames omitted
2020-04-02 18:25:36,977 WARN  [elasticsearch[xx.xx.xxx.224][generic][T#3]] BytesRestResponse.java:133 build path: /test, params: {index=test}
java.lang.IllegalStateException: Channel is already closed
        at org.elasticsearch.rest.RestController$ResourceHandlingHttpChannel.close(RestController.java:497)
        at org.elasticsearch.rest.RestController$ResourceHandlingHttpChannel.sendResponse(RestController.java:490)
        at org.elasticsearch.rest.action.RestResponseListener.processResponse(RestResponseListener.java:37)
        at org.elasticsearch.rest.action.RestActionListener.onResponse(RestActionListener.java:47)
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:85)
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:81)
        at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$1.onResponse(TransportMasterNodeAction.java:150)
        at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$1.onResponse(TransportMasterNodeAction.java:147)
        at org.elasticsearch.action.admin.indices.create.TransportCreateIndexAction.lambda$masterOperation$0(TransportCreateIndexAction.java:82)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60)
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.lambda$createIndex$1(MetaDataCreateIndexService.java:225)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60)
        at org.elasticsearch.cluster.AckedClusterStateUpdateTask.onAckTimeout(AckedClusterStateUpdateTask.java:85)
        at org.elasticsearch.cluster.service.MasterService$SafeAckedClusterStateTaskListener.onAckTimeout(MasterService.java:569)
        at org.elasticsearch.cluster.service.MasterService$AckCountDownListener.onTimeout(MasterService.java:667)
        at org.elasticsearch.cluster.service.MasterService$AckCountDownListener.lambda$new$0(MasterService.java:635)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:573)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-04-02 18:25:36,978 ERROR [elasticsearch[xx.xx.243.224][generic][T#3]] RestActionListener.java:61 onFailure failed to send failure response
java.lang.IllegalStateException: Channel is already closed
        at org.elasticsearch.rest.RestController$ResourceHandlingHttpChannel.close(RestController.java:497)
        at org.elasticsearch.rest.RestController$ResourceHandlingHttpChannel.sendResponse(RestController.java:490)
        at org.elasticsearch.rest.action.RestActionListener.onFailure(RestActionListener.java:58)
        at org.elasticsearch.rest.action.RestActionListener.onResponse(RestActionListener.java:49)
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:85)
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:81)
        at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$1.onResponse(TransportMasterNodeAction.java:150)
        at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$1.onResponse(TransportMasterNodeAction.java:147)
        at org.elasticsearch.action.admin.indices.create.TransportCreateIndexAction.lambda$masterOperation$0(TransportCreateIndexAction.java:82)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60)
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.lambda$createIndex$1(MetaDataCreateIndexService.java:225)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60)
        at org.elasticsearch.cluster.AckedClusterStateUpdateTask.onAckTimeout(AckedClusterStateUpdateTask.java:85)
        at org.elasticsearch.cluster.service.MasterService$SafeAckedClusterStateTaskListener.onAckTimeout(MasterService.java:569)
        at org.elasticsearch.cluster.service.MasterService$AckCountDownListener.onTimeout(MasterService.java:667)
        at org.elasticsearch.cluster.service.MasterService$AckCountDownListener.lambda$new$0(MasterService.java:635)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:573)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        Suppressed: java.lang.IllegalStateException: Channel is already closed
                at org.elasticsearch.rest.RestController$ResourceHandlingHttpChannel.close(RestController.java:497)
                at org.elasticsearch.rest.RestController$ResourceHandlingHttpChannel.sendResponse(RestController.java:490)
                at org.elasticsearch.rest.action.RestResponseListener.processResponse(RestResponseListener.java:37)
                at org.elasticsearch.rest.action.RestActionListener.onResponse(RestActionListener.java:47)
                ... 16 common frames omitted

 
**Steps to reproduce**:

Please include a *minimal* but **complete** **recreation** of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Create a 3-5 node apache cassandra 3.11.3 claster using GossipingPropertyFileSnitch.
 2. Create some test tables in it with RF3.
 3. Add 3 new Elassandra 6.2.3.13 nodes as a new DC to the existing cassandra cluster with auto_bootstrap=false.
 4. Stream the data from the cassandra DC to the new elassandra DC using "nodetool rebuild DC_Name".
 5. Create an ElasticSearch Index of a table . (We are trying to use Postman to create the index)

**Please provide the following information**:

* elassandra logs (logs/system.logs or /var/lib/cassandra/system.log)

* elasticsearch cluster state (curl http://localhost:9200/_cluster/state)
{
  "cluster_name" : "AWS Cassandra-AMI Cluster",
  "compressed_size_in_bytes" : 340,
  "version" : 6,
  "state_uuid" : "BJ0TdkGtRriOlLWoivs7Ng",
  "master_node" : "3d8aa6e0-ca98-44ba-8905-e53f998ea068",
  "blocks" : { },
  "nodes" : {
    "ebefaf04-06e2-4759-a9e2-36ae3de522c7" : {
      "name" : "xx.xx.xxx.171",
      "status" : "ALIVE",
      "ephemeral_id" : "ebefaf04-06e2-4759-a9e2-36ae3de522c7",
      "transport_address" : "xx.xx.xxx.171:9300",
      "attributes" : {
        "rack" : "2a",
        "dc" : "us-west-prepops"
      }
    },
    "caa8d34c-3eb7-425a-951a-b1c28346f4f6" : {
      "name" : "xx.xx.xxx.224",
      "status" : "ALIVE",
      "ephemeral_id" : "caa8d34c-3eb7-425a-951a-b1c28346f4f6",
      "transport_address" : "xx.xx.xxx.224:9300",
      "attributes" : {
        "rack" : "2a",
        "dc" : "us-west-prepops"
      }
    },
    "3d8aa6e0-ca98-44ba-8905-e53f998ea068" : {
      "name" : "xx.xx.xxx.61",
      "status" : "ALIVE",
      "ephemeral_id" : "3d8aa6e0-ca98-44ba-8905-e53f998ea068",
      "transport_address" : "xx.xx.xxx.61:9300",
      "attributes" : {
        "rack" : "2a",
        "dc" : "us-west-prepops"
      }
    }
  },
  "metadata" : {
    "version" : 0,
    "cluster_uuid" : "3d8aa6e0-ca98-44ba-8905-e53f998ea068",
    "templates" : { },
    "indices" : { },
    "index-graveyard" : {
      "tombstones" : [ ]
    }
  },
  "routing_table" : {
    "indices" : { }
  },
  "routing_nodes" : {
    "unassigned" : [ ],
    "nodes" : {
      "ebefaf04-06e2-4759-a9e2-36ae3de522c7" : [ ],
      "caa8d34c-3eb7-425a-951a-b1c28346f4f6" : [ ],
      "3d8aa6e0-ca98-44ba-8905-e53f998ea068" : [ ]
    }
  },
  "restore" : {
    "snapshots" : [ ]
  },
  "snapshot_deletions" : {
    "snapshot_deletions" : [ ]
  },
  "snapshots" : {
    "snapshots" : [ ]
  }
}

* cassandra schema (cqlsh>DESC KEYSPACE <your_keyspace>)
cassandra@cqlsh> desc KEYSPACE test;

CREATE KEYSPACE test WITH replication = {'class': 'NetworkTopologyStrategy', 'us-west': '3', 'us-west-prepops': '3'}  AND durable_writes = true;

CREATE TABLE test.emp (
    emp_id text,
    dept text,
    fname text,
    lname text,
    PRIMARY KEY (emp_id, dept)
) WITH CLUSTERING ORDER BY (dept ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';

* cassandra gossip state (run: nodetool gossipinfo)

/xx.xx.246.183
  generation:1585677646
  heartbeat:197975
  STATUS:16:NORMAL,-113428083318429630
  LOAD:197958:5.4573571211E10
  SCHEMA:192176:5f753561-e905-3f58-b172-67c80a2aeef5
  DC:8:us-west
  RACK:10:2b
  RELEASE_VERSION:4:3.11.3
  INTERNAL_IP:6:xx.xx.246.183
  RPC_ADDRESS:3:xx.xx.246.183
  NET_VERSION:1:11
  HOST_ID:2:4cb85e29-e9b9-40d7-8ec8-6a0f545a5a33
  RPC_READY:31:true
  TOKENS:15:<hidden>
/xx.xx.242.101
  generation:1585677313
  heartbeat:198334
  STATUS:16:NORMAL,-1444098092229178093
  LOAD:198284:6.0795989601E10
  SCHEMA:192537:5f753561-e905-3f58-b172-67c80a2aeef5
  DC:8:us-west
  RACK:10:2a
  RELEASE_VERSION:4:3.11.3
  INTERNAL_IP:6:xx.xx.242.101
  RPC_ADDRESS:3:xx.xx.242.101
  NET_VERSION:1:11
  HOST_ID:2:e0155b93-1c4a-4347-87f9-0adf70f5caf9
  RPC_READY:31:true
  TOKENS:15:<hidden>
/xx.xx.243.211
  generation:1585677462
  heartbeat:198182
  STATUS:18:NORMAL,-1245003772573014218
  LOAD:198160:5.4270121071E10
  SCHEMA:192383:5f753561-e905-3f58-b172-67c80a2aeef5
  DC:8:us-west
  RACK:10:2a
  RELEASE_VERSION:4:3.11.3
  INTERNAL_IP:6:xx.xx.243.211
  RPC_ADDRESS:3:xx.xx.243.211
  NET_VERSION:1:11
  HOST_ID:2:508131c5-1480-42e2-8759-4bb8affd28a2
  RPC_READY:31:true
  TOKENS:17:<hidden>
/xx.xx.243.224
  generation:1585866103
  heartbeat:3272
  STATUS:18:NORMAL,-1776625020212102571
  LOAD:3251:3.83474404E8
  SCHEMA:12:5f753561-e905-3f58-b172-67c80a2aeef5
  DC:8:us-west-prepops
  RACK:10:2a
  RELEASE_VERSION:4:3.11.3.5
  INTERNAL_IP:6:xx.xx.243.224
  RPC_ADDRESS:3:xx.xx.243.224
  NET_VERSION:1:11
  HOST_ID:2:caa8d34c-3eb7-425a-951a-b1c28346f4f6
  RPC_READY:30:true
  X1:32:{}
  X2:34:caa8d34c-3eb7-425a-951a-b1c28346f4f6/0
  TOKENS:17:<hidden>
/xx.xx.241.97
  generation:1585834938
  heartbeat:35489
  STATUS:16:NORMAL,-140058499818012650
  LOAD:35443:4.3896627563E10
  SCHEMA:29693:5f753561-e905-3f58-b172-67c80a2aeef5
  DC:8:us-west
  RACK:10:2a
  RELEASE_VERSION:4:3.11.3
  INTERNAL_IP:6:xx.xx.241.97
  RPC_ADDRESS:3:xx.xx.241.97
  NET_VERSION:1:11
  HOST_ID:2:aeb862a8-a99f-4728-9a76-30f274a52ab0
  RPC_READY:28:true
  TOKENS:15:<hidden>
/xx.xx.246.79
  generation:1585677798
  heartbeat:197831
  STATUS:16:NORMAL,-1031254217506618383
  LOAD:197786:5.195148754E10
  SCHEMA:192035:5f753561-e905-3f58-b172-67c80a2aeef5
  DC:8:us-west
  RACK:10:2b
  RELEASE_VERSION:4:3.11.3
  INTERNAL_IP:6:xx.xx.246.79
  RPC_ADDRESS:3:xx.xx.246.79
  NET_VERSION:1:11
  HOST_ID:2:6cd48ec9-c42e-482d-854d-95a9ce433841
  RPC_READY:31:true
  TOKENS:15:<hidden>
/xx.xx.242.61
  generation:1585866162
  heartbeat:3212
  STATUS:18:NORMAL,-1095808708938263228
  LOAD:3189:3.83456408E8
  SCHEMA:12:5f753561-e905-3f58-b172-67c80a2aeef5
  DC:8:us-west-prepops
  RACK:10:2a
  RELEASE_VERSION:4:3.11.3.5
  INTERNAL_IP:6:xx.xx.242.61
  RPC_ADDRESS:3:xx.xx.242.61
  NET_VERSION:1:11
  HOST_ID:2:3d8aa6e0-ca98-44ba-8905-e53f998ea068
  RPC_READY:30:true
  X1:32:{}
  X2:34:3d8aa6e0-ca98-44ba-8905-e53f998ea068/0
  TOKENS:17:<hidden>
/xx.xx.240.171
  generation:1585865917
  heartbeat:3464
  STATUS:18:NORMAL,-4012006785073304298
  LOAD:3437:3.84817403E8
  SCHEMA:12:5f753561-e905-3f58-b172-67c80a2aeef5
  DC:8:us-west-prepops
  RACK:10:2a
  RELEASE_VERSION:4:3.11.3.5
  INTERNAL_IP:6:xx.xx.240.171
  RPC_ADDRESS:3:xx.xx.240.171
  NET_VERSION:1:11
  HOST_ID:2:ebefaf04-06e2-4759-a9e2-36ae3de522c7
  RPC_READY:30:true
  X1:32:{}
  X2:34:ebefaf04-06e2-4759-a9e2-36ae3de522c7/0
  TOKENS:17:<hidden>

**Comment by vroyer** [comment]
It should work, but your procedure is a bit unclear.

- Check the elastic_admin keyspace is properly replicated on us-west-prepops
- You should use a more recent version 6.2.3.24
- You must deploy the ExtendedElasticSecondaryIndex class in the cassandra-only us-west DC classpath.
- If you need more support under NDA, please contact strapdata.

**Comment by rsr999** [comment]
Thank you, Vincent.
The issue was with the "elastic_admin" Keyspace.
Since My first attempt to add the elassandra nodes as a new DC to the existing Cassandra cluster failed, I was supposed to completely remove the elastic_admin keyspace before making another attempt which I didn't do.
After the failed attempt I was removing the elassandra nodes from the cluster but not dropping the "elastic_admin" keypsace before attempting again to add the elassandra nodes to the same cassandra cluster.
Once I dropped the keypsace and  then tried , everything worked fine.

Thanks & Regards
Raj
