### ISSUE TITLE
PAXOS Failed to update metadata source=create-index [test2], cause [auto(bulk api)] 

### ISSUE THREAD

**Issue by tengzhuofei** [strapdata/elassandra#344]
#342  elassandra 6.8.4  Cassandra 3.11.5.2

curl -XPUT -H 'Content-Type: application/json' 'http://$host:9200/test2/tweet/2' -d '
{
"user": "kimchy",
"postDate": "2009-11-15T14:12:12",
"message": "Another tweet, will it be indexed?"
}'

After executing the above command, no result is returned, and it keeps stuck

server log：
2020-04-30 03:19:26,243 WARN [elasticsearch[172.16.0.132][masterService#updateTask][T#1]] org.elasticsearch.cluster.service.ClusterService.commitMetaData(ClusterService.java:1279) PAXOS Failed to update metadata source=create-index [test2], cause [auto(bulk api)] prevMetadata=f764e235-a004-4d89-90ea-51937b5ea621/0 nextMetaData=f764e235-a004-4d89-90ea-51937b5ea621/1
2020-04-30 03:19:26,243 WARN [elasticsearch[172.16.0.132][masterService#updateTask][T#1]] org.elassandra.discovery.CassandraDiscovery.publishAsCoordinator(CassandraDiscovery.java:1123) PAXOS concurrent update, source=create-index [test2], cause [auto(bulk api)] metadata=f764e235-a004-4d89-90ea-51937b5ea621/1, resubmit task on next metadata change

**Comment by tengzhuofei** [comment]
second node error 

2020-05-13 03:56:44,415 WARN  [main] org.elassandra.discovery.CassandraDiscovery.publishX2(CassandraDiscovery.java:923) Gossiper not yet enabled to publish X2
2020-05-13 03:56:44,444 INFO  [main] org.elasticsearch.cluster.service.ClusterService.readMetaDataFromTableExtensions(ClusterService.java:980) Elasticsearch metadata succesfully loaded from CQL table extensions metadata.version=2
2020-05-13 03:56:44,474 INFO  [elasticsearch[10.42.4.75][masterService#updateTask][T#1]] org.elassandra.gateway.CassandraGatewayService$GatewayRecoveryListener$1.clusterStateProcessed(CassandraGatewayService.java:153) Recovered [1] indices into cluster_state metadata=cc88ffe3-1548-4ab4-be00-87226c030c90/2
2020-05-13 03:56:44,638 WARN  [elasticsearch[10.42.4.75][clusterApplierService#updateTask][T#1]] org.elassandra.discovery.CassandraDiscovery.publishX2(CassandraDiscovery.java:923) Gossiper not yet enabled to publish X2
2020-05-13 03:56:44,770 INFO  [elasticsearch[10.42.4.75][generic][T#1]] org.elassandra.shard.CassandraShardStateListener.afterIndexShardStarted(CassandraShardStateListener.java:69) shard [test3][0] started
2020-05-13 03:56:44,772 WARN  [elasticsearch[10.42.4.75][generic][T#1]] org.elassandra.discovery.CassandraDiscovery.publishX1(CassandraDiscovery.java:909) Gossiper not yet enabled to publish X1
2020-05-13 03:56:44,811 INFO  [main] org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:336) Replayed 0 commitlogs records
2020-05-13 03:56:47,777 WARN  [MigrationStage:1] org.apache.cassandra.service.MigrationTask.runMayThrow(MigrationTask.java:67) Can't send schema pull request: node /10.42.0.58 is down.
2020-05-13 03:56:48,002 WARN  [GossipTasks:1] org.apache.cassandra.gms.FailureDetector.interpret(FailureDetector.java:296) Not marking nodes down due to local pause of 5443868050 > 5000000000
2020-05-13 03:56:48,205 ERROR [InternalResponseStage:1] org.apache.cassandra.service.MigrationTask$1.response(MigrationTask.java:95) Configuration exception merging remote schema
org.apache.cassandra.exceptions.ConfigurationException: Column family ID mismatch (found b8494ec0-94cd-11ea-b6ff-fbb6e060fa9c; expected d27862e0-94c3-11ea-b3ad-1bd8214f2ca5)
	at org.apache.cassandra.config.CFMetaData.validateCompatibility(CFMetaData.java:949)
	at org.apache.cassandra.config.CFMetaData.apply(CFMetaData.java:903)
	at org.apache.cassandra.config.Schema.updateTable(Schema.java:703)
	at org.apache.cassandra.schema.SchemaKeyspace.updateKeyspace(SchemaKeyspace.java:1518)
	at org.apache.cassandra.schema.SchemaKeyspace.mergeSchema(SchemaKeyspace.java:1471)
	at org.apache.cassandra.schema.SchemaKeyspace.mergeSchema(SchemaKeyspace.java:1437)
	at org.apache.cassandra.schema.SchemaKeyspace.mergeSchemaAndAnnounceVersion(SchemaKeyspace.java:1409)
	at org.apache.cassandra.schema.SchemaKeyspace.mergeSchemaAndAnnounceVersion(SchemaKeyspace.java:1404)
	at org.apache.cassandra.service.MigrationTask$1.response(MigrationTask.java:91)
	at org.apache.cassandra.net.ResponseVerbHandler.doVerb(ResponseVerbHandler.java:53)
	at org.apache.cassandra.net.MessageDeliveryTask.run(MessageDeliveryTask.java:66)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.cassandra.concurrent.NamedThreadFactory.lambda$threadLocalDeallocator$0(NamedThreadFactory.java:84)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2020-05-13 03:56:48,368 ERROR [InternalResponseStage:2] org.apache.cassandra.service.MigrationTask$1.response(MigrationTask.java:95) Configuration exception merging remote schema
org.apache.cassandra.exceptions.ConfigurationException: Column family ID mismatch (found b8494ec0-94cd-11ea-b6ff-fbb6e060fa9c; expected d27862e0-94c3-11ea-b3ad-1bd8214f2ca5)
	at org.apache.cassandra.config.CFMetaData.validateCompatibility(CFMetaData.java:949)
	at org.apache.cassandra.config.CFMetaData.apply(CFMetaData.java:903)
	at org.apache.cassandra.config.Schema.updateTable(Schema.java:703)
	at org.apache.cassandra.schema.SchemaKeyspace.updateKeyspace(SchemaKeyspace.java:1518)
	at org.apache.cassandra.schema.SchemaKeyspace.mergeSchema(SchemaKeyspace.java:1471)
	at org.apache.cassandra.schema.SchemaKeyspace.mergeSchema(SchemaKeyspace.java:1437)
	at org.apache.cassandra.schema.SchemaKeyspace.mergeSchemaAndAnnounceVersion(SchemaKeyspace.java:1409)
	at org.apache.cassandra.schema.SchemaKeyspace.mergeSchemaAndAnnounceVersion(SchemaKeyspace.java:1404)
	at org.apache.cassandra.service.MigrationTask$1.response(MigrationTask.java:91)
	at org.apache.cassandra.net.ResponseVerbHandler.doVerb(ResponseVerbHandler.java:53)
	at org.apache.cassandra.net.MessageDeliveryTask.run(MessageDeliveryTask.java:66)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.cassandra.concurrent.NamedThreadFactory.lambda$threadLocalDeallocator$0(NamedThreadFactory.java:84)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2020-05-13 03:56:54,261 INFO  [main] org.elasticsearch.cluster.service.ClusterService.readMetaDataFromTableExtensions(ClusterService.java:980) Elasticsearch metadata succesfully loaded from CQL table extensions metadata.version=2
2020-05-13 03:56:54,308 WARN  [main] org.elasticsearch.cluster.service.ClusterService.createOrUpdateElasticAdminKeyspace(ClusterService.java:1218) Keyspace [elastic_admin] replication factor DC1=1, you should increase this replication factor to avoid possible issue if quorum cannot be reach to update the elasticsearch mapping.
2020-05-13 03:56:54,310 INFO  [elasticsearch[10.42.4.75][masterService#updateTask][T#1]] org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:251) starting-cassandra-discovery[org.elassandra.discovery.CassandraDiscovery$RoutingTableUpdateTask@3ff0719c], searchEnabled-changed-to-true[org.elassandra.discovery.CassandraDiscovery$RoutingTableUpdateTask@1112d490], reason: added {{10.42.0.58}{0aa2ddee-95fb-4d85-bdc1-455cc9c795fc}{0aa2ddee-95fb-4d85-bdc1-455cc9c795fc}{10.42.0.58}{10.42.0.58:9300}{ALIVE}{rack=RAC1, dc=DC1},}
2020-05-13 03:56:54,313 INFO  [elasticsearch[10.42.4.75][clusterApplierService#updateTask][T#1]] org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:469) added {{10.42.0.58}{0aa2ddee-95fb-4d85-bdc1-455cc9c795fc}{0aa2ddee-95fb-4d85-bdc1-455cc9c795fc}{10.42.0.58}{10.42.0.58:9300}{ALIVE}{rack=RAC1, dc=DC1},}, reason: apply cluster state (from cc88ffe3-1548-4ab4-be00-87226c030c90[committed version [cc88ffe3-1548-4ab4-be00-87226c030c90/2] source [starting-cassandra-discovery[org.elassandra.discovery.CassandraDiscovery$RoutingTableUpdateTask@3ff0719c], searchEnabled-changed-to-true[org.elassandra.discovery.CassandraDiscovery$RoutingTableUpdateTask@1112d490]]])
2020-05-13 03:56:54,316 INFO  [elasticsearch[10.42.4.75][masterService#updateTask][T#1]] org.elassandra.gateway.CassandraGatewayService$1.clusterStateProcessed(CassandraGatewayService.java:93) cassandra ring block released
Elassandra started

**Comment by tengzhuofei** [comment]
2020-05-13 06:15:44,184 WARN  [elasticsearch[10.42.0.58][write][T#1]] org.elasticsearch.rest.BytesRestResponse.build(BytesRestResponse.java:133) path: /test4/tweet/2, params: {index=test4, id=2, type=tweet}
org.elasticsearch.ElasticsearchTimeoutException: blocking update timeout
	at org.elasticsearch.cluster.service.ClusterService$BlockingActionListener.waitForUpdate(ClusterService.java:647)
	at org.elasticsearch.cluster.service.ClusterService.blockingMappingUpdate(ClusterService.java:695)
	at org.elasticsearch.cluster.service.ClusterService.blockingMappingUpdate(ClusterService.java:680)
	at org.elasticsearch.action.bulk.TransportShardBulkAction$ConcreteMappingUpdatePerformer.updateMappings(TransportShardBulkAction.java:520)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.lambda$executeIndexRequestOnPrimary$5(TransportShardBulkAction.java:472)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeOnPrimaryWhileHandlingMappingUpdates(TransportShardBulkAction.java:499)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeIndexRequestOnPrimary(TransportShardBulkAction.java:464)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:226)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:169)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:160)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:146)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:83)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:1088)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:1066)
	at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:105)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.runWithPrimaryShardReference(TransportReplicationAction.java:445)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:387)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:327)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:314)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66)
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:696)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:751)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-05-13 06:15:44,208 WARN  [elasticsearch[10.42.0.58][masterService#updateTask][T#1]] org.elasticsearch.cluster.service.MasterService.warnAboutSlowTaskIfNeeded(MasterService.java:583) cluster state update task [put-mapping[tweet]] took [30s] above the warn threshold of 30s

**Comment by tengzhuofei** [comment]
2020-05-13 06:22:36,339 WARN  [MessagingService-Incoming-/10.42.4.75] org.apache.cassandra.net.IncomingTcpConnection.run(IncomingTcpConnection.java:103) UnknownColumnFamilyException reading from socket; closing
org.apache.cassandra.db.UnknownColumnFamilyException: Couldn't find table for cfId d27862e0-94c3-11ea-b3ad-1bd8214f2ca5. If a table was just created, this is likely due to the schema not being fully propagated.  Please wait for schema agreement on table creation.
	at org.apache.cassandra.config.CFMetaData$Serializer.deserialize(CFMetaData.java:1533)
	at org.apache.cassandra.db.partitions.PartitionUpdate$PartitionUpdateSerializer.deserialize30(PartitionUpdate.java:850)
	at org.apache.cassandra.db.partitions.PartitionUpdate$PartitionUpdateSerializer.deserialize(PartitionUpdate.java:825)
	at org.apache.cassandra.service.paxos.Commit$CommitSerializer.deserialize(Commit.java:130)
	at org.apache.cassandra.service.paxos.Commit$CommitSerializer.deserialize(Commit.java:112)
	at org.apache.cassandra.net.MessageIn.read(MessageIn.java:123)
	at org.apache.cassandra.net.IncomingTcpConnection.receiveMessage(IncomingTcpConnection.java:195)
	at org.apache.cassandra.net.IncomingTcpConnection.receiveMessages(IncomingTcpConnection.java:183)
	at org.apache.cassandra.net.IncomingTcpConnection.run(IncomingTcpConnection.java:94)

**Comment by vroyer** [comment]
You probably broke your CQL schema for some reason (see Column family ID mismatch).
Run nodetool describecluster to check your schema, restart nodes having a wrong schema id.
Then check elastic_admin.metadata_log.version = elasticsearch cluster state.metadata.version. If it's not the case, manually set elastic_admin.metadata_log.version to your elasticsearch cluster state.metadata.version.

**Comment by tengzhuofei** [comment]
![image](https://user-images.githubusercontent.com/49179198/88062286-37842d00-cb9b-11ea-903e-d1d012e9ccc8.png)

**Comment by tengzhuofei** [comment]
first start to create index fail

**Comment by vroyer** [comment]
Yes,  for some reason, this table is empty, so PAXOS transaction can succeed on the row that is missing.
When the first node starts for the first time, it automatically adds a row in that table with version = 0 which is missing in your case. There is maybe in your environment a race condition between inserting this first row and bootstrapping the second node, cloud you please check your logs to track these events ?

**Comment by tengzhuofei** [comment]
The nodes are started in order

**Comment by tengzhuofei** [comment]
![image](https://user-images.githubusercontent.com/49179198/88065144-d199a480-cb9e-11ea-9a19-5eab2ca0e728.png)

**Comment by tengzhuofei** [comment]
second node

![image](https://user-images.githubusercontent.com/49179198/88065436-2ccb9700-cb9f-11ea-8d38-6a68f2f775d2.png)

**Comment by vroyer** [comment]
Yes, in the first node, insert the first row succeed but there is no row in the table at the end. 
Could you check that when starting just one node in a single node cluster ?

**Comment by tengzhuofei** [comment]
I originally set up 3 seed nodes, now I changed to 2 and cassandra.ring_delay_ms=60000 to 200000，What’s the impact? There can be 2 ok in 10 times.
Not bad


I set up 3 nodes in total

![image](https://user-images.githubusercontent.com/49179198/88070640-7ae39900-cba5-11ea-82a0-a1986e60b602.png)

**Comment by tengzhuofei** [comment]
> Yes, in the first node, insert the first row succeed but there is no row in the table at the end.
> Could you check that when starting just one node in a single node cluster ?


The second node will delete or roll back log table data？

**Comment by tengzhuofei** [comment]
third node log

Can't send schema pull request: node /172.16.0.82 is down
Can't send schema pull request: node /172.16.0.42 is down

**Comment by tengzhuofei** [comment]
only one node  is good
