### ISSUE TITLE
After elassandra creates an index, some shards are not normal

### ISSUE THREAD

**Issue by tengzhuofei** [strapdata/elassandra#362]
elassandra 6.8.4.2

at java.util.Collections$UnmodifiableMap.containsKey(Collections.java:1454)
2020-07-10 09:28:59,767 ERROR [GossipStage:1] org.apache.cassandra.service.CassandraDaemon$2.uncaughtException(CassandraDaemon.java:234) Exception in thread Thread[GossipStage:1,5,main]
java.lang.StackOverflowError: null
 at java.util.HashMap.hash(HashMap.java:339)
 at java.util.HashMap.containsKey(HashMap.java:596)
 at java.util.Collections$UnmodifiableMap.containsKey(Collections.java:1454)
 at java.util.Collections$UnmodifiableMap.containsKey(Collections.java:1454)
 at java.util.Collections$UnmodifiableMap.containsKey(Collections.java:1454)
 at java.util.Collections$U

**Comment by tengzhuofei** [comment]
![image](https://user-images.githubusercontent.com/49179198/87151116-d67c6f80-c2e5-11ea-8525-cf0dc177a84a.png)

**Comment by vroyer** [comment]
It seems you have not enough memory or an erroneous settings leading to the java.lang.StackOverflowError.

**Comment by tengzhuofei** [comment]
![image](https://user-images.githubusercontent.com/49179198/87238546-3e41d000-c436-11ea-9656-11e7911e5224.png)

**Comment by tengzhuofei** [comment]
why is it restart pod is recovery?
