### ISSUE TITLE
Having issue with recreating index.

### ISSUE THREAD

**Issue by ocelikk** [strapdata/elassandra#384]
Hi @vroyer, we run elassandra 6.2.3 on Centos 7, Wanted to recreate index. Dropped it and can not create one. Writes the following message in logs. 
```
2021-01-22 18:46:50,207 WARN  [elasticsearch[192.168.16.20][masterService#updateTask][T#1]] MasterService.java:684 executeTasks failed to execute cluster state update source [create-index [x], cause [api]]
java.lang.IllegalArgumentException: Rejecting mapping update to [x] as the final mapping would have more than 1 type: [x, source]
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:663)
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:515)
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:439)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$IndexCreationTask.execute(MetaDataCreateIndexService.java:493)
	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:52)
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:676)
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:300)
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:221)
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:152)
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:573)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

http get response :
```
{
    "error": {
        "root_cause": [
            {
                "type": "index_not_found_exception",
                "reason": "no such index",
                "resource.type": "index_or_alias",
                "resource.id": "x",
                "index_uuid": "_na_",
                "index": "x"
            }
        ],
        "type": "index_not_found_exception",
        "reason": "no such index",
        "resource.type": "index_or_alias",
        "resource.id": "x",
        "index_uuid": "_na_",
        "index": "x"
    },
    "status": 404
}
```

http put response :

```
{
    "error": {
        "root_cause": [
            {
                "type": "illegal_argument_exception",
                "reason": "Rejecting mapping update to [x] as the final mapping would have more than 1 type: [x, source]"
            }
        ],
        "type": "illegal_argument_exception",
        "reason": "Rejecting mapping update to [x] as the final mapping would have more than 1 type: [x, source]"
    },
    "status": 400
}
```

gossip info : 

```
 generation:1610386547
  heartbeat:985907
  STATUS:16:NORMAL,-2110247280634197533
  LOAD:985879:2.55270908083E11
  SCHEMA:896003:edb00fff-ea14-3189-91e0-0f624aedf32f
  DC:8:DC1
  RACK:10:r1
  RELEASE_VERSION:4:3.11.3.5
  INTERNAL_IP:6:192.168.16.20
  RPC_ADDRESS:3:192.168.16.20
  NET_VERSION:1:11
  HOST_ID:2:3031587e-5354-4342-9ddc-e5696985fc8c
  RPC_READY:28:true
  X1:896007:{"xx":3,"xx":3,..}
  X2:896009:3031587e-5354-4342-9ddc-e5696985fc8c/161
  TOKENS:15:<hidden>
```

**Comment by Stoyan-Bukovich** [comment]
Did you checked the corresponding Cassandra table for custom  index left over?

**Comment by ocelikk** [comment]
> Did you checked the corresponding Cassandra table for custom index left over?

If something like elastic_tablename_idx in table is what you mean by index left over, corresponding table doesn't have any.
