### ISSUE TITLE
Jar Hell when installing ingest-attachment plugin

### ISSUE THREAD

**Issue by harshagarwal00** [strapdata/elassandra#410]
When running:
` bin/elasticsearch-plugin install ingest-attachment`

I see:

`Exception in thread "main" java.lang.IllegalStateException: failed to load plugin ingest-attachment due to jar hell
	at org.elasticsearch.plugins.PluginsService.checkBundleJarHell(PluginsService.java:475)
	at org.elasticsearch.plugins.InstallPluginCommand.jarHellCheck(InstallPluginCommand.java:609)
	at org.elasticsearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:588)
	at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:707)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:623)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:223)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:212)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:75)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:48)
Caused by: java.lang.IllegalStateException: jar hell!
class: org.slf4j.helpers.BasicMarker
jar1: /home/azureuser/elassandra-6.2.3.38/plugins/.installing-2974073780624375496/slf4j-api-1.6.2.jar
jar2: /home/azureuser/elassandra-6.2.3.38/lib/slf4j-api-1.7.25.jar`

**Comment by harshagarwal00** [comment]
Found the solution :)



From: 
https://jarcasting.com/artifacts/com.strapdata.elasticsearch.plugin/ingest-attachment/
or even better try the official site:
https://search.maven.org/artifact/com.strapdata.elasticsearch.plugin/ingest-attachment/6.2.3.31/jar
and click downloads and then zip

Downloaded: ingest-attachment-6.2.3.31.zip

Then run: 
`bin/elasticsearch-plugin install file:"/home/sampleuser/ingest-attachment-6.2.3.31.zip"`
