### ISSUE TITLE
Elassandra not able to run in Kubernetes

### ISSUE THREAD

**Issue by Sardonyxtechsupport** [strapdata/elassandra#420]
Dear team,

 I have run this image **strapdata/elassandra:latest** in minikube successfully in Windows machine.
 but I cannot run the same image in the Kubernetes cluster kueadm setup.
I have 1 master node and 2 worker node. 
the  above three machines are the Linux Ubuntu 20.04 server os.
When I am running the Elassandra , I am getting the following Error.

```
kubectl logs elassandra-0
Defaulted container "elassandra" out of: elassandra, increase-vm-max-map-count (init), increase-ulimit (init)
/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-init.d/*
Starting cassandra with org.apache.cassandra.service.ElassandraDaemon
CompilerOracle: dontinline org/apache/cassandra/db/Columns$Serializer.deserializeLargeSubset (Lorg/apache/cassandra/io/util/DataInputPlus;Lorg/apache/cassandra/db/Columns;I)Lorg/apache/cassandra/db/Columns;
CompilerOracle: dontinline org/apache/cassandra/db/Columns$Serializer.serializeLargeSubset (Ljava/util/Collection;ILorg/apache/cassandra/db/Columns;ILorg/apache/cassandra/io/util/DataOutputPlus;)V
CompilerOracle: dontinline org/apache/cassandra/db/Columns$Serializer.serializeLargeSubsetSize (Ljava/util/Collection;ILorg/apache/cassandra/db/Columns;I)I
CompilerOracle: dontinline org/apache/cassandra/db/commitlog/AbstractCommitLogSegmentManager.advanceAllocatingFrom (Lorg/apache/cassandra/db/commitlog/CommitLogSegment;)V
CompilerOracle: dontinline org/apache/cassandra/db/transform/BaseIterator.tryGetMoreContents ()Z
CompilerOracle: dontinline org/apache/cassandra/db/transform/StoppingTransformation.stop ()V
CompilerOracle: dontinline org/apache/cassandra/db/transform/StoppingTransformation.stopInPartition ()V
CompilerOracle: dontinline org/apache/cassandra/io/util/BufferedDataOutputStreamPlus.doFlush (I)V
CompilerOracle: dontinline org/apache/cassandra/io/util/BufferedDataOutputStreamPlus.writeExcessSlow ()V
CompilerOracle: dontinline org/apache/cassandra/io/util/BufferedDataOutputStreamPlus.writeSlow (JI)V
CompilerOracle: dontinline org/apache/cassandra/io/util/RebufferingInputStream.readPrimitiveSlowly (I)J
CompilerOracle: inline org/apache/cassandra/db/rows/UnfilteredSerializer.serializeRowBody (Lorg/apache/cassandra/db/rows/Row;ILorg/apache/cassandra/db/SerializationHeader;Lorg/apache/cassandra/io/util/DataOutputPlus;)V
CompilerOracle: inline org/apache/cassandra/io/util/Memory.checkBounds (JJ)V
CompilerOracle: inline org/apache/cassandra/io/util/SafeMemory.checkBounds (JJ)V
CompilerOracle: inline org/apache/cassandra/utils/AsymmetricOrdering.selectBoundary (Lorg/apache/cassandra/utils/AsymmetricOrdering/Op;II)I
CompilerOracle: inline org/apache/cassandra/utils/AsymmetricOrdering.strictnessOfLessThan (Lorg/apache/cassandra/utils/AsymmetricOrdering/Op;)I
CompilerOracle: inline org/apache/cassandra/utils/BloomFilter.indexes (Lorg/apache/cassandra/utils/IFilter/FilterKey;)[J
CompilerOracle: inline org/apache/cassandra/utils/BloomFilter.setIndexes (JJIJ[J)V
CompilerOracle: inline org/apache/cassandra/utils/ByteBufferUtil.compare (Ljava/nio/ByteBuffer;[B)I
CompilerOracle: inline org/apache/cassandra/utils/ByteBufferUtil.compare ([BLjava/nio/ByteBuffer;)I
CompilerOracle: inline org/apache/cassandra/utils/ByteBufferUtil.compareUnsigned (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
CompilerOracle: inline org/apache/cassandra/utils/FastByteOperations$UnsafeOperations.compareTo (Ljava/lang/Object;JILjava/lang/Object;JI)I
CompilerOracle: inline org/apache/cassandra/utils/FastByteOperations$UnsafeOperations.compareTo (Ljava/lang/Object;JILjava/nio/ByteBuffer;)I
CompilerOracle: inline org/apache/cassandra/utils/FastByteOperations$UnsafeOperations.compareTo (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
CompilerOracle: inline org/apache/cassandra/utils/vint/VIntCoding.encodeVInt (JI)[B
2023-12-12 10:55:13,881 WARN  [main] org.apache.cassandra.db.SystemKeyspace.getLocalHostId(SystemKeyspace.java:1130) No host ID found, created 766bbaac-aee3-413b-9729-dc828062c7ed (Note: This should happen exactly once per node).
2023-12-12 10:55:14,009 INFO  [main] org.elasticsearch.cluster.service.ClusterService.<init>(ClusterService.java:373) Starting with elastic_admin keyspace=[elastic_admin], CQL extension pattern=[elastic_admin(_[a-zA-Z0-9_\-]+)?/.*]
2023-12-12 10:55:14,009 INFO  [main] org.elasticsearch.cluster.service.ClusterService.<init>(ClusterService.java:376) Starting with datacenter.tags=[]
{6.8.4}: Initialization Failed ...
- AssertionError[null]
2023-12-12 10:55:14,108 ERROR [main] org.apache.cassandra.service.ElassandraDaemon.main(ElassandraDaemon.java:601) Exception
java.lang.AssertionError: null
        at org.elasticsearch.monitor.os.OsProbe.getControlGroups(OsProbe.java:247)
        at org.elasticsearch.monitor.os.OsProbe.getCgroup(OsProbe.java:510)
        at org.elasticsearch.monitor.os.OsProbe.osStats(OsProbe.java:635)
        at org.elasticsearch.monitor.os.OsService.<init>(OsService.java:49)
        at org.elasticsearch.monitor.MonitorService.<init>(MonitorService.java:46)
        at org.elasticsearch.node.Node.<init>(Node.java:402)
        at org.elasticsearch.node.Node.<init>(Node.java:265)
        at org.apache.cassandra.service.ElassandraDaemon$2.<init>(ElassandraDaemon.java:176)
        at org.apache.cassandra.service.ElassandraDaemon.activate(ElassandraDaemon.java:176)
        at org.apache.cassandra.service.ElassandraDaemon.main(ElassandraDaemon.java:567)
```

**Comment by KaustubhJha-TUL-UpperFunnel** [comment]
are you using yaml to create the pods ?
