### ISSUE TITLE
java.io.IOException: from is a reserved keyword

### ISSUE THREAD

**Issue by lmangani** [strapdata/elassandra#65]
Bonjour Vincent,

Using latest build, I am attempting to create custom index mapping including ```object``` types resulting in a faceted issue - filing them together as they seem two faces of the same coin so to speak.

### java.io.IOException: from is a reserved keyword

```
PUT watcher
{
    "mappings": {
      "watch": {
        "properties": {
          "id": {
          "type":  "string",
          "index": "not_analyzed"
          },
          "condition": {
            "type":"object",
            "enabled": false
          },
          "input": {
            "type":"object",
            "enabled": false
          },
          "transform": {
            "type":"object",
            "enabled": false
          }
        }
      }
    }
}
```

followed by a document creation attempt:
```
PUT watcher/watch/test_watch_random
{
    "disabled": false,
    "id": "test_watch_random",
    "trigger": {
      "schedule": {
        "later": "every 5 minutes"
      }
    },
    "input": {
      "search": {
        "request": {
          "index": [],
          "body": {}
        }
      }
    },
    "condition": {
      "script": {
        "script": "payload.hits.total > 100"
      }
    },
    "transform": {},
    "actions": {
      "email_admin": {
        "throttle_period": "15m",
        "email": {
          "to": "alarm@localhost",
          "from": "sentinl@localhost",
          "subject": "Sentinl Alarm",
          "priority": "high",
          "body": "Found {{payload.hits.total}} Events"
        }
      }
    }
  }
```

The first response of Elassandra is:
```
{
   "error": {
      "root_cause": [
         {
            "type": "runtime_exception",
            "reason": "java.io.IOException: from is a reserved keyword"
         }
      ],
      "type": "runtime_exception",
      "reason": "java.io.IOException: from is a reserved keyword",
      "caused_by": {
         "type": "i_o_exception",
         "reason": "from is a reserved keyword",
         "caused_by": {
            "type": "configuration_exception",
            "reason": "from is a reserved keyword"
         }
      }
   },
   "status": 500
}
```
 with logs:
```
2016-12-26 08:51:11,257 WARN  [elasticsearch[127.0.0.1][http_server_worker][T#3]{New I/O worker #53}] BytesRestResponse.java:134 convert path: /watcher2/watch/test_watch_random, params: {index=watcher2, id=test_watch_random, type=watch}
java.lang.RuntimeException: java.io.IOException: from is a reserved keyword
	at org.elassandra.cluster.InternalCassandraClusterService$BlockingActionListener.waitForUpdate(InternalCassandraClusterService.java:1820)
	at org.elassandra.cluster.InternalCassandraClusterService.blockingMappingUpdate(InternalCassandraClusterService.java:1842)
	at org.elassandra.cluster.InternalCassandraClusterService.upsertDocument(InternalCassandraClusterService.java:1879)
	at org.elassandra.cluster.InternalCassandraClusterService.insertDocument(InternalCassandraClusterService.java:1852)
	at org.elasticsearch.action.index.TransportXIndexAction.innerExecute(TransportXIndexAction.java:85)
	at org.elasticsearch.action.index.TransportIndexAction.doExecute(TransportIndexAction.java:120)
	at org.elasticsearch.action.index.TransportIndexAction.doExecute(TransportIndexAction.java:66)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:137)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:85)
	at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:58)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
	at org.elasticsearch.client.FilterClient.doExecute(FilterClient.java:52)
	at org.elasticsearch.rest.BaseRestHandler$HeadersAndContextCopyClient.doExecute(BaseRestHandler.java:88)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
	at org.elasticsearch.client.support.AbstractClient.index(AbstractClient.java:371)
	at org.elasticsearch.rest.action.index.RestIndexAction.handleRequest(RestIndexAction.java:105)
	at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:54)
	at org.elasticsearch.rest.RestController.executeHandler(RestController.java:198)
	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:158)
	at org.elasticsearch.http.HttpServer.internalDispatchRequest(HttpServer.java:153)
	at org.elasticsearch.http.HttpServer$Dispatcher.dispatchRequest(HttpServer.java:101)
	at org.elasticsearch.http.netty.NettyHttpServerTransport.dispatchRequest(NettyHttpServerTransport.java:451)
	at org.elasticsearch.http.netty.HttpRequestHandler.messageReceived(HttpRequestHandler.java:61)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.http.netty.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:60)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: from is a reserved keyword
	at org.elassandra.cluster.InternalCassandraClusterService.updateTableSchema(InternalCassandraClusterService.java:1185)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:391)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:280)
	at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:540)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:902)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	... 3 common frames omitted
Caused by: org.apache.cassandra.exceptions.ConfigurationException: from is a reserved keyword
	at org.elassandra.cluster.InternalCassandraClusterService.buildUDT(InternalCassandraClusterService.java:795)
	at org.elassandra.cluster.InternalCassandraClusterService.buildCql(InternalCassandraClusterService.java:744)
	at org.elassandra.cluster.InternalCassandraClusterService.buildUDT(InternalCassandraClusterService.java:772)
	at org.elassandra.cluster.InternalCassandraClusterService.buildCql(InternalCassandraClusterService.java:744)
	at org.elassandra.cluster.InternalCassandraClusterService.buildUDT(InternalCassandraClusterService.java:772)
	at org.elassandra.cluster.InternalCassandraClusterService.buildCql(InternalCassandraClusterService.java:744)
	at org.elassandra.cluster.InternalCassandraClusterService.updateTableSchema(InternalCassandraClusterService.java:1093)
	... 9 common frames omitted

```
Interestingly, attempting the very same insert unchanged, works:
```
{
  "_index": "watcher",
  "_type": "watch",
  "_id": "test_watch_random",
  "_version": 1,
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "created": true
}
```
and gets indexed correctly:
```
GET watcher/_search
{
  "took": 5,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 1,
    "hits": [
      {
        "_index": "watcher",
        "_type": "watch",
        "_id": "test_watch_random",
        "_score": 1,
        "_source": {
          "input": "{\"search\":{\"request\":{\"index\":[],\"body\":{}}}}",
          "condition": "{\"script\":{\"script\":\"payload.hits.total > 100\"}}",
          "transform": "{}",
          "id": "test_name"
        }
      }
    ]
  }
}

```

### Pure Object documents not searchable
Attempting to create a mapping without an "enabled" field seems to fail harder - the above mapping/document without the "string" id field is accepted but returns no search results afterwards.

Here's an adapted example to reproduce:

```
PUT watcher_fail
{
    "mappings": {
      "watch": {
        "properties": {
          "condition": {
            "type":"object",
            "enabled": false
          },
          "input": {
            "type":"object",
            "enabled": false
          },
          "transform": {
            "type":"object",
            "enabled": false
          }
        }
      }
    }
}
```

followed by a document creation attempt:
```
PUT watcher_fail/watch/this_doc_will_be_missing
{
    "trigger": {
      "schedule": {
        "later": "every 5 minutes"
      }
    },
    "input": {
      "search": {
        "request": {
          "index": [],
          "body": {}
        }
      }
    },
    "condition": {
      "script": {
        "script": "payload.hits.total > 100"
      }
    },
    "transform": {},
    "actions": {
      "email_admin": {
        "throttle_period": "15m",
        "email": {
          "to": "alarm@localhost",
          "from": "sentinl@localhost",
          "subject": "Sentinl Alarm",
          "priority": "high",
          "body": "Found {{payload.hits.total}} Events"
        }
      }
    }
  }
```

The above document should get accepted, but will never be available in search:
```
GET watcher_fail/_search
```

**Comment by vroyer** [comment]
Hi Lorenzo,

This is because your « from » field in « actions » is a CQL reserved keyword (SELECT .. FROM …). 
So dynamic mapping failed for actions, and this field is missing in your indexed document _source.
Moreover, because other fields have enabled:false, nothing is indexed, so search returns no result.
Could you try to rename that field to _from for example ?

Thanks’
Vincent

**Comment by lmangani** [comment]
Thanks Vincent,

That makes more sense - I will give this a try to confirm, but unfortunately, renaming all possible "from" fields might be tricky to achieve for users - wouldn't this translation of "reserved" keyword be best performed in dynamic mapping? Is there any Elassandra use case where a CQL FROM might be relevant when existing in ES doc field?

As of the lack of indexed elements causing no results, I was confused as this is not the case in stock ES but its quite easy to work around in Elassandra, so I'll make sure those have an indexed field/string.

_PS: Effort is to have SENTINL Watcher work in Elassandra for Alerts and Reports, etc_

**Comment by vroyer** [comment]
Elassandra generates CQL queries to insert and retrieve documents, so it might be tricky to translate a field name in both directions without any overlapping issue.
I can try to remove this limitation by quoting all identifiers in all CQL queries.

Elassandra cannot index a document with no indexed fields because Cassandra secondary index API is triggered only when a columns having an index is inserted or updated. Adding a useless indexed field solves this issue.

**Comment by lmangani** [comment]
Fully agree - mind I have zero problems changing my own fields of course, but I'm more thinking of others trying to migrate their setups/data to Elassandra and in spirit of "smoothness" for transitions

As of Index/No index it makes perfect sense and actually helps understand the Elassandra contraption even further. Thanks!

**Comment by vroyer** [comment]
I have pushed a fix for you on the master branch by removing « FROM » from the reserved keywords.
My simple test is OK, so you can try with your use case.

**Comment by lmangani** [comment]
Thanks Vincent - Rebulding and testing now

**Comment by lmangani** [comment]
"FROM" works as expected, but I immediately ran into a case of "TO" - my usual luck :)

To best understand the case and learn, could you outline how those keywords could be relevant when only presented as a document field name during CQL conversion? Shouldn't colliding names be just safely treated as double quoted strings when inserting to Cassandra via CQL?

From Cassandra docs:
```
A reserved keyword cannot be used as an identifier unless you enclose the word in double quotation marks.
```

**Comment by vroyer** [comment]
Reserved keywords are defined in org/elassandra/cluster/InternalCassandraClusterService.java:535 and check at line 1003.
I’ve already have some issues related to theses keywords, but we may try to disable the check at line 1003 since all identifiers should be well quoted now !

**Comment by lmangani** [comment]
@vroyer ok will give this a shot and send a PR if it works out

**Comment by lmangani** [comment]
I replaced all instances of ```isReservedKeyword``` with a simple logger warning and I can insert data successfully - although some JSON objects are being heavily escaped but I'll investigate that separately. Should I send a PR?

**Comment by vroyer** [comment]
Hi Lorenzo,
Could you remove the « continue » instruction in your patch, otherwise it will ignore the ES field.
Then i’ll merge your patch.
Thanks’.

**Comment by lmangani** [comment]
Issue is resolved with PR, thanks for your time and attention. Resolved.
