### ISSUE TITLE
Unable to read cassandra-rackdc.properties

### ISSUE THREAD

**Issue by hidenny** [strapdata/elassandra#82]
when I try to start the elassandra on debian, I find that it can't locate the cassandra-rackdc.properties. I have double checked the file actually exists in /opt/elassandra/conf and /etc/cassandra/cassandra-rackdc.properties.

09:01:11.875 [main] WARN  o.a.c.locator.SnitchProperties - Unable to read cassandra-rackdc.properties
Exception (org.apache.cassandra.exceptions.ConfigurationException) encountered during startup: Error instantiating snitch class 'org.apache.cassandra.locator.GossipingPropertyFileSnitch'.
org.apache.cassandra.exceptions.ConfigurationException: Error instantiating snitch class 'org.apache.cassandra.locator.GossipingPropertyFileSnitch'.
	at org.apache.cassandra.utils.FBUtilities.construct(FBUtilities.java:494)
	at org.apache.cassandra.utils.FBUtilities.construct(FBUtilities.java:472)
	at org.apache.cassandra.config.DatabaseDescriptor.createEndpointSnitch(DatabaseDescriptor.java:701)
	at org.apache.cassandra.config.DatabaseDescriptor.applyConfig(DatabaseDescriptor.java:445)
	at org.apache.cassandra.config.DatabaseDescriptor.<clinit>(DatabaseDescriptor.java:119)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:508)
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:669)
Caused by: org.apache.cassandra.exceptions.ConfigurationException: DC or rack not found in snitch properties, check your configuration in: cassandra-rackdc.properties

**Comment by vroyer** [comment]
Did you set CASSANDRA_HOME to /opt/elassandra before starting elassandra ? Elassandra locates the cassandra-rackdc.properties in $CASSANDRA_HOME/conf (as Cassandra)
