### ISSUE TITLE
Timeout when updating mapping due to new field in nested field (c* map)

### ISSUE THREAD

**Issue by kyleboyle** [strapdata/elassandra#91]
I have a single node and a table with map<text, text>. When i insert a row via cql, elassandra attempts to update the type mapping (presumably in the elastic_admin.metadata table. I'm getting a timeout in the logs for each field update, like so:

```
2017-04-10 13:48:14,726 INFO  [SharedPool-Worker-2] ElasticSecondaryIndex.java:470 addField updating mapping={"event_structured":{"properties":{"strings":{"type":"nested","cql_struct":"map","cql_collection":"singleton
","properties":{"stringProperty1":{"type":"string"}}}}}}
2017-04-10 13:48:44,727 ERROR [SharedPool-Worker-2] ElasticSecondaryIndex.java:476 addField error while updating mapping
org.elasticsearch.ElasticsearchTimeoutException: blocking update timeout
        at org.elassandra.cluster.InternalCassandraClusterService$BlockingActionListener.waitForUpdate(InternalCassandraClusterService.java:1690)
        at org.elassandra.cluster.InternalCassandraClusterService.blockingMappingUpdate(InternalCassandraClusterService.java:1717)
        at org.elassandra.index.ElasticSecondaryIndex$Context.addField(ElasticSecondaryIndex.java:472)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$RowcumentIndexer$Rowcument.buildContext(ElasticSecondaryIndex.java:1706)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$WideRowcumentIndexer$WideRowcument.buildContext(ElasticSecondaryIndex.java:1264)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$RowcumentIndexer$Rowcument.index(ElasticSecondaryIndex.java:1774)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$RowcumentIndexer$Rowcument.index(ElasticSecondaryIndex.java:1764)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$WideRowcumentIndexer$WideRowcument.index(ElasticSecondaryIndex.java:1264)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$WideRowcumentIndexer.flush(ElasticSecondaryIndex.java:1307)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$RowcumentIndexer.finish(ElasticSecondaryIndex.java:1496)
        at org.apache.cassandra.index.SecondaryIndexManager$WriteTimeTransaction.commit(SecondaryIndexManager.java:869)
        at org.apache.cassandra.db.partitions.AtomicBTreePartition.addAllWithSizeDelta(AtomicBTreePartition.java:180)
        at org.apache.cassandra.db.Memtable.put(Memtable.java:258)
        at org.apache.cassandra.db.ColumnFamilyStore.apply(ColumnFamilyStore.java:1189)
        at org.apache.cassandra.db.Keyspace.apply(Keyspace.java:558)
        at org.apache.cassandra.db.Keyspace.applyNotDeferrable(Keyspace.java:404)
        at org.apache.cassandra.db.Mutation.apply(Mutation.java:213)
        at org.apache.cassandra.db.Mutation.apply(Mutation.java:227)
        at org.apache.cassandra.service.StorageProxy$8.runMayThrow(StorageProxy.java:1344)
        at org.apache.cassandra.service.StorageProxy$LocalMutationRunnable.run(StorageProxy.java:2516)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:164)
        at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$LocalSessionFutureTask.run(AbstractLocalAwareExecutorService.java:136)
        at org.apache.cassandra.concurrent.SEPExecutor.maybeExecuteImmediately(SEPExecutor.java:192)
        at org.apache.cassandra.service.StorageProxy.performLocally(StorageProxy.java:1338)
        at org.apache.cassandra.service.StorageProxy.sendToHintedEndpoints(StorageProxy.java:1247)
        at org.apache.cassandra.service.StorageProxy$2.apply(StorageProxy.java:136)
        at org.apache.cassandra.service.StorageProxy.performWrite(StorageProxy.java:1053)
        at org.apache.cassandra.service.StorageProxy.mutate(StorageProxy.java:607)
        at org.apache.cassandra.service.StorageProxy.mutateWithTriggers(StorageProxy.java:833)
        at org.apache.cassandra.cql3.statements.ModificationStatement.executeWithoutCondition(ModificationStatement.java:422)
        at org.apache.cassandra.cql3.statements.ModificationStatement.execute(ModificationStatement.java:408)
        at org.apache.cassandra.cql3.QueryProcessor.processStatement(QueryProcessor.java:206)
        at org.apache.cassandra.cql3.QueryProcessor.process(QueryProcessor.java:237)
        at org.apache.cassandra.cql3.QueryProcessor.process(QueryProcessor.java:222)
        at org.apache.cassandra.transport.messages.QueryMessage.execute(QueryMessage.java:115)
        at org.apache.cassandra.transport.Message$Dispatcher.channelRead0(Message.java:513)
        at org.apache.cassandra.transport.Message$Dispatcher.channelRead0(Message.java:407)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
        at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:32)
        at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:283)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:164)
        at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:105)
        at java.lang.Thread.run(Thread.java:745)
```

Here, my map<text,text> column name is 'strings' and the key in the map is 'stringProperty1'. 

The metadata table does have the initial index settings created using the discover method.

I'm able to insert data into my table successfully when it does not have a secondary index.

Both my keyspace and the elastic_admin keyspace have the same replication = {
	'class' : 'NetworkTopologyStrategy',
	'DC1' : 1
}

Is this a single node issue perhaps?

**Comment by vroyer** [comment]
It should work in a single node cluster, a soon as your datacenter is DC1 (case sensitive) in your cassandra snitch definition. Assuming this is good, could you share your CQL schema to reproduce the issue ?

**Comment by kyleboyle** [comment]
Yes I have DC1 in both cassandra-rackdc.properties and cassandra-topology.properties, my snitch is using the default GossipingPropertyFileSnitch

minimal schema is:
```
CREATE TABLE keyspace1.event_test (
  id text,
  strings map<text, text>,
  PRIMARY KEY (id)
);
```
created index with:

```
curl -XPUT "http://node1:9200/event_test_index" -d '{
  "settings": {
      "keyspace":"keyspace1"
  },
  "mappings": {
      "event_test" : { "discover" : ".*" }
  }
}'
```
Then I insert a row via cql, and get a write timeout on the client.

```
2017-04-10 14:37:26,143 DEBUG [elasticsearch[192.168.122.180][clusterService#updateTask][T#1]] CassandraIndicesClusterStateService.java:211 applyNewIndices [192.168.122.180] [event_test_index] creating index
2017-04-10 14:37:26,147 DEBUG [elasticsearch[192.168.122.180][clusterService#updateTask][T#1]] CassandraIndicesClusterStateService.java:224 applyNewIndices [192.168.122.180] [event_test_index][0] creating shard
2017-04-10 14:37:26,149 DEBUG [elasticsearch[192.168.122.180][clusterService#updateTask][T#1]] CassandraIndicesClusterStateService.java:237 applyNewIndices [192.168.122.180] [event_test_index][0] creating shard
2017-04-10 14:37:26,356 DEBUG [elasticsearch[192.168.122.180][clusterService#updateTask][T#1]] CassandraIndicesClusterStateService.java:244 onRecoveryDone [192.168.122.180] [event_test_index][0] recovery done, shard s
tate=POST_RECOVERY
2017-04-10 14:37:26,356 DEBUG [elasticsearch[192.168.122.180][clusterService#updateTask][T#1]] CassandraIndicesClusterStateService.java:359 processMapping [192.168.122.180] [event_test_index] adding mapping [event_tes
t], source [{"event_test":{"properties":{"id":{"type":"string","index":"not_analyzed","cql_collection":"singleton","cql_partition_key":true,"cql_primary_key_order":0},"strings":{"type":"nested","cql_struct":"map","cql
_collection":"singleton"}}}}]
2017-04-10 14:37:26,357 DEBUG [elasticsearch[192.168.122.180][clusterService#updateTask][T#1]] CassandraSecondaryIndicesListener.java:70 clusterChanged Creating secondary indices for table=keyspace1.event_test with class=org.elassandra.index.ExtendedElasticSecondaryIndex
2017-04-10 14:37:28,522 WARN  [MemtablePostFlush:7] ElasticSecondaryIndex.java:1908 isIndexing No Elasticsearch index ready
2017-04-10 14:39:10,520 INFO  [SharedPool-Worker-2] ElasticSecondaryIndex.java:470 addField updating mapping={"event_test":{"properties":{"strings":{"type":"nested","cql_struct":"map","cql_collection":"singleton","properties":{"stringProp1":{"type":"string"}}}}}}
2017-04-10 14:39:40,521 ERROR [SharedPool-Worker-2] ElasticSecondaryIndex.java:476 addField error while updating mapping
org.elasticsearch.ElasticsearchTimeoutException: blocking update timeout
        at org.elassandra.cluster.InternalCassandraClusterService$BlockingActionListener.waitForUpdate(InternalCassandraClusterService.java:1690)
        at org.elassandra.cluster.InternalCassandraClusterService.blockingMappingUpdate(InternalCassandraClusterService.java:1717)
        at org.elassandra.index.ElasticSecondaryIndex$Context.addField(ElasticSecondaryIndex.java:472)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$RowcumentIndexer$Rowcument.buildContext(ElasticSecondaryIndex.java:1706)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$SkinnyRowcumentIndexer$SkinnyRowcument.buildContext(ElasticSecondaryIndex.java:1352)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$RowcumentIndexer$Rowcument.index(ElasticSecondaryIndex.java:1774)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$RowcumentIndexer$Rowcument.index(ElasticSecondaryIndex.java:1764)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$SkinnyRowcumentIndexer$SkinnyRowcument.index(ElasticSecondaryIndex.java:1352)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$SkinnyRowcumentIndexer.flush(ElasticSecondaryIndex.java:1382)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$RowcumentIndexer.finish(ElasticSecondaryIndex.java:1496)
        at org.apache.cassandra.index.SecondaryIndexManager$WriteTimeTransaction.commit(SecondaryIndexManager.java:869)
        at org.apache.cassandra.db.partitions.AtomicBTreePartition.addAllWithSizeDelta(AtomicBTreePartition.java:180)
        at org.apache.cassandra.db.Memtable.put(Memtable.java:258)
        at org.apache.cassandra.db.ColumnFamilyStore.apply(ColumnFamilyStore.java:1189)
        at org.apache.cassandra.db.Keyspace.apply(Keyspace.java:558)
        at org.apache.cassandra.db.Keyspace.applyNotDeferrable(Keyspace.java:404)
        at org.apache.cassandra.db.Mutation.apply(Mutation.java:213)
        at org.apache.cassandra.db.Mutation.apply(Mutation.java:227)
        at org.apache.cassandra.service.StorageProxy$8.runMayThrow(StorageProxy.java:1344)
        at org.apache.cassandra.service.StorageProxy$LocalMutationRunnable.run(StorageProxy.java:2516)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:164)
        at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$LocalSessionFutureTask.run(AbstractLocalAwareExecutorService.java:136)
        at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:105)
        at java.lang.Thread.run(Thread.java:745)
```

There is an addField+timeout for each key in the map.

Is the addField write using a replication factor that isn't compatible with a single node? Eventually after all the timeouts occur the metadata for the index contains the map keys.

**Comment by kyleboyle** [comment]
FYI, I patched in jar from newest tag 11 and get same behaviour.

I get the same behaviour on both local dev machine (macos running on localhost) and a linux machine running on the eth0 interface.

**Comment by loint** [comment]
We had same issue when trying to mapping type Map in Cassandra to Elastic Search. 
@vroyer Could you please help to investigate with type "map" in Cassandra ? Sometimes it hangs when trying to create mapping to ES in multiple nodes but I'm not sure we have tests for multiple nodes.

"@vroyer It should work in a single node cluster" => in the real life, it should works with multiple nodes.

**Comment by vroyer** [comment]
I released a fix in version 2.4.2-12.

**Comment by kyleboyle** [comment]
Confirmed on single node. thanks

**Comment by loint** [comment]
@vroyer Thanks for proactive and nice patch. Do we have any contribution guidelines ? I wish to do something if any issue can create PR but searching for a starting point from your commits.

**Comment by loint** [comment]
I found something in your commit.
```
mvn test -Pdev -pl com.strapdata:elassandra -Dtests.seed=622A2B0618CE4676 -Dtests.class=org.elassandra.CqlTypesTests -Dtests.method="testMapAsObject" -Des.logger.level=ERROR -Dtests.assertion.disabled=false -Dtests.security.manager=false -Dtests.heap.size=1024m -Dtests.locale=ro-RO -Dtests.timezone=America/Toronto
```

This line only help to run unit tests but is that enough to verify mapping to ES or do we need a full running for single/multiple nodes every patch ?

**Comment by vroyer** [comment]
I have added this unit test to detect a write timeout, but of course, many other checks could be done, including mapping check in various cases.
Right now, the test framework works on a single node cluster (see explanation in http://doc.elassandra.io/en/latest/testing.html <http://doc.elassandra.io/en/latest/testing.html> ). 
We are going to deliver ecm, a modified version of https://github.com/pcmanus/ccm <https://github.com/pcmanus/ccm>, to be able to play multi-nodes tests, and this should run with elasticsearch rally for benchmarking.

**Comment by loint** [comment]
Thanks for your info. I will try with your simple quick start. Looking forward to ccm.
