### ISSUE TITLE
Error while building from source

### ISSUE THREAD

**Issue by pct960** [strapdata/elassandra#93]
Hi! I'm trying to build elassandra from source using maven. However I end up getting the error (given below) no matter how much I try. I tried setting the JAVA_HOME variable and making some tweaks in the pom.xml file. But nothing worked.

`Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project elassandra`

**Comment by vroyer** [comment]
Do you have java 1.8+ correctly installed ?

**Comment by pct960** [comment]
Yes, I do. When I run `java -version `I get
```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

My JAVA_HOME is set to `JAVA_HOME=/usr/lib/jvm/jdk1.8.0_131`

I have been at it for more than 36 hours now. Nothing seems to work. Every attempt ends at:

`Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project elassandra`

Please let me know where I'm going wrong.

**Comment by vroyer** [comment]
Could you run `mvn -X -e package -DskipTests` and post the output.
Thanks.

**Comment by pct960** [comment]
`Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project elassandra: Compilation failure -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project elassandra: Compilation failure
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:976)
	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)`

**Comment by vroyer** [comment]
Thanks, but could you include, the directory path where you launch maven, the full command and the full output ?
What is your maven version ? We use version 3.3.9.

**Comment by pct960** [comment]
Path where I launch the maven command: `/root/elassandra`
Command used: `mvn -X -e package -DskipTests`
When I run `mvn -version` I get
```
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /usr/lib/jvm/jdk1.8.0_131/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-72-generic", arch: "amd64", family: "unix"
```
The output is too long (about 100,000 lines) to post here

**Comment by vroyer** [comment]
Could redirect your output in a file and attach it to the issue ?

**Comment by pct960** [comment]
Here it is. It is around 64,000 lines long. It builds up to "Elassandra Core" after which it fails.

[output.txt](https://github.com/strapdata/elassandra/files/955830/output.txt)

**Comment by vroyer** [comment]
According to your logs, this is a maven or javac issue,  probably due to your environnement.

**Comment by pct960** [comment]
Well, that was my hunch too. But I was hoping you'd give a deeper insight into the problem. Java is installed correctly, JAVA_HOME is set correctly and maven is installed properly. As far as I can tell, I'm not doing anything wrong on my side.

**Comment by vroyer** [comment]
It’s a java compiler issue, you may try to compile some other project, it can be a memory or system issue…
You can also use the tarball installation...

**Comment by pct960** [comment]
Alright thanks!
